### ISSUE TITLE
Doc: Create GETTING_STARTED.md inside .github folder

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#103]
**Is your feature request related to a problem? Please describe.**
The [Getting Started](https://github.com/anitab-org/bridge-in-tech-web/wiki/Getting-Started) page on the bridge-in-tech-web wiki is currently not written as a markdown document, but directly written as a wiki page. The content on this page needs to be made available to contributors so they can also involve in improving the page documentation.

**Describe the solution you'd like**
Create a markdown file `GETTING_STARTED.md` inside `.github` folder and place the content on the  [Getting Started](https://github.com/anitab-org/bridge-in-tech-web/wiki/Getting-Started) page inside that doc so that the wiki sidebar can refer to the doc instead of having the content written as a wiki page.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by mtreacy002** [comment]
@anishghimire603 , while there is no restriction to work on another `First-Timers-Only` issue as long as it is in a separate repo to the one you have done, it is recommended to focus on one issue at a time. I've only just assigned you to the [backend issue#142](https://github.com/anitab-org/bridge-in-tech-backend/issues/142), so please work on that issue first, submit a PR, then while waiting for the PR to be reviewed, you can look for another issue and claim them if you are interested. This is also to give chance to other members in the community to participate in the project. Does this make sense?

**Comment by anishghimire603** [comment]
@mtreacy002 sure!!!

**Comment by KapilBansal320** [comment]
@mtreacy002 Can I work on this issue?

**Comment by imrishabh18** [comment]
Hey @mtreacy002 , I will like to take up this isssue.

**Comment by mtreacy002** [comment]
@imrishabh18 , let me check with @anishghimire603 first if he is still interested to work on this issue as he’s The first one to express interest on this and his other PR on backend repo was already approved and merged. @anishghimire603 , can you please tell us your position? Would you like to work on this now or can I assign this to @imrishabh18 ?

**Comment by anishghimire603** [comment]
yeah it will be great if I can work on this. you can assign me this.

**Comment by lopeselio** [comment]
Hey, I would like to take up this issue

**Comment by mtreacy002** [comment]
@lopeselio , @anishghimire603 is the first one on the list to show interest to the issue. So, I'll assign him to this. You can check other available issues [here](https://github.com/anitab-org/bridge-in-tech-web/issues), If you can't find one, you can also suggest an issue by checking which area of the code could be improved. I'm planning to open more issues soon. So keep an 👀 for them. 😁

**Comment by mtreacy002** [comment]
@anishghimire603 . You can work on this now.
