### ISSUE TITLE
Bug: Organizations list table content is overflowing outside container

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#105]
**Describe the bug**
The view page for organizations list doesn't look right. The table content is overflowing outside the table container.

**To Reproduce**
1. run the application
2. login as user
3. Click `Organizations` from the menu bar to view the list of organizations (note: make sure you have created at least one organization to view the organizations table)
4. See error (see screenshot section)

**Expected behavior**
The table content must be inside table container.

**Screenshots**
<img width="1680" alt="Screen Shot 2020-09-21 at 9 14 26 pm" src="https://user-images.githubusercontent.com/29667122/93760846-1a79e200-fc50-11ea-860d-3fd779f8a672.png">

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version ??

**Additional context**
NA

**Comment by RiaDhanani** [comment]
Can I work on this issue?

**Comment by mtreacy002** [comment]
Sure, @RiaDhanani, I'll assign you to this . Wellcome to BridgeInTech. 🎉🎉

**Comment by mtreacy002** [comment]
@RiaDhanani , can you please give us an update on your progress?

**Comment by RiaDhanani** [comment]
I tried to run the backend server on Heroku but it always says server unavailable and I'm facing some issues in the local setup.  Can you give me a day or two to get it working?

**Comment by mtreacy002** [comment]
Hi @RiaDhanani . Heroku servers are currently unavailable because there are limitations of Heroku free service that makes it impossible for BridgeInTech to use Heroku as remote deployment option. This is out of our control. I explained this issue in detail in my [medium blog](https://medium.com/anitab-org-open-source/why-you-cant-use-heroku-free-dynos-in-multiple-servers-dependent-application-fa1cdd9e9e07?source=friends_link&sk=281bb76050f052c03c6772e9be275f67). For now the only option for contributor is to run all 3 servers (BIT backend and frontend as well as MS backend) locally. Let me know if you need any help setting up locally.

**Comment by mtreacy002** [comment]
@RiaDhanani, since I haven't heard any updates from you, I'll label this issue as available again.

**Comment by somayaj** [comment]
Can I work this request?

**Comment by mtreacy002** [comment]
Sure, @somayaj . I'll assign you to this 😉
