### ISSUE TITLE
Feat: Hide Organization container when user has not declare they are representing organization

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#106]
**Is your feature request related to a problem? Please describe.**
When a new registered user login, by default their Additional Info `is_organization_representative` is set to `False'. Currently there is no information can be found on how organization user can create organization. 

**Describe the solution you'd like**
To be able to create an organization, a user has to tick the box `I am a representative of an organization` on the Additional Info form to change the `is_organization_value` value to `True`.
<img width="1168" alt="Screen Shot 2020-09-21 at 10 09 51 pm" src="https://user-images.githubusercontent.com/29667122/93765048-99bee400-fc57-11ea-852e-d91a2b77a0d2.png">
 
An instruction need to be placed under `You have not declared that you are reperesenting an organization` on the `My Organization` page. 
<img width="1278" alt="Screen Shot 2020-09-21 at 9 48 05 pm" src="https://user-images.githubusercontent.com/29667122/93765362-18b41c80-fc58-11ea-8803-4d3c206e8e8e.png">

It can be something like: 
To do this, please tick the box on the Additional Information form which can be found under "My Space" tab.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by tichnas** [comment]
Hi, I would love to work on this. Can I please be assigned?

**Comment by mtreacy002** [comment]
Sure, @tichnas , I'll assign you to this. Thanks for picking this up 👍

**Comment by tichnas** [comment]
I'm working on it, but it may take some time because I have to set up the backend locally, and I'm new to those technologies.

**Comment by mtreacy002** [comment]
That's fine, @tichnas . Take your time. This is why we go open source 😁😁, so we could have hands-on learning on the tech stack we're interested in 😉.
Let me know if you need help with anything.

**Comment by tichnas** [comment]
@mtreacy002 Sorry to disturb you but can you please help me with setting up the backend?
When I run `pip install -r requirements.txt` from the virtual environment, I'm getting an error. The output is very long, but you can see the relevant part here: https://pastebin.com/21avXjY6
I tried to google stuff, but no luck. As far as I can understand, there is some problem with `cffi` and `cryptography`, so I installed them separately but still not working. Anything I'm doing wrong?

**Comment by mtreacy002** [comment]
@tichnas , can you please tell me you computer spec? OS and its version, which terminal and python version you're using?

**Comment by tichnas** [comment]
@mtreacy002 I'm using Ubuntu 20.04 with Python 3.8.2 in bash terminal with bash version 5.0.17

**Comment by mtreacy002** [comment]
@tichnas, there is a possibility this is caused by the python version you are using. There was someone on [Zulip](https://anitab-org.zulipchat.com/#narrow/stream/222534-mentorship-system/topic/mentorship-backend/near/210260931) had lots of different problem setting up mentorship system backend (which is using similar dependencies with BridgeInTech) on Windows 10 machine, git bash terminal, python 3.8.5. Only after we tried to download python 3.7.5 on her machine and made it the default python to run from the terminal, the issue was solved. 
You could give this a try. let me know how you go.

PS: this might be machine specific as well, since there's another person using windows 10 (not sure which terminal) but she has no issue setting up MS backend.

**Comment by mtreacy002** [comment]
@tichnas , are you able to resolve the issue? If not, there's a [bug report issue#157](https://github.com/anitab-org/bridge-in-tech-backend/issues/157) raised by another contributor also facing the same issue as you. After checking with MS backend, I recommend to remove the cffi (not the cryptography) from the dependencies. You can try this locally as well and see if this works for you.

**Comment by mtreacy002** [comment]
@tichnas , the PR i mentioned above has just merged to develop. If you pull the latest update from the backend develop branch and try install dependencied again, you shouldn't have the same issue. Please try and let me know how you go.

**Comment by tichnas** [comment]
@mtreacy002 Sorry for late reply, I was quite busy for past few days. I managed to solve the issue by your advice and some googling.

**Comment by mtreacy002** [comment]
@tichnas , can you please give me an update on this task?

**Comment by mtreacy002** [comment]
@tichnas ,since there is no update for a while and there are other issues (#86 and #87) that should be able to achieve similar outcome (user won't be able to proceed to programs), should I close this issue (if you are not working on it)

**Comment by mtreacy002** [comment]
Closing this issue now 😉
