### ISSUE TITLE
Doc: Add Build badge for Travis CI to README

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#108]
## Description
As a contributor,
I need to see Build badge,
so that I can see the status of the latest Travis CI build.

## Mocks
NA

### Update [Required]
- [ ] Add Build badge for Travis CI build. [Refer to the following resource on how to do it](https://docs.travis-ci.com/user/status-images/)

### Enhamcement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by AltCtrlDel1999** [comment]
Can I work on these issue?

**Comment by AltCtrlDel1999** [comment]
Hey but I'm not a member of AnitaB currently so I will not have access to Travis ci of BIT?
I'm new to open source development, kindly help.

**Comment by AltCtrlDel1999** [comment]
@mtreacy002 I'm done with changes waiting to get assign

**Comment by mtreacy002** [comment]
@AltCtrlDel1999 , make sure next time you wait to be assign before you start working on an issue, so to follow the workflow. I'll assign you to this now.

**Comment by AltCtrlDel1999** [comment]
@mtreacy002 I will make sure next time
