### ISSUE TITLE
Doc: Add Zulip badge to README

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#109]
## Description
As a contributor,
I need add the project Zulip channel to README,
so that I can clearly see where to go if I want to join the community Zulip Channel.

### Update [Required]
- [ ] Add Zulip badge to README with link to [#bridge-in-tech](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech) zulip channel 

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by anishghimire603** [comment]
can I work on this Issue.

**Comment by madhhuurrii** [comment]
Hi, Can I work on this issue ?

**Comment by mtreacy002** [comment]
@anishghimire603 , since you already contributed to an issue before on this repo, I'll assign this to @madhhuurrii as this is a first-timers-only issue.
