### ISSUE TITLE
Feat: Design UI for 404:Error Page for default redirects.

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/bridge-in-tech-web#115]
## Is your feature request related to a problem? Please describe.

Currently, there is no feature to redirect the user to a specific Error 404 Page when they enter the wrong URLs. There should be a design and change in Route paths for this.

## Describe the solution you'd like

- Design a 404 Error Page

- Route redirect to implement this.

## Describe alternatives you've considered
  N/A

## Additional context
Would like to work on this.

**Comment by Aaishpra** [comment]
@mtreacy002 have a look.

**Comment by vj-codes** [comment]
@Aaishpra after the issue is reviewed , will you be working on this?
If not , I would like to work :)

**Comment by Aaishpra** [comment]
> @Aaishpra after the issue is reviewed , will you be working on this?
> If not , I would like to work :)

Hey @vj-codes thanks for showing interest for working on the issue but, since i am currently not working on any other issue so would like to work on this.😅

**Comment by Aaishpra** [comment]
Ping @mtreacy002

**Comment by mtreacy002** [comment]
Sorry for the late reply, @Aaishpra . I'll assign this issue to you now 😉

**Comment by Aaishpra** [comment]
> Sorry for the late reply, @Aaishpra . I'll assign this issue to you now 😉

Sure

**Comment by Aaishpra** [comment]
@mtreacy002 
Update: Since my mid semester exams are scheduled in  few days so I am very busy with my University's work . That's why, i would make  the PR by next Wednesday when i am done with them.
Hope you are fine with this .

**Comment by mtreacy002** [comment]
Sure, @Aaishpra . Take your time. Thanks for letting me know. Good luck with your mid exam too.

**Comment by Aaishpra** [comment]
@mtreacy002 the initial design is here, can you tell me which colour you want the header to be, or any other change
![image](https://user-images.githubusercontent.com/66299533/96831283-63dd6d00-145a-11eb-8ac5-39abe02e763d.png)

**Comment by mtreacy002** [comment]
This looks good, @Aaishpra . I'll review the PR as soon as I have time.

**Comment by Aaishpra** [comment]
> This looks good, @Aaishpra . I'll review the PR as soon as I have time.

Sure, @mtreacy002 take your time to review.
