### ISSUE TITLE
Feat: Design Navbar

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [anitab-org/bridge-in-tech-web#117]
## Description
As a public user,
I need to see a well maintained and designed navbar ,
so that I can navigate properly through the website.

## Mocks
As of the [Design](https://www.figma.com/file/jxCqu1lq55H7jC4FDY119a/BridgeInTech?node-id=10%3A1) , Add the proper design to navbar.
![Screenshot (128)](https://user-images.githubusercontent.com/56167998/95375886-e5cb8300-08fd-11eb-84d4-4ab8a6cc40da.png)

### Update [Required]
- [ ] Avoid changing the other things in this PR.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day.

**Comment by prathmeshkhandelwal1** [comment]
@mtreacy002 Have a look please.

**Comment by mtreacy002** [comment]
Thank you, @prathmeshkhandelwal1 for opening this issue. I've assigned you to this.

**Comment by prathmeshkhandelwal1** [comment]
> Thank you, @prathmeshkhandelwal1 for opening this issue. I've assigned you to this.

Sure, will do a PR ASAP

**Comment by prathmeshkhandelwal1** [comment]
As in this project react-bootstrap is used in making navbar so it is the best i can customize it according to the design can you plzz check it and tell me whether i should do a PR or NOT @mtreacy002 
![Screenshot (140)](https://user-images.githubusercontent.com/56167998/96233757-225e4500-0fb6-11eb-80e2-5c7d33415449.png)

**Comment by mtreacy002** [comment]
> As in this project react-bootstrap is used in making navbar so it is the best i can customize it according to the design can you plzz check it and tell me whether i should do a PR or NOT @mtreacy002
> ![Screenshot (140)](https://user-images.githubusercontent.com/56167998/96233757-225e4500-0fb6-11eb-80e2-5c7d33415449.png)

This looks good, @prathmeshkhandelwal1 . Can you tell me if the dropdown submenu still the same (under main navbar item) or are you planning to add a separate sub navbar as per the figma design? I'm happy with either one. And yes, you can open a PR on this, please 😉 .

**Comment by prathmeshkhandelwal1** [comment]
> > As in this project react-bootstrap is used in making navbar so it is the best i can customize it according to the design can you plzz check it and tell me whether i should do a PR or NOT @mtreacy002
> > ![Screenshot (140)](https://user-images.githubusercontent.com/56167998/96233757-225e4500-0fb6-11eb-80e2-5c7d33415449.png)
> 
> This looks good, @prathmeshkhandelwal1 . Can you tell me if the dropdown submenu still the same (under main navbar item) or are you planning to add a separate sub navbar as per the figma design? I'm happy with either one. And yes, you can open a PR on this, please 😉 .

its the same as it was before just the layout of navbar is change(on clicking the `home` drop-down will appear. Accordian is used in this )...i tried adding other one..but this looks good..so i stayed with this...okk i will open i PR with little brush up.
