### ISSUE TITLE
Setup Travis CI to run tests for BIT React frontend

### ISSUE THREAD

**Issue by meenakshi-dhanani** [anitab-org/bridge-in-tech-web#12]
## Description
As a developer,
I need run tests on every PR on CI,
so that I can immediately get feedback on a build

## Out of Scope
Deploying to a higher environment when the push is on the develop branch

## Acceptance Criteria
- [ ] Build gets triggered on push
- [ ] Tests run for build

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
1-2 hours

**Comment by meenakshi-dhanani** [comment]
@isabelcosta This issue will not deal with deploying, this is at minimum to run tests. Is there a higher environment though(heroku/aws/any other) that we have where we can deploy and see BIT? We could make it part of the future issue for setting up in Travis

**Comment by isabelcosta** [comment]
@meenakshi-dhanani https://github.com/anitab-org/bridge-in-tech-backend/issues/22#issuecomment-636314931 yes. Until @mayburgos gets back to use with updates from AWS, we can use Heroku. That is what we are using at MS backend. Could we use it for Web as well?

**Comment by meenakshi-dhanani** [comment]
@isabelcosta Thank you. Would be good to use for front end as well, where can I access it as a developer? Not sure if I require separate credentials for that?

**Comment by isabelcosta** [comment]
@meenakshi-dhanani , @mtreacy002 can provide you access to the mentorship-backend-bit deployed heroku app, as she has owenership of that.
