### ISSUE TITLE
Doc: Add existing UI screenshots to README.md

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#120]
**Is your feature request related to a problem? Please describe.**
It would be ideal to see existing screenshots of all existing UIs.

**Describe the solution you'd like**
Create a section called UI screenshots inside README.md (under `Run the app` section) and place screenshots of all existing UIs.

**Describe alternatives you've considered**
Screenshots can be replaced with GIFs

**Additional context**
NA

**Comment by mctraore** [comment]
I am interested in working on this issue.

**Comment by mtreacy002** [comment]
sure, @mctraore . I'll assign this to you.

**Comment by ankitpal1029** [comment]
is this issue still open?

**Comment by jhalak27** [comment]
Hey, If this issue is available, I would like to work on it.

**Comment by khushishikhu** [comment]
@mtreacy002  may i work on this

**Comment by ankitpal1029** [comment]
i'm interested in working on this

**Comment by mtreacy002** [comment]
@jhalak27. If you are still interested I'll assign this to you since you've never contributed to the repo before (aka first-timer) and you're the next eligible on the list to claim the issue.

**Comment by jhalak27** [comment]
Yes. Sure

**Comment by jhalak27** [comment]
@mtreacy002 could you tell where can I find existing screenshots?

**Comment by mtreacy002** [comment]
@jhalak27 . To do this, you need to locally run all 3 servers (BIT web, BIT and MS backend) and manually take screenshots of all pages/features available on BIT web. Does this make sense?

**Comment by devkapilbansal** [comment]
@jhalak27 are you working on this issue? Please post your progress in every 3-4 days so that maintainers can know the status of the issue

**Comment by jhalak27** [comment]
I am really sorry. I got stuck with some college things.
I will try to get this done.

**Comment by amlannandy** [comment]
Hello. If no one is working on this currently, then I'd like to do so.

**Comment by nlok5923** [comment]
@mtreacy002  I would like to work on this issue if no one is currently working on it.

**Comment by mtreacy002** [comment]
@jhalak27. Are you still working on this issue? If not, I'll make it available for anyone to pick up.

**Comment by jhalak27** [comment]
Extremely sorry, I wasn't able to work on this. I have unassigned myself.

**Comment by amlannandy** [comment]
@mtreacy002 Hello. I'd like to work on this issue. I had commented earlier and just saw it's open. Could you please assign it to me if that's okay?

**Comment by mtreacy002** [comment]
No worries, @jhalak27, thanks for letting us know. @amlannandy, I'll assign you to this now. Thanks for picking it up.
