### ISSUE TITLE
Feat : Design Homepage wireframe for bridge-in-tech-web

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/bridge-in-tech-web#126]
## Is your feature request related to a problem? Please describe.
Currently, the Project doesn't have a Homepage , when the user visits the project the following  under construction page is shown to them

![image](https://user-images.githubusercontent.com/66299533/97110044-0288f880-16fd-11eb-9f07-7ab9fd351c6a.png)

## Describe the solution you'd like

Design the Homepage wireframe using figma or adobe which can be considerd while designing/coding the actual Homepage
 

## Additional context

Please take care of the colour scheme of the project and navbar while designing.

**Comment by Aaishpra** [comment]
@mtreacy002 have a look at the issue and add the required labels. Also, the issue is up for grabs, for anyone who would like to work on it.

**Comment by Aaishpra** [comment]
@mtreacy002 since no one has claimed this issue, i would like to work on this as it would be a nice opportunity for me to learn about designing and working with figma😅

**Comment by purnima143** [comment]
@Aaishpra @mtreacy002  Can I work on this issue?

**Comment by purnima143** [comment]
I have a design on my mind, If you give me chance I'll love to implement in this project😊

**Comment by mtreacy002** [comment]
@purnima143 , since @Aaishpra opened and claimed the issue first, I'll assign this to her. You could ask if she's happy to share the workload so that the two of you can work together on this.

**Comment by purnima143** [comment]
@Aaishpra It would be great if we both work together on this issue. What's your opinion?

**Comment by Aaishpra** [comment]
> @Aaishpra It would be great if we both work together on this issue. What's your opinion?

Well sure let's do this @mtreacy002 you can assign this issue to @purnima143  also i would like to work with her.

**Comment by mtreacy002** [comment]
Sure thing, @Aaishpra . Will add @purnima143 as another assignee

**Comment by purnima143** [comment]
@Aaishpra Please check the below link
https://www.figma.com/file/gfjEZw4s8wImBjdRTmFbNa/AnitaB-landing-page?node-id=0%3A1

**Comment by Aaishpra** [comment]
> @Aaishpra Please check the below link
> https://www.figma.com/file/gfjEZw4s8wImBjdRTmFbNa/AnitaB-landing-page?node-id=0%3A1

I have posted my comment there , please check that out.

**Comment by Aaishpra** [comment]
@mtreacy002 have a look at the first draft. Most of this was prepared by @purnima143. 
![image](https://user-images.githubusercontent.com/66299533/98253549-2839bb80-1fa1-11eb-8681-146a8f813e43.png)

**Comment by purnima143** [comment]
@mtreacy002  @Aaishpra have a look at this UI, If you both agree then we can move forward to coding. Let me know what all the changes are required.
![image](https://user-images.githubusercontent.com/57852378/98266819-bc5f4f00-1fb0-11eb-830d-3938213115a0.png)

**Comment by Aaishpra** [comment]
> @mtreacy002 @Aaishpra have a look at this UI, If you both agree then we can move forward to coding. Let me know what all the changes are required.
> ![image](https://user-images.githubusercontent.com/57852378/98266819-bc5f4f00-1fb0-11eb-830d-3938213115a0.png)

It's good to go from my side.

**Comment by purnima143** [comment]
@Aaishpra  Can we move to implement part,i.e. coding

**Comment by Aaishpra** [comment]
> @Aaishpra  Can we move to implement part,i.e. coding

We first need @mtreacy002 to review this

**Comment by marthaerm** [comment]
Hi! I would like to know if this design is already reviewed. I would like to help with the code implementation! :)

**Comment by mtreacy002** [comment]
> > @mtreacy002 @Aaishpra have a look at this UI, If you both agree then we can move forward to coding. Let me know what all the changes are required.
> > ![image](https://user-images.githubusercontent.com/57852378/98266819-bc5f4f00-1fb0-11eb-830d-3938213115a0.png)
> 
> It's good to go from my side.

Sorry for the late reply, @Aaishpra and @purnima143. I love the proposed design here 😍 !!!
Both of you have done an amazing job with the design. You can move forward to the code implementation.
@marthaerm, thanks for your interest on the issue. But I'll give the first chance to @Aaishpra and @purnima143 as they came up with the design.

**Comment by marthaerm** [comment]
@mtreacy002 thank you! I'll be aware of some new issues, and @Aaishpra @purnima143 the design looks really cool! if you need help you can ask me, probably we can work together on some new pages :)

**Comment by Aaishpra** [comment]
> @mtreacy002 thank you! I'll be aware of some new issues, and @Aaishpra @purnima143 the design looks really cool! if you need help you can ask me, probably we can work together on some new pages :)

Thanks for your kind words would surely ping you if I find something worth working on together.

**Comment by marianayap** [comment]
Hello! I'm interested in this issue and I'll like to know if is already taken to see the chance of taking it. I'm like design and I can help with the code. I'll like to know if you have new issues to work on
Thank you! I'll wait for the answer @Aaishpra

**Comment by purnima143** [comment]
@marianayap  Sorry but its already assigned to @Aaishpra  and me, but there are many more pages in this project to redesign ...like about page, contact page etc. @marthaerm and @marianayap can work on it once issue will get created 😊

**Comment by Aaishpra** [comment]
> @marianayap Sorry but its already assigned to @Aaishpra and me, but there are many more pages in this project to redesign ...like about page, contact page etc. @marthaerm and @marianayap can work on it once issue will get created 😊

Agreed. @marianayap i  would create some design related issues if i find until then feel free to claim other issues.

**Comment by purnima143** [comment]
@Aaishpra Can you can go ahead with the navbar and the remaining part I'll work on. Is it fine or do you have any other idea in your mind...? Anyhow the homepage doesn't only has the intro section it will go long along with about, benefit and footer section. So we can work on many more section of the homepage.

**Comment by Aaishpra** [comment]
> @Aaishpra Can I work on the homepage and you can go ahead with the navbar. Is it fine or do you have any other idea in your mind...? Anyhow the homepage doesn't only has the intro section it will go long along with about, benefit and footer section. So we can work on many more section of the homepage.

@purnima143 I am not sure if the navbar needs to get changed (since it was recently changed), if it does we can go ahead as you suggested. Also, this particular issue is about the Landing Page, so we don't need to go ahead with other pages, let others do the rest.
@mtreacy002 what are your thoughts about the navbar should we change it or keep it ( the current navbar)?

**Comment by mtreacy002** [comment]
@Aaishpra , can you adopt the current navbar that just recently been adopted to your design? If you can give a screenshot of how the design looks with the current navbar, that will be great.

**Comment by Aaishpra** [comment]
> @Aaishpra , can you adopt the current navbar that just recently been adopted to your design? If you can give a screenshot of how the design looks with the current navbar, that will be great.

Sure thing, will show you the design by tomorrow.

**Comment by purnima143** [comment]
I did the coding part long back... @mtreacy002  and @Aaishpra  check it out...and whatever changes you need on navbar or any other components let me know.
![image](https://user-images.githubusercontent.com/57852378/100881548-0fef8a80-34d4-11eb-9947-160b99b73abe.png)

**Comment by Aaishpra** [comment]
> I did the coding part long back... @mtreacy002  and @Aaishpra  check it out...and whatever changes you need on navbar or any other components let me know.
> ![image](https://user-images.githubusercontent.com/57852378/100881548-0fef8a80-34d4-11eb-9947-160b99b73abe.png)
> 

@purnima143 there were about, benefit and contact page under home section and some other pages under my space section  in navbar have you included those?

**Comment by purnima143** [comment]
@Aaishpra I changed some of the css codes... everything is working even the  about benefit drop-down part.

**Comment by Aaishpra** [comment]
> @Aaishpra , can you adopt the current navbar that just recently been adopted to your design? If you can give a screenshot of how the design looks with the current navbar, that will be great.



@mtreacy002 here is the design with current navbar
![image](https://user-images.githubusercontent.com/66299533/100975048-63f58000-3563-11eb-9929-e00641208433.png)

**Comment by mtreacy002** [comment]
@Aaishpra, the design with the latest navbar looks good 👍 . It's a green light from me 😉

**Comment by Aaishpra** [comment]
@purnima143 can you put back the navbar as original one and submit the Pr for the home section.

**Comment by purnima143** [comment]
@Aaishpra  Okay
