### ISSUE TITLE
logo doesn't displayed

### ISSUE THREAD

**Issue by nlok5923** [anitab-org/bridge-in-tech-web#129]
**Describe the bug**
AnitaBorg logo doesn't displayed.

**To Reproduce**
1. Go to BIT web landing page'

**Expected behavior**
Navigation bar should contain logo on top left side.

**Screenshots**
![Screenshot (1642)](https://user-images.githubusercontent.com/56120084/100520258-e2000280-31c2-11eb-977b-667079291319.png)

**Desktop (please complete the following information):**
 - OS: Windows [e.g. iOS]
 - Browser:chrome  [e.g. chrome, safari]
 - Version: 32 [e.g. 22]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nlok5923** [comment]
i would like to work on this issue.

**Comment by codewithvk** [comment]
I  would happy to work with this issue

**Comment by purnima143** [comment]
@nlok5923 and @codewithvk  This problem will be resolve on issue #126  and If you download the repo locally, you'll find the logo. In the project's link so many things are not updated, that team will work on. For now, you can check other open issues 🙂.
