### ISSUE TITLE
AnitaB logo does not load on nav bar

### ISSUE THREAD

**Issue by meenakshi-dhanani** [anitab-org/bridge-in-tech-web#13]
**Describe the bug**
The AnitaB logo is not seen

**To Reproduce**
On the home page of the app

**Expected behavior**
Logo should be seen

**Screenshots**

<img width="917" alt="Screen Shot 2020-06-04 at 3 31 45 PM" src="https://user-images.githubusercontent.com/14279061/83743671-ab648780-a678-11ea-86a7-ff167aac1c42.png">

**Comment by foongminwong** [comment]
Not sure this will help 
https://stackoverflow.com/questions/34582405/react-wont-load-local-images?answertab=active#tab-top

**Comment by mtreacy002** [comment]
> Not sure this will help
> https://stackoverflow.com/questions/34582405/react-wont-load-local-images?answertab=active#tab-top

Thanks, @foongminwong. Will give it a look ....

**Comment by mtreacy002** [comment]
Yeah.... that link is if we are going to use webpack bundler as I mentioned [here](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech/topic/React/near/199741769). But according to @meenakshi-dhanani 's  [response](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech/topic/React/near/199745845), we are not using Webpack now so we can't really apply the solution given in the link you gave. But thanks for the support, anyway 😉

**Comment by 19-pragya** [comment]
can i work on this??

**Comment by meenakshi-dhanani** [comment]
Hey @19-pragya, you have already been assigned a first timer issue. Would prefer if you'd want to sign up for other open issues and leave this issue for another first timer.

**Comment by 19-pragya** [comment]
i left the issue for first timers.. can i get assigned now??

**Comment by meenakshi-dhanani** [comment]
> i left the issue for first timers.. can i get assigned now??

@19-pragya you have already raised the PR. And the issue already has an approval, I'd prefer you assign yourself back to it. I shall reassign you to it

**Comment by 19-pragya** [comment]
Ok

**Comment by 19-pragya** [comment]
Please assign me back

**Comment by 19-pragya** [comment]
@meenakshi-dhanani please assign me back.

**Comment by meenakshi-dhanani** [comment]
> Please assign me back

you have been assigned to this issue - https://github.com/anitab-org/bridge-in-tech-web/issues/68

**Comment by khushishikhu** [comment]
may i try to work on this issue?

**Comment by meenakshi-dhanani** [comment]
Sure @khushishikhu I am assigning it to you

**Comment by khushishikhu** [comment]
is this frontend  bug only?

**Comment by mtreacy002** [comment]
Yes, @khushishikhu, this is a frontend bug only. This has nothing to do with backend as the logo file is kept on frontend 😉
