### ISSUE TITLE
bug: buttons really close to each other and not on same level in responsive view.

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/bridge-in-tech-web#131]
**Describe the bug**
The buttons are really close to each other and not on the same level in the smartphone/responsive view 
The bug exists in the login and register form.
See Screenshot for reference

![image](https://user-images.githubusercontent.com/66299533/101275503-319a8b80-37cc-11eb-87c8-287213e64163.png)

**To Reproduce**
1. Go to the login/Register page
2. Scroll down to login/sign up button
3. See error.

**Expected behavior**
The buttons should have some space between them and should be on the same level

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox Web Browser
 - Version --

**Additional context**

**Comment by mtreacy002** [comment]
Thank you, @Aaishpra . Good pick up....

**Comment by nlok5923** [comment]
@Aaishpra i would like to work on it as i am first timer in this repo.

**Comment by Aaishpra** [comment]
> @Aaishpra i would like to work on it as i am first timer in this repo.

@mtreacy002 can you assign this to him?

**Comment by mtreacy002** [comment]
Sure, @nlok5923. I’ll assign you to this issue. Thanks for picking it up 😀
