### ISSUE TITLE
Bug: Submenus under My Space > Profile dissappear from Navbar

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#134]
**Describe the bug**
The submenus under My Space > Profile (Personal Detals, Additional Info, and Personal Background) have dissappeared from the Navbar. One of the recent merged to develop branch is suspected to have caused this.

**To Reproduce**
1. Run the 3 servers (BIT and MS backends as well as BIT frontend)
2. Login and try to update personal details (by going to My Space > Profile > Personal Details on the Navbar)
3. See error (when you click on Profile, dropdown options are not showing)

**Expected behavior**
When you click on Profile, the 3 dropdown options should've been given under the Profile tab instead)

**Screenshots**
with Bug (no options given when Profile is clicked)
<img width="1668" alt="Screen Shot 2020-12-13 at 10 39 54 pm" src="https://user-images.githubusercontent.com/29667122/102010756-3fd04500-3d94-11eb-8308-a665038ac99c.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 10.15.7
 - Browser: Chrome
 - Version ??

**Additional context**
The submenus options still exists as options under Navigation.js and Route.js. They are just not being displayed when the `Profile` tab is clicked.

**Comment by chinmaym07** [comment]
Hey can I try this .?

**Comment by mtreacy002** [comment]
Sure, @chinmaym07 . I'll assign you to this. Thanks for picking this up.

**Comment by chinmaym07** [comment]
Hey @mtreacy002  I am trying to register on it after running the 3 servers .It is showing this error .

CRITICAL:root:HTTPConnectionPool(host='127.0.0.1', port=4000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7314a83250>: Failed to establish a new connection: [Errno 111] Connection refused'))
CRITICAL:root:{'message': 'An unexpected server error occurs while processing your request. Please try again later.'}
Please help.

**Comment by emmanuelhashy** [comment]
Hi, @mtreacy002 I'd like to work on this.

**Comment by mtreacy002** [comment]
Hi @emmanuelhashy, let's check with @chinmaym07 first. @chinmaym07 , were you able to solve the issue you posted here? It could also be because of the missing dependency raised by one of the contributor [here](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech/topic/Questions/near/221422579). You could check if the update to ms-backend-server branch solve the issue (reinstall dependencies to your virtual env first).

**Comment by chinmaym07** [comment]
Yes @mtreacy002 I am working on it.will submit a PR asap. 
No that error is not because of missing dependency (flask-cors).

**Comment by chinmaym07** [comment]
Hey @mtreacy002  is dropdown now opening correctly..? Please check.

![Peek 2021-01-12 19-21](https://user-images.githubusercontent.com/44670961/104322880-76bc8680-550b-11eb-9461-a76e5618ef2e.gif)

If it is working fine can I open a pr for the same. ?

**Comment by mtreacy002** [comment]
Hi @chinmaym07,  your screenshot shown the expected behaviour on the dropdown menu. You can send a pr so I can test/check it out. Thanks.
