### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by bhu1tyagi** [anitab-org/bridge-in-tech-web#135]
Login and register page UI improvement.

**Comment by bhu1tyagi** [comment]
Please assign this to me, I would like to work on this issue.

**Comment by mtreacy002** [comment]
@bhu1tyagi . Thank you for showing interest to BridgeInTech project.
I'd like to share some advice:
When you contributing to an open source project, you must wait till someone approve the issue and assign you to it before you can start working. This is mentioned in `Getting Started` guidelines > `[Choosing a working item](https://github.com/anitab-org/bridge-in-tech-web/wiki/Getting-Started#choose-a-working-item)`. 
The issue you open here also need to follow the template provided by the organization. When you click on `New Issue`, you'll notice there are 4 templates you need to choose from and the needed infomation you need to provide for others to understand what you're trying to raise in that issue. 
<img width="724" alt="Screen Shot 2021-01-06 at 2 40 45 pm" src="https://user-images.githubusercontent.com/29667122/103726611-7749ae80-502d-11eb-9b4e-981170240dfb.png">

Can you please adjust the title and description for this issue to match one of the template above?

**Comment by mtreacy002** [comment]
This issue is now closed due to the BIT redesign process workflow which requires any design proposal to be approved by the design team before it can be implemented.
