### ISSUE TITLE
Login a user

### ISSUE THREAD

**Issue by foongminwong** [anitab-org/bridge-in-tech-web#14]
## Description
As a user,
I want to login on BIT,
So that I can login as mentor/mentee to see programs I like

## Out of Scope
- [ ] Persisting the auth JWT token on the client side and using it in every request to backend
- [ ] Being able to login via email
- [ ] On successful login, when user directed to Member Portfolio page, the Login link should be replaced with Logout option & Register should not show for logged in user

## Mocks
See the latest mock under https://github.com/anitab-org/bridge-in-tech-web/issues/3

## Linked Issue
[Create Login API](https://github.com/anitab-org/bridge-in-tech-backend/issues/47)

### Update [Required]
- [ ] Given a user is on the Home Page, When the user clicks on Register, Then she/he should see the username and password to login
- [ ] Given a user enters username and password, When the user clicks on login, Then he/she will be redirected to the Member Portfolio Page
- [ ] Test to check if a call to the login backend api is made with expected payload(username and password)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
1 - 2 days

**Comment by mtreacy002** [comment]
Update: @anitab-org/bridgeintech-maintainers . I'll have to cut down and change few details of this login form. 
It will no longer need `Login as:` `Organization` or `Mentor/Mentee` radio buttons following the development/what we have now in the Register form.

I also will not attempt the `forgot password` link for now. This can be revisited later after we've got MVP done (so, this can be part of `Nice to have` or maybe `Future Feature` requirement. Note: I think this is also still WIP for Mentorship Android atm.
