### ISSUE TITLE
Bug: Eslint warnings on the homepage 

### ISSUE THREAD

**Issue by jalajcodes** [anitab-org/bridge-in-tech-web#140]
## Description
After running the app, there are a lot of eslint warnings from the rule `react-hooks/exhaustive-deps`. They are just warnings but can lead to bugs later as mentioned [here](https://github.com/facebook/create-react-app/issues/6880#issuecomment-485912528) by Dan Abramov. 

There are also some typo warnings like using `eventKey` instead of `eventkey` etc

## To Reproduce
**Steps to reproduce the behavior:**
1. Start the react app
2. While on homepage, open developer tools console
3. See the errors

## Screenshots
![image](https://user-images.githubusercontent.com/17108695/104120576-dc6b1000-535d-11eb-82f6-c86e78531757.png)

## Expected behavior
No errors and warnings should popup in the console.

### Update [Required]
- [ ] update useEffect's depedency array of the respective files.
- [ ] fix the typos cusing the warning.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1-2] hours

**Comment by jalajcodes** [comment]
Oh and I'd like to work on it.

**Comment by mtreacy002** [comment]
@jalajcodes , thanks for bringing this up. Can you please roughly explain how you're going to fix this bug?

**Comment by jalajcodes** [comment]
@mtreacy002 Sure, 

* The warnings are self explanatory as to what should be done, let's take this warning for example,
```sh
./src/members/Members.jsx
  Line 36:6:  React Hook useEffect has a missing dependency: 'requestMembersList'. Either include it or remove the 
  dependency array  react-hooks/exhaustive-deps
```

Here's the code causing this warning, if you look closely on line 36 you'll see squiggly line on the empty array, 
![image](https://user-images.githubusercontent.com/17108695/104278391-8a95c780-54ce-11eb-9367-7454c9c8fa4d.png)

to fix it, in this case I can just add `requestMembersList` object to the dependency array.
![image](https://user-images.githubusercontent.com/17108695/104278836-3d662580-54cf-11eb-9fcc-81ebc177a1fa.png)

* Above example was simple, but that solution won't work if useEffect depends on a function, in that case there are two options, either move the function inside useEffect or memoize it with `useCallback` hook and then put the memoized function in the array.

**Comment by mtreacy002** [comment]
Sounds good to me @jalajcodes. I look forward to your code change for the fix. I'll assign you to this then. Thanks for the explanation. I've learned something from you 😉.
