### ISSUE TITLE
Improve navbar UI

### ISSUE THREAD

**Issue by shruti1421** [anitab-org/bridge-in-tech-web#141]
**Describe the bug**
- navbar menu is not styled properly and the drop down menu is not matching with the current navbar style

**To Reproduce**
1. Go to '..login page.'
2. Click on '....drop down menu bar'

**Expected behavior**
To improve the styling of the navbar elements and to align all elements of navbar in uniform order with proper padding.

**Screenshots**

![image](https://user-images.githubusercontent.com/64346825/104375827-fff2ae00-5549-11eb-8bd7-e50e654ca4b2.png)

**Desktop (please complete the following information):**
 - Ubuntu
 - Firefox
 - Version 20.0

**Smartphone (please complete the following information):**
 - Device: Realme 7
 - OS: Android
 - Browser Chrome
 - Version 

**Additional context**
I can fix this issue please assign this to me.

**Comment by Aaishpra** [comment]
Hi @shruti1421 thanks for showing your interest in the project and opening this issue, but I believe BIT is going to follow a design matrix as @mtreacy002 mentioned [here](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech/topic/Design.2FMocks/near/221473666) and any change in the UI needs to be first approved by the design team, so you can go on zulip and discuss any change with the design team and @mtreacy002 first and then work on it.

cc @mtreacy002

**Comment by battuAshita** [comment]
Hi @shruti1421. Is this issue open for contribution?

**Comment by mtreacy002** [comment]
@shruti1421 and @battuAshita , thanks for your interest in the project. For this issue, as per @Aaishpra stated above, we need to make sure any design changes is approved by the design team. Feel free to join there so we can have a design focus discussion 😉

**Comment by mtreacy002** [comment]
@shruti1421 , I'm closing this issue as the Navbar design issue is now opened for the approved design (issue #208).
