### ISSUE TITLE
Dev: Add editorconfig file to the project.

### ISSUE THREAD

**Issue by nlok5923** [anitab-org/bridge-in-tech-web#143]
## Description
it would be good having editorconfig file in project to maintain the formatting style of whole project. 

## Acceptance Criteria
 file with accepted formatting style.

## Estimation
1 hour

**Comment by jalajcodes** [comment]
+1

I was thinking about it too...
We can go one step ahead and use the same file in all org. Projects. What do you say? @mtreacy002

**Comment by nlok5923** [comment]
Wanna work on it if the issue is legit.

**Comment by mtreacy002** [comment]
This sounds like a good idea. But we’re yet to finalise the design matrix for BIT. Wouldn’t this be best to be done after we’ve done that (the matrix)? This way we can enforce the matrix throughout the project. What do you think @jalajcodes and @nlok5923 ?

**Comment by nlok5923** [comment]
Yes, @mtreacy002 that would be good.

**Comment by jalajcodes** [comment]
> This sounds like a good idea. But we’re yet to finalise the design matrix for BIT. Wouldn’t this be best to be done after we’ve done that (the matrix)? This way we can enforce the matrix throughout the project. What do you think @jalajcodes and @nlok5923 ?

Yeah, that would be better.

**Comment by mtreacy002** [comment]
@nlok5923 and @jalajcodes , just want to let you know that BIT lead designer, Vuyanzi, has created the [BIT Design Metrics Guidelines doc](https://www.figma.com/file/V22SXBLzMd9bqnita6hfMp/Bridge_in_tech?node-id=0%3A1). Would this be sufficient to make the initial editorconfig file? The file can be modified later when new metrics are added. @nlok5923 , if the doc is suitable, let me know if you want to work on it so I can assign you.

**Comment by nlok5923** [comment]
@mtreacy002  Sure i would like to work on it.
