### ISSUE TITLE
Fix: Alignment of fields in Register page

### ISSUE THREAD

**Issue by harsha-sam** [anitab-org/bridge-in-tech-web#147]
## Description
As a public user,
I need to see a well-aligned `Register` page with proper styling,
so that I can register.

## Mocks
![image](https://user-images.githubusercontent.com/56500849/104916354-f1781c80-59b7-11eb-9aea-3d6fced56b8e.png)
As you can see above, all fields of the current registration page are not aligned exactly. Some of the fields have more left padding whereas some fields don't and checkboxes don't tick even when corresponding labels are clicked.

### Update [Required]
- [ ] Fix register component styling so that all fields are exactly aligned like shown  below

![image](https://user-images.githubusercontent.com/56500849/104917169-115c1000-59b9-11eb-9f97-56fbeb2b537f.png)

- [ ] Fix register.jsx file so that checkboxes work even if clicked on its labels.
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day.

**Comment by harsha-sam** [comment]
I would like to work on this

**Comment by Ayush23Dash** [comment]
I think the redesigning of the complete website is scheduled. So I believe, this issue won't be of much relevance.
