### ISSUE TITLE
Optimize Images

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-web#148]
**Describe the bug**
A picture speaks thousand words, but if the picture is of large size, it takes forever to load.
Large images slow down the web pages which creates a less than optimal user experience.
We can reduce your image’s file sizes to help improve your website’s performance.

**To Reproduce**
1. Go to https://bridge-in-tech-web-heroku.herokuapp.com/benefit
2. Right Click -> Inspect Element -> Go to Network Tab
3. Check out the file sizes and loading time

**Expected behavior**
We can reduce the image sizes without compromising the image quality.

**Screenshots**
Here's an example
![img2-data](https://user-images.githubusercontent.com/54268438/105045117-88fb6f00-5a8d-11eb-88fc-1d9fb19e6583.JPG)

The following image is of size 3.1 MB which is very large and takes very long to load in a poor internet connection and needs to be optimized.
![img1-data](https://user-images.githubusercontent.com/54268438/105045229-b0ead280-5a8d-11eb-8d08-ad8b567a6986.JPG)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser : Chrome
- Version : 87.0.4280.141 (Official Build) (64-bit)

**Additional context**
I tried optimizing a image from the website and the size reduced significantly with no reduction in quality.

Before Optimization : Size -> 1.2 MB
<img width="465" alt="benefit1" src="https://user-images.githubusercontent.com/54268438/105045038-6ff2be00-5a8d-11eb-8790-cf07b77a3bdf.png">

After Optimization : Size -> 234.9 KB
![benefit1 (1)](https://user-images.githubusercontent.com/54268438/105045050-741edb80-5a8d-11eb-9182-210e8b953270.png)

![after-compression](https://user-images.githubusercontent.com/54268438/105045091-813bca80-5a8d-11eb-90c4-30db04d5b447.JPG)

I want to work on this issue and will create a pull request asap.
Please assign it to me.

**Comment by Aaishpra** [comment]
Hi @Rahulm2310 thanks for showing your interest in the project and opening this issue, but I believe BIT is going to follow a design matrix as @mtreacy002 mentioned [here](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech/topic/Design.2FMocks/near/221473666) So, benifit page, about page all are going to get redesigned. That means the page you are currently seeing are temporary so i believe we don't need to have optimized images for something which is temporary.

Cc @mtreacy002

**Comment by Rahulm2310** [comment]
@Aaishpra Alright. Thanks for looking into it. 😊

**Comment by mtreacy002** [comment]
Yep, as per @Aaishpra said above. @Rahulm2310 atm any issus related to design improvements should be put on hold as we need to decide with design matrix first. So can you please close this issue?

**Comment by Rahulm2310** [comment]
Sure @mtreacy002 🙂
