### ISSUE TITLE
Doc: Setup instructions link on Readme file needs to be updated

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#149]
**Describe the bug**
The previous **BIT Backend Environment Setup** linked to a wiki page that is not longer exist since now we're using the ENV_SETUP_INSTRUCTION.md under .github folder. Therefore the link inside the Readme file need to be updated to reflect this change.

**To Reproduce**
1. Go to bridge-in-tech-web repository and click on the link to **here** under option 1.1
<img width="688" alt="Screen Shot 2021-01-23 at 1 39 09 pm" src="https://user-images.githubusercontent.com/29667122/105566484-9b70f380-5d80-11eb-8444-5725f4575955.png">

2. See an empty wiki page (not the expected behaviour)
<img width="1048" alt="Screen Shot 2021-01-22 at 11 04 06 am" src="https://user-images.githubusercontent.com/29667122/105428790-4364bf00-5ca4-11eb-9d2b-84b4f67d9e80.png">

3. Now Go to the Wiki page and click on the link to the same page from the side bar

<img width="246" alt="Screen Shot 2021-01-22 at 11 04 33 am" src="https://user-images.githubusercontent.com/29667122/105428483-98540580-5ca3-11eb-88cf-b4b85cb0c5b0.png">

<img width="1038" alt="Screen Shot 2021-01-22 at 11 05 20 am" src="https://user-images.githubusercontent.com/29667122/105428590-c3d6f000-5ca3-11eb-98ac-01688bd221fd.png">

**Expected behavior**
The link on the Readme of repository need to lead to the same page as the wiki side bar does

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - Version: Catalina 10.15.7, Safari 14.0.2

**Comment by 0xNilesh** [comment]
@mtreacy002 I would like to do this. Please assign me.

**Comment by mtreacy002** [comment]
Hi @VectoTec , thanks for showing your interest on the project. As per the [guideline](https://github.com/anitab-org/bridge-in-tech-web/wiki/Getting-Started#choose-a-working-item), you should wait until either a maintainer/OS Ambassador assign you to the issue.
This is to prevent conflict with other contributor that also interested with the issue.

**Comment by 0xNilesh** [comment]
Ok, sorry for the same 😅. I'll keep in mind next time.

**Comment by mtreacy002** [comment]
Thank you for your understanding. For now, I'll assign you to this.

**Comment by 0xNilesh** [comment]
Ok thanks for assigning. So, do I close the previous PR and open it again or is it fine ?

**Comment by mtreacy002** [comment]
No, the same PR should be fine. No need to open another PR.

**Comment by 0xNilesh** [comment]
ok thanks.
