### ISSUE TITLE
Bug: No Option to Logout 

### ISSUE THREAD

**Issue by chinmaym07** [anitab-org/bridge-in-tech-web#153]
**Describe the bug**

After successful login ,there is no option to logout & also Login button is still there but when I clicked on login again It showed the main landing page.

**Expected behavior**

After successful login ,there should be a button to logout & also Login button should not be there .

**Screenshots**

![Peek 2021-01-22 15-38](https://user-images.githubusercontent.com/44670961/105477488-eb3fb400-5cc7-11eb-9ec3-0736242e347c.gif)

I would like to work on this issue .

**Comment by Rahulm2310** [comment]
@chinmaym07 Yes, also currently even after log in, user is allowed to go to register route which should not be.

**Comment by chinmaym07** [comment]
> @chinmaym07 Yes, also currently even after log in, user is allowed to go to register route which should not be.

Correct ..I forgot to mention that..👍🏻

**Comment by chinmaym07** [comment]
There is an option to logout ..I figured it out right now..that's why closing this issue.!!

**Comment by 0xNilesh** [comment]
@chinmaym07 Can you tell me how to logout ?

**Comment by mtreacy002** [comment]
@chinmaym07 , this is actually a valid issue. Somewhere in the commits that got merged, it breaks the app that the `Logout` button no longer shown after user is logged in (the Register and Login buttons remain visible) which is not the expected behaviour. So, will reopen the issue now.

**Comment by mtreacy002** [comment]
@chinmaym07 . Would you like to work on it?

**Comment by mtreacy002** [comment]
> @chinmaym07 Can you tell me how to logout ?

@VectoTec , as this is a bug, what you can do to get around it temporarily is to shut down all 3 servers, clear your browsing history and restart everything again (at least that's what I do for now). @chinmaym07 , you also mentioned above that you find a way to logout, can you share your method (if it's different).

**Comment by chinmaym07** [comment]
> > @chinmaym07 Can you tell me how to logout ?
> 
> @VectoTec , as this is a bug, what you can do to get around it temporarily is to shut down all 3 servers, clear your browsing history and restart everything again (at least that's what I do for now). @chinmaym07 , you also mentioned above that you find a way to logout, can you share your method (if it's different).

Yes @mtreacy002 I found the same way that is to shut down all the 3 server and start again ..then login ..then you will be able to see logout option...☺️

Yes I would like to work on it ...I'll try to think of a solution & will inform you about it before implementing.☺️👍🏻

**Comment by 0xNilesh** [comment]
@chinmaym07 @mtreacy002 I found the solution to fix the issue, if you aren't able to do this, then let me know. I had fixed and tried locally, it's working fine. 😄

**Comment by chinmaym07** [comment]
@mtreacy002 please assign this issue to @VectoTec.. !!

**Comment by mtreacy002** [comment]
Ok, will assign him now 😉

**Comment by jalajcodes** [comment]
> > @chinmaym07 Can you tell me how to logout ?
> 
> @VectoTec , as this is a bug, what you can do to get around it temporarily is to shut down all 3 servers, clear your browsing history and restart everything again (at least that's what I do for now). @chinmaym07 , you also mentioned above that you find a way to logout, can you share your method (if it's different).

I logout by deleting the cookies for localhost:3000 from the application tab of devtools and then refreshing the page😁

**Comment by 0xNilesh** [comment]
@jalajcodes yeah that's an option and btw I've solved the issue and will make a PR soon 😁.
