### ISSUE TITLE
Bug: Multiple requests being sent to the server due to the change in useEffect's dependency array.

### ISSUE THREAD

**Issue by jalajcodes** [anitab-org/bridge-in-tech-web#158]
**Describe the bug**
Due to some changes made in [this PR](https://github.com/anitab-org/bridge-in-tech-web/pull/150) lots of requests are sent to the backend in a short amount of time.

**To Reproduce**
Steps to reproduce the behaviour:

1. Login with your account
2. Open Developer Console
4. Switch to the Network tab
4. Now, click on any link from the `My Space` dropdown present in the navbar.
3. See the requests increasing repeatedly on the bottom left side.

**Expected behaviour**
The number of requests should be equal to the number of fetch requests made by the page.

**Screenshots**
See multiple requests on the bottom left corner of the network tab.
![](https://user-images.githubusercontent.com/29667122/105616652-b9942d80-5e2c-11eb-8b75-d92afd73f7d0.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave
 - Version 1.18.75 Chromium: 87.0.4280.101 (Official Build) (64-bit)

**Comment by mtreacy002** [comment]
Thanks for opening this issue, @jalajcodes, 👍

**Comment by Rahulm2310** [comment]
@jalajcodes Can you please provide clear steps to reproduce this issue.

**Comment by jalajcodes** [comment]
> @jalajcodes Can you please provide clear steps to reproduce this issue.

@Rahulm2310 
I've updated the steps... Check if you can reproduce the issue now.
