### ISSUE TITLE
Remove .vscode

### ISSUE THREAD

**Issue by meenakshi-dhanani** [anitab-org/bridge-in-tech-web#16]
## Description
.vscode should not be committed

## Acceptance Criteria
- [ ] Delete .vscode
- [ ] Add .vscode to .gitignore so that it is not added in the future

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

**Comment by mahakbansal2019** [comment]
hey @meenakshi-dhanani!
I would like to work on this.
Can I take this up?
Thanks :)

**Comment by meenakshi-dhanani** [comment]
Let me know if you need any help :) Assigned the issue to you @mahakbansal2019
