### ISSUE TITLE
Bug: Display email issue

### ISSUE THREAD

**Issue by chinmaym07** [anitab-org/bridge-in-tech-web#166]
**Describe the bug**

When a user logs in using username it display message "Welcome ${username}" and when the same user logs in using email it displays "Welcome ${email}" 

**Expected behavior**

Either the user logs in using email or username ,It should show user's username.

**Screenshots**

![Peek 2021-02-01 02-23](https://user-images.githubusercontent.com/44670961/106397679-953fde80-6434-11eb-88be-e24cb30caecb.gif)
**Desktop (please complete the following information):**
 - OS: any
 - Browser  any
 - Version  any

**Smartphone (please complete the following information):**
 - Device: any
 - OS:  any
 - Browser  any
 - Version  any

**Comment by aakarshvats638** [comment]
Can I work on this issue @chinmaym07

**Comment by chinmaym07** [comment]
Please wait for it to be approved by maintainers .If it's a valid issue after that you can ask the maintainer to assign it to you. !!. @aakarshvats638

**Comment by mtreacy002** [comment]
Yep, @chinmaym07 . It’s a valid issue. Can we open this for first-time contributors do you think?

**Comment by chinmaym07** [comment]
Yes sure @mtreacy002 🙂👍🏻

**Comment by mtreacy002** [comment]
@aakarshvats638 , if you’ve never contributed to this repo before, I can assign you to this. Are you still interested?

**Comment by sharur7** [comment]
@mtreacy002 can I work on this issue?

**Comment by mtreacy002** [comment]
Let's see if @aakarshvats638 still interested to work on this or not first, @sharur7. But thanks for showing interest.

**Comment by Srashtimittal** [comment]
@mtreacy002 Can I work on this issue?

**Comment by aakarshvats638** [comment]
@mtreacy002  mam I haven't worked on this repo

**Comment by mtreacy002** [comment]
Ok then @aakarshvats638 , I'll assign you to this issue 😉

**Comment by shades-7** [comment]
@mtreacy002 if this issue is still open, can I give it a shot?

**Comment by subodhk01** [comment]
@mtreacy002 Can I work on this issue?

**Comment by chinmaym07** [comment]
@aakarshvats638 can you please share the progress that you made on this issue .?

**Comment by aakarshvats638** [comment]
I am actually facing trouble setting up the environment, @chinmaym07

**Comment by Rahulm2310** [comment]
@aakarshvats638 Feel free to ask your queries on [Zulip](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech). The community is ready to help you. Take it easy🙂

**Comment by mtreacy002** [comment]
@aakarshvats638 , can we please get an update on this issue? Were you able to solve the issue with your local setup? I didn't see your posting on Zulip requesting for help.

**Comment by aakarshvats638** [comment]
Mam, I haven't done much due to my ongoing exams.

**Comment by mtreacy002** [comment]
That's ok @aakarshvats638, we only need to hear an update every 3-4 days, even if you need more time due to your exam. You can take your time and work on it again when your exam is finish. Please do let us know when you will be available again 😉.

**Comment by aakarshvats638** [comment]
OKAY, THANK YOU MAM

**Comment by mtreacy002** [comment]
@aakarshvats638, have you finiished with the exam? Can you please let us know when you  would likely be available again to continue working on this issue? Thanks

**Comment by aakarshvats638** [comment]
Mam I'll continue working on this from tomorrow, as tomorrow is my last exam

**Comment by mtreacy002** [comment]
Thanks for letting me know, @aakarshvats638 . Look forward to your work on this 😉

**Comment by mtreacy002** [comment]
@aakarshvats638 , can we please get an update on this?

**Comment by Rahulm2310** [comment]
Unassigning @aakarshvats638 due to inactivity for more than a month. This will be available for OSH aspirants from 1st April.

**Comment by Aryamanz29** [comment]
I would like to work on this issue @Rahulm2310 @chinmaym07

**Comment by Rahulm2310** [comment]
@Aryamanz29 Sure, Go ahead with the fix 🙂

**Comment by devkapilbansal** [comment]
@Aryamanz29 just to make sure, did you complete required setup first?

**Comment by Aryamanz29** [comment]
> @Aryamanz29 just to make sure, did you complete required setup first?

Yup, I'll setup this repo  tomorrow first before proceeding to this issue.

**Comment by Rahulm2310** [comment]
@Aryamanz29 Yes please complete #218 before starting to work on this 🙂

**Comment by Aryamanz29** [comment]
> @Aryamanz29 Yes please complete #218 before starting to work on this 🙂

I have raised PR for env setup, Kindly look into it #234 
Should I start working on this issue now? @Rahulm2310 @devkapilbansal

**Comment by Rahulm2310** [comment]
@Aryamanz29 the PR looks fine. You can now work on this ☺️
