### ISSUE TITLE
Bug: Repeating background on home page

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-web#167]
**Describe the bug**
The background on home page is repeating on some screen sizes.

**To Reproduce**
1. Go to Developer Tools
2. Click on 'Toggle device toolbar'
3. Keep decreasing the screen width till the background repeats

**Expected behavior**
The background should not repeat on any screen size.

**Screenshots**
![image](https://user-images.githubusercontent.com/54268438/106512027-1495e680-64f7-11eb-8356-a3bf8a0241e2.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome
 - Version: 84

**Comment by Rahulm2310** [comment]
@vj-codes I think this should be labelled `First Timers only`

**Comment by arkumari2000** [comment]
I would like to work on it. Can I try this?

**Comment by Rahulm2310** [comment]
@arkumari2000 Yes you definitely can but just wait for a maintainer to confirm and assign this issue to you. Thanks 😊

**Comment by mtreacy002** [comment]
Agree with @Rahulm2310 , I’ll label it first-timer only. @arkumari2000 , if you’ve never contributed before to this repo, I can assign this to you if you’re interested 😉

**Comment by arkumari2000** [comment]
@mtreacy002  yes I want to give it a try. please assign it to me.

**Comment by shruti1421** [comment]
If no one is working on this, can I try?

**Comment by Rahulm2310** [comment]
As @arkumari2000 was the first one to claim it, I think she should get the chance first. If she's no more interested than surely you can @shruti1421 but please wait for @mtreacy002 to assign any one of you before start working on it. 🙂

**Comment by shades-7** [comment]
is this issue still open, if yes, can I work on it? I am just a newbie over here.

**Comment by Rahulm2310** [comment]
@shades-7 Thanks for showing interest but @arkumari2000 has already made a PR for this. Feel free to look through some other first timer issues. 🙂
