### ISSUE TITLE
Home Page Text center align in responsive view

### ISSUE THREAD

**Issue by wajeehamushtaq** [anitab-org/bridge-in-tech-web#172]
When the Home page view on mobile the text does not properly view. It should not align center.

![issue1](https://user-images.githubusercontent.com/55188521/107525872-16d40100-6bd9-11eb-8ee2-4e03a5fdcf78.JPG)

**Comment by Rahulm2310** [comment]
@wajeehamushtaq As we are redesigning the whole website, this will be covered too. So, don't worry about this. Thanks 🙂

**Comment by Rahulm2310** [comment]
@mtreacy002 I think this should be closed.

**Comment by mtreacy002** [comment]
@wajeehamushtaq , thank you for bringing this up. Unfortunately, I agree with @Rahulm2310 . Since we're redesigning the homepage, this issue might not be relevant on the new Homepage. Will close this issue now.
