### ISSUE TITLE
Dev: Feature of Deploy from Github Actions

### ISSUE THREAD

**Issue by aditmehta9** [anitab-org/bridge-in-tech-web#173]
**Is your feature request related to a problem? Please describe.**
Creation of deploy.yml file from Github Actions

**Describe the solution you'd like**
Creation of deploy.yml file in .github/workflow category

**Additional context**
![image](https://user-images.githubusercontent.com/35133994/107322791-26fdba80-6acb-11eb-8b23-8f0c89c9ec23.png)

**Comment by aditmehta9** [comment]
@mtreacy002 can this issue can be assigned to me as I haven't contributed to this repo and it is also the task of OS Ambassador more work needed section?

**Comment by mtreacy002** [comment]
Sure, @aditmehta9 , I'll assign you to this. 😉

**Comment by aditmehta9** [comment]
> 
> 
> Sure, @aditmehta9 , I'll assign you to this. 😉

Thank you so much.

**Comment by mtreacy002** [comment]
This issue is now closed as it is not possible to deploy bit web (non-static pages) to gh-pages (only for static pages) (see the post [here](https://github.com/anitab-org/bridge-in-tech-web/pull/170#issuecomment-787445887)).

**Comment by aditmehta9** [comment]
> This issue is now closed as it is not possible to deploy bit web (non-static pages) to gh-pages (only for static pages) (see the post [here](https://github.com/anitab-org/bridge-in-tech-web/pull/170#issuecomment-787445887)).

Sure

**Comment by mtreacy002** [comment]
Reopening the issue as the feature is actually possible with slight adjustment on Backend for CORS origin (allowing gh-page url). @aditmehta9 , reassigning you on this. cc @annabauza and @isabelcosta

**Comment by aditmehta9** [comment]
> Reopening the issue as the feature is actually possible with slight adjustment on Backend for CORS origin (allowing gh-page url). @aditmehta9 , reassigning you on this. cc @annabauza and @isabelcosta

So, when will be the changes in the backend will be implemented? So, I can try again.

**Comment by mtreacy002** [comment]
> > Reopening the issue as the feature is actually possible with slight adjustment on Backend for CORS origin (allowing gh-page url). @aditmehta9 , reassigning you on this. cc @annabauza and @isabelcosta
> 
> So, when will be the changes in the backend will be implemented? So, I can try again.

@aditmehta9 , your work here will not depend on the backend adjustment. Instead, backend changes to CORS can only happen after you successfully deploy the frontend to gh-pages through this PR since only then we can get the gh-page URL to be placed on BIT backend as CORS source. 
I only stated the need for the backend CORS modification to emphasise the reason we can re-open the issue which is, gh-pages can work as BIT web as it can connect to the Backend using different URL (the newly deploy gh-page)
So, please do make the necessary change here 😉.

**Comment by aditmehta9** [comment]
Fixed the error here it is deployed: https://aditmehta9.github.io/bridge-in-tech-web/
