### ISSUE TITLE
Create a under construction screen. 

### ISSUE THREAD

**Issue by pranay-simejia** [anitab-org/bridge-in-tech-web#175]
As the  [website](https://bridge-in-tech-web-heroku.herokuapp.com/) is under construction, there can be a nice under construction screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/70064696/107797441-f8a90500-6d80-11eb-955e-1c35440134fb.png)

**Comment by Rahulm2310** [comment]
@pranay-simejia BIT is not at production level & still under development. I think we should focus more on constructing/designing the website than designing a under construction page.  Thanks 🙂 

Cc : @mtreacy002

**Comment by Aaishpra** [comment]
@pranay-simejia the screenshot you presented is on the Heroku server of BIT(which ain't updated with the local project at the moment) please locally set up the project, we pretty much have most of the pages created(not under construction).
Therfore Please close this issue.

**Comment by pranay-simejia** [comment]
got it! @Rahulm2310 
sure! @Aaishpra
