### ISSUE TITLE
Bug: Add links to Code of Conduct, Terms & Privacy Policy in the Register UI

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-web#176]
**Describe the bug**
User can't go through the AnitaB.org's Code of Conduct, Terms & Privacy Policy during registering. 

**To Reproduce**
1. Go to http://localhost:3000/register
2. See error

**Expected behavior**
Add links to AnitaB.org's Code of Conduct, Terms & Privacy Policy in the Register UI or add a Modal to display  Code of Conduct, Terms & Privacy Policy.

**Screenshots**
![image](https://user-images.githubusercontent.com/54268438/108263535-6cd21700-718c-11eb-946c-57a053d5e9ee.png)

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: Any

**Comment by Rahulm2310** [comment]
@mtreacy002 Can you confirm/approve this issue ?

**Comment by mtreacy002** [comment]
@Rahulm2310 , do you have specific links in mind for these Code of Conduct, Terms & Privacy Policy? I kept it blank during GSoC as it needs careful discussion on what to put as the contents and whether we need BIT own customised policies or adopt them from existing AnitaB policies.
But I agree, at some point we need to add contents to the policies. I'll put this as an Outreach/Research issue so we can start the discussion. What do you think?

**Comment by Rahulm2310** [comment]
@mtreacy002  Yes, I agree. It is a sensitive topic. Let's have inputs from @admins as well as the community.

**Comment by shades-7** [comment]
can I take up this issue ?

**Comment by mtreacy002** [comment]
@shades-7 , let's see if @Rahulm2310 wants to work on it. The contributor who opens the issue normally gets the first priority to be assigned. @Rahulm2310 , I think this issue is valid, do you want to work on it? If you are not currently working on an issue in this BIT web repo, I'll assign you to this.

**Comment by Rahulm2310** [comment]
@mtreacy002 Thanks. I would like to pick it up. 🙂

**Comment by mtreacy002** [comment]
Great. I'll assign you then.
