### ISSUE TITLE
Bug: text underline on the Login & Sign Up (blue) buttons

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-web#177]
**Describe the bug**
There is a text underline on the Login & Sign Up (blue) buttons. 

**To Reproduce**
1. Go to http://localhost:3000/login
2. See error

**Expected behavior**
Remove text underline from the login & sign up (blue) buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/54268438/108396756-34d6dc80-723d-11eb-81de-38af5ed10ad2.png)

![image](https://user-images.githubusercontent.com/54268438/108396789-41f3cb80-723d-11eb-9cf4-a5cce5b34ac6.png)

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: Any

**Additional context**
I think setting `text-decoration: none` would work.

**Comment by Rahulm2310** [comment]
@mtreacy002 Please add `First Timers only` label. Thanks 🙂

**Comment by mtreacy002** [comment]
Thanks, @Rahulm2310 . Done.

**Comment by sachinsom93** [comment]
Can I work on this ?? @mtreacy002

**Comment by Rahulm2310** [comment]
@sachinsom93 Of course Yes! Just wait until you are assigned. 😉

**Comment by sachinsom93** [comment]
> @sachinsom93 Of course Yes! Just wait until you are assigned. 😉

Thanks @Rahulm2310, also I would like to know on which branch all the PRs should me raised ?

**Comment by Rahulm2310** [comment]
@sachinsom93 All PRs are raised to merge with `develop` branch. Please create a separate branch for a PR. Never use `develop`(default) branch to create a PR. For more please have a look into contribution guidelines mentioned in readme.

**Comment by mtreacy002** [comment]
@sachinsom93 , welcome to BridgeInTech and thanks for picking up this issue. I'll assign you to this now 😉

**Comment by haelmj** [comment]
Hi everyone, is there an update on this issue?

**Comment by sachinsom93** [comment]
> Hi everyone, is there an update on this issue?

Hi @haelmj, I am working on this issue.

**Comment by stableapple** [comment]
Can I work on this issue?

**Comment by Rahulm2310** [comment]
@stableapple It is already been assigned to @sachinsom93 . Please look for some other available issues. 🙂

**Comment by Rahulm2310** [comment]
@sachinsom93 Can you please share your progress on this or if facing any problem please ask for help.

**Comment by sachinsom93** [comment]
Hey hi @Rahulm2310, Thanks for asking, I have done the setup of this project locally, but I was committed to some other personal works, that's why I didn't raise PR for this issue, I'll soon raise a PR.
Sorry for inconvenience.

**Comment by Rahulm2310** [comment]
@sachinsom93 no worries. You can raise a PR whenever you get time, but try to give an update in 2-3 days.

**Comment by mtreacy002** [comment]
@sachinsom93 , can you please give us an update on this?

**Comment by sachinsom93** [comment]
@mtreacy002 @Rahulm2310, I am facing a error while starting the react app.
The error looks like this 
![](https://github.com/sachinsom93/temp/blob/master/error.jpg?raw=true)
Could you please help me how to overcome this ?

**Comment by chinmaym07** [comment]
Hey @sachinsom93 !!
Can you please share a screenshot of the error you are facing . It will then be easier to debug .

**Comment by Rahulm2310** [comment]
@sachinsom93 Seems that you missed adding the error screenshot. Also, its better to not clutter up the messages here and discuss it on zulip.

**Comment by sachinsom93** [comment]
I thought i have added the screenshot.

**Comment by chinmaym07** [comment]
Please do check package.json file for any extra spaces or any missing commas. If the error still persists.
Try removing node_modules folder & then again running `npm install` & then check whether this error still persist or not.

**Comment by sachinsom93** [comment]
Thanks @chinmaym07 , error resolved.
