### ISSUE TITLE
Doc: Delete .github/ISSUE_TEMPLATE folder 

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/bridge-in-tech-web#178]
### Description
As a org admin / maintainer,
I need to maintain 1 version of issue templates used in the organization,
so that I can avoid duplicating work and having different versions of the templates, when we want to use the same ones across all projects.

Because the issue templates are now on https://github.com/anitab-org/.github, we don't need to have issue templates present in the repository. Read more about these type of files here https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file

### Acceptance Criteria
**Update [Required]**

- [ ]  Delete .github/ISSUE_TEMPLATE

**Definition of Done**

- [ ]  All of the required items are completed.
- [ ]  Approval by 1 mentor.

**Estimation**
0.5 hours

**Comment by shruti1421** [comment]
I can do this, can you please assign this to me?

**Comment by mtreacy002** [comment]
Sure, @shruti1421 . I'll assign you to this. Thanks for picking this issue up.
