### ISSUE TITLE
Feat: Redirect logo to homepage

### ISSUE THREAD

**Issue by stableapple** [anitab-org/bridge-in-tech-web#180]
**Is your feature request related to a problem? Please describe.**
Currently when a user clicks on the logo on the top left of the web UI, nothing happens.

**Describe the solution you'd like**
Add a link to the logo which redirects the user to homepage when clicked.

**Additional context**
![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/53488062/109408064-08912d80-79ac-11eb-9617-ba833e888791.gif)

**Comment by untari** [comment]
may I work on this ?

**Comment by stableapple** [comment]
Hey @untari, I opened this issue for myself to work on, kindly take up another issue :)

**Comment by untari** [comment]
ah, I see :D

**Comment by 0xNilesh** [comment]
Hi @stableapple , thanks for showing your interest on the project. As per the [guideline,](https://github.com/anitab-org/bridge-in-tech-web/wiki/Getting-Started#choose-a-working-item) you should wait until a maintainer approves the issue and assign you to it. 😄

**Comment by mtreacy002** [comment]
@stableapple , as per @VectoTec point out, next time please do wait for the issue to be approved and you to be assigned before submitting the PR. Thanks.

**Comment by stableapple** [comment]
Extremely sorry for the mistake. I will wait for the issue to be assigned to me before making a PR in the near future.

**Comment by mtreacy002** [comment]
@stableapple , please follow the issue template and give relevant information on each section description. [Here's](https://github.com/anitab-org/bridge-in-tech-web/issues/186#issue-817971789) a good example of an issue description using the Feature request template. So, the description you provide [above](https://github.com/anitab-org/bridge-in-tech-web/issues/180#issue-814714224) is suitable for the `Describe the solution you'd like` section.

**Comment by stableapple** [comment]
@mtreacy002 I have updated the issue description. Can you please review it.
