### ISSUE TITLE
Unnecessary Large Size For A Simple Checkbox

### ISSUE THREAD

**Issue by CIPHERTron** [anitab-org/bridge-in-tech-web#183]
**Describe the bug**
When we go to the **Register** section and Scroll down to the **checkbox** where we agree to the **Terms and Conditions** and **Privacy Policy** and if we inspect the checkbox element, we find the checkbox is wrapped inside a div whose dimensions is **(119 x 64)** which I think is not necessary.

**To Reproduce**
1. Go to 'localhost:3000'
2. Click on 'Register'
3. Scroll down to 'Checkbox for Code of Conduct and Privacy Policy'

**Expected behavior**
A checkbox of smaller dimensions, let's say (15 x 15) would suffice.

**Screenshots**
![Screenshot (592)_LI](https://user-images.githubusercontent.com/56754747/109152239-3baba500-7791-11eb-87af-975f2f60b9e4.jpg)

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Version any

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser any
 - Version any

**Comment by Rahulm2310** [comment]
@CIPHERTron Thanks for looking into it. As we are redesigning the whole website, this will be covered too. So, don't worry about this. 🙂

Cc: @mtreacy002

**Comment by mtreacy002** [comment]
@CIPHERTron , I agree with @Rahulm2310 . But thanks anyway for pointing this out 😉. Will close this issue now.
