### ISSUE TITLE
Feat: Migrating documentation from github wiki to docusaurus

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-web#186]
## Description

**Is your feature request related to a problem? Please describe.**
Current documentation is fine but with `docusaurus` , the documentation becomes more readable and maintainable.

**Describe the solution you'd like**
Moving the project's documentation to [docusaurus](https://v2.docusaurus.io).

**Additional context**
BIT backend has already migrated project documentation to docusaurus.

## Acceptance Criteria

- [ ] Move documentation to Docusaurus
- [ ] Deploy Docusaurus as part of GitHub pages - should be available at https://anitab-org.github.io/bridge-in-tech-web

**Comment by CIPHERTron** [comment]
Heyy @mtreacy002 @Rahulm2310 I would like to work on this issue. Could you please assign it to me? Thank you! 😊

**Comment by mtreacy002** [comment]
@CIPHERTron , let's ask if @Rahulm2310 would like to work on this since he opens the issue, or if he's happy to pass it on for others to work on 😉.

**Comment by CIPHERTron** [comment]
Sure thing @mtreacy002 😊

**Comment by Rahulm2310** [comment]
@mtreacy002 As i am already done with #179, I would like to pick it up. 🙂

**Comment by isabelcosta** [comment]
@Rahulm2310 @mtreacy002 
We (admins) have looked into assignments related to "more work needed", and we had this task planned for ambassadors that need more work done for getting ambassadors (1st edition) certificate. So I will assign this to @Frenzyritz13

Thank you for creating this issue @Rahulm2310 🙏🏾

**Comment by mtreacy002** [comment]
@Frenzyritz13 , can you please give us an update on this?

**Comment by Frenzyritz13** [comment]
> @Frenzyritz13 , can you please give us an update on this?

Sure. I have got docusaurus running in the cloned repo, I am working on structuring the information in it.

**Comment by Frenzyritz13** [comment]
Update on this: There are some errors while starting the server for testing. Working on that.

**Comment by Rahulm2310** [comment]
@Frenzyritz13 Great! please ping if you need any sort of help. 🙂

**Comment by Frenzyritz13** [comment]
> @Frenzyritz13 Great! please ping if you need any sort of help. 🙂 

Sure will do. I will post on zulip and tag you if I can't figure it by tomorrow evening. Thank you!

**Comment by mtreacy002** [comment]
@Frenzyritz13 , can you please update us on this?

**Comment by Frenzyritz13** [comment]
> @Frenzyritz13 , can you please update us on this?

Almost done. Should create a pull request in a couple of days.

**Comment by mtreacy002** [comment]
@Frenzyritz13 , any updates on the PR?

**Comment by Rahulm2310** [comment]
@mtreacy002 Should we make this available again as there are no updates from @Frenzyritz13 ?

**Comment by Frenzyritz13** [comment]
> @mtreacy002 Should we make this available again as there are no updates from @Frenzyritz13 ?

Apologies for the delay. Still working through the errors. Should be done by Friday.

**Comment by codesankalp** [comment]
@Frenzyritz13 try to make the PR compatible to deployment on github pages.
reference: https://github.com/anitab-org/mentorship-backend/commit/4cc78ae

**Comment by Rahulm2310** [comment]
@Frenzyritz13 Please share the updates on this. If you are occupied, we can make it available for OSH aspirants.

**Comment by Frenzyritz13** [comment]
> @Frenzyritz13 Please share the updates on this. If you are occupied, we can make it available for OSH aspirants.

I am stuck at the last step I think. Give me a couple of more days. I should be able to tell you exactly what's going wrong.

**Comment by Frenzyritz13** [comment]
Progress update: Sorting the documents in the right hierarchy.

**Comment by Frenzyritz13** [comment]
> Progress update: Sorting the documents in the right hierarchy.

Working on the linking of the right documents and checking for any systers reference. Should be able to create a pull request before my next update.

**Comment by mtreacy002** [comment]
Thank you @Frenzyritz13 for your updates, can you tell us roughly how close you are to submit a pull request?

**Comment by mtreacy002** [comment]
@Frenzyritz13 , can you please update us on this? If you have other issues you're working on at the moment and unable to submit the pull request for this, we can open the issue for other contributors to claim.

**Comment by Frenzyritz13** [comment]
> @Frenzyritz13 , can you please update us on this? If you have other issues you're working on at the moment and unable to submit the pull request for this, we can open the issue for other contributors to claim.

Hey, no. I am just having trouble with the last part. I will create a pull request tomorrow and keep completing it.

**Comment by isabelcosta** [comment]
@Frenzyritz13 we'll make this available due to inactivity. Feel free to later contribute to other issues if you wish, for now, this is a blocking issue we want to solve to make our projects processes consistent.

**Comment by codesankalp** [comment]
As this is not an OSH issue. Can I work on it?

**Comment by mtreacy002** [comment]
Sure, @codesankalp . I'm assigning you now 😉

**Comment by codesankalp** [comment]
@mtreacy002 As GitHub-pages is already active for this repository, how can I deploy the docusaurus docs on this repo github-pages?
My work is almost done.
Do I have to deploy it on surge?

**Comment by Rahulm2310** [comment]
@codesankalp for now you can deploy it to surge (similar to how it is done for backend) as the frontend is already using gh-pages.
