### ISSUE TITLE
Doc: Add link to Bridge In Tech Setup Instructions

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#19]
## Description
As a contributor,
I need to see a link on the README file to where I can read setup instruction for development environment of Bridge In Tech backend,
so that I can contribute to the project.

## Mocks
NA
### Update [Required]
- [ ] Add a link with necessary description on README.md to go to BridgeInTech Development Environment Setup Instructions which can be found on bridge-in-tech-backend wiki repository.
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
< 1 hour

**Comment by mahakbansal2019** [comment]
Hey @mtreacy002!
Can I work on this ?
Thanks :)

**Comment by mtreacy002** [comment]
Sure, go ahead, @mahakbansal2019 . Let me know if you need any help. Also, I'll move this issue to backend. I put it on frontend by accident. So, please add the link to the bridge-in-tech-backend repository README.md, not frontend 😉

**Comment by mtreacy002** [comment]
Issue moved to [anitab-org/bridge-in-tech-backend #55](https://github.com/anitab-org/bridge-in-tech-backend/issues/55) via [**ZenHub**](https://www.zenhub.com/)
