### ISSUE TITLE
Bug: remove warnings from app compilation

### ISSUE THREAD

**Issue by nlok5923** [anitab-org/bridge-in-tech-web#192]
### Describe the bug
@mtreacy002 currently there are few warnings show up while compiling app and needed to be removed.

### To Reproduce
1 npm install ( make sure you are in correct directory)
2 npm start 

### Expected behavior
No warnings at compilation time 

### Screenshots
![image](https://user-images.githubusercontent.com/56120084/110414780-98bf2900-80b6-11eb-933d-639d7016f8d3.png)

### Desktop (please complete the following information):
 - OS: [e.g. iOS] all
 - Browser [e.g. chrome, safari] all

### Additional context
I think this can be a good first issues for first timers .

**Comment by mtreacy002** [comment]
I agree, this seems like a good first-timers issue. Thanks for picking this up, @nlok5923 😉

**Comment by stableapple** [comment]
Can I work on this issue?

**Comment by mtreacy002** [comment]
Sure, @stableapple , I'll assign you to this. Thanks for picking up the issue 😉.
