### ISSUE TITLE
Bug: Navbar elements has underline 

### ISSUE THREAD

**Issue by nlok5923** [anitab-org/bridge-in-tech-web#193]
### Describe the bug

Currently all the elements in navbar has underline 

### To Reproduce
1. Go to BIT landing page
2. See issue

### Expected behavior
Navbar elements should not be underlined.

### Screenshots

![image](https://user-images.githubusercontent.com/56120084/110415087-403c5b80-80b7-11eb-9a39-61564e27fc07.png)

### Desktop (please complete the following information):
 - OS: [e.g. iOS] all
 - Browser [e.g. chrome, safari] all
 - Version [e.g. 22] all 

### Smartphone (please complete the following information):
 - Device: [e.g. iPhone6] all
 - OS: [e.g. iOS8.1] all
 - Browser [e.g. stock browser, safari] all
 - Version [e.g. 22] all

### Additional context
removal of underline from navbar elements is needed.

**Comment by Rahulm2310** [comment]
@nlok5923 As we are redesigning the navbar, this issue will be addressed. So no need for this. 

Cc: @mtreacy002
