### ISSUE TITLE
Doc: Add number of forks badge to README

### ISSUE THREAD

**Issue by Sanika1999** [anitab-org/bridge-in-tech-web#198]
## Description
As a developer,
I need to see a badge showing the number of forks for the repo.
Example: See badges in the readme for mentorship android  (https://github.com/anitab-org/mentorship-android)

### Update [Required]
- [ ] Add number of forks badge to README 
### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by Rahulm2310** [comment]
@Sanika1999 I think this is redundant as we already have a fork button on the top right corner of the github repo landing page. 

![image](https://user-images.githubusercontent.com/54268438/111517407-0afcd100-877b-11eb-8520-7822be887e42.png)

**Comment by Sanika1999** [comment]
> @Sanika1999 I think this is redundant as we already have a fork button on the top right corner of the github repo landing page. 
> 
> ![image](https://user-images.githubusercontent.com/54268438/111517407-0afcd100-877b-11eb-8520-7822be887e42.png)
> 

Yes you are right but mentorship android and Anitab website repos have those badges and it would be a nice issue for first timers or beginners to start contributing.

**Comment by Rahulm2310** [comment]
@Sanika1999 agreed but it's presence in mentorship android and anitab-org.github.io doesn't mean it isn't redundant. We should not create vague issues just for the sake.

**Comment by mtreacy002** [comment]
@Sanika1999 , I agree with @Rahulm2310 , it's best to avoid introducing redundancy to the repo. Perhaps you can suggest this as well on the other projects? So, I'll close this issue now. Feel free to continue the discussion though, I'll open to hear strong argument to why it is needed and willing to open the issue again if there is a valid reason for it 😉

**Comment by Sanika1999** [comment]
@mtreacy002  sorry for that. Will make sure to check with you guys before opening issues. Iam still learning 😁

**Comment by mtreacy002** [comment]
No worries, @Sanika1999 . That's part of the beauty of open source. We'll be continuously learning new things throughout our open source journey 😉. I am still learning a lot coming to AnitaB Open Source and community 😁🥰.
