### ISSUE TITLE
Bug: Members list not scrollable on smaller screen sizes

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-web#199]
### Describe the bug
Members list under `/members` is not scrollable on smaller screen sizes. 

### To Reproduce
1. Go to http://localhost:3000/members
2. Shrink down your browser width.

### Expected behavior
Ideally, the list should be horizontally scrollable.

### Screenshots
![bit-members-list](https://user-images.githubusercontent.com/54268438/111522167-01c23300-8780-11eb-933a-b41f2c908551.gif)

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

**Comment by prykdev** [comment]
I'd like to work on this if it is available. : )

**Comment by HeroicHitesh** [comment]
@P-riyanka-prasad we will be assigning all issues labelled `Open Source Hack` on and/or after 1st April when Open Source Hack starts (as per the [announcement](https://anitab-org.zulipchat.com/#narrow/stream/213491-announcements/topic/Open.20Source.20Hack/near/230741560) on Zulip). Till then you can set up the project in your machine and if you have any doubts please ask by tagging @anitab-org/maintainers 
cc @Rahulm2310

**Comment by prykdev** [comment]
I would like to work on this :)

**Comment by epicadk** [comment]
Happy coding @P-riyanka-prasad : ).

**Comment by Amulya-coder** [comment]
Yours @P-riyanka-prasad

**Comment by prykdev** [comment]
:) Thanks

**Comment by decon-harsh** [comment]
@P-riyanka-prasad Don't forget to complete the mandatory task first #218.

**Comment by Rahulm2310** [comment]
@P-riyanka-prasad You have already been assigned to [#128](https://github.com/anitab-org/stem-diverse-tv/issues/128) on stem-diverse-tv. We can't assign a contributor to more than one issue at the same time. Please decide which one do you want to continue with and unassign yourself from the other one. Also, I think it is compulsory for every OSH aspirant to successfully complete #218 and then should be eligible for other available issues. So, for now unassigning @P-riyanka-prasad. Please complete the compulsory task and then claim this. Thanks 🙂

**Comment by epicadk** [comment]
> @P-riyanka-prasad You have already been assigned to [#128](https://github.com/anitab-org/stem-diverse-tv/issues/128) on stem-diverse-tv. We can't assign a contributor to more than one issue at the same time. Please decide which one do you want to continue with and unassign yourself from the other one. Thanks 🙂

afaik it was one issue per repository.

**Comment by naveen8801** [comment]
Hi @Rahulm2310 , i'd like to work on this :-)

**Comment by keshakaneria** [comment]
> Hi @Rahulm2310 , i'd like to work on this :-)

Go for it

**Comment by naveen8801** [comment]
hi @keshakaneria @Rahulm2310  , i have made a PR , please review :-)
