### ISSUE TITLE
UI: High-fidelity Mockup - Register

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#2]
@mtreacy002 commented on [Thu May 14 2020](https://github.com/anitab-org/bridge-in-tech-backend/issues/20)

## Description
As a student,
I need create high-fidelity mockup for Register,
so that I can move forward with on the planning stage.

## Mocks
Initial idea (per proposal)
Figure 1.1. Register
<img width="1133" alt="BridgeInTech MockUp - Register" src="https://user-images.githubusercontent.com/29667122/81883605-fe4aa200-95d8-11ea-8750-cab841e5a388.png">

### Update [Required]
- [ ] must have all the fields for Mentorship System user registration:
       [ ] name
       [ ] username
       [ ] password
       [ ] confirm password 
       [ ] email
       [ ] terms and conditions check box 
       [ ] need mentoring check box
       [ ] available to mentor check box
       
- [ ] must have `Organization` and `Mentor/Mentee` check box
- [ ] must have `Signup` and `Login` buttons
- [ ] must have `view/hide` password field options

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

**Comment by mtreacy002** [comment]
Update:
@isabelcosta, @ramitsawhney27, and @foongminwong. Here is the high-fidelity for Register page I made using _justinmind_ as suggested. Color code are taken from AnitaB.org logo color mix. 

<img width="1025" alt="Screen Shot 2020-05-14 at 3 16 33 pm" src="https://user-images.githubusercontent.com/29667122/81895604-f9e0b200-95f5-11ea-9843-10538cc34c4f.png">


[Link to file](https://drive.google.com/open?id=1Tq5En7AeaINm6dD1Lq0VGnn7XqSFUC-5)

I'm no designer so I know this is far from ideal. Please do give me your opinion on this. If you like this as it is, please give your approval by using ✅ on this post. Thanks heaps.

PS: I couldn't find ways to arrange the exact distancing between components on justinmind. Still working my way around this tool ☺️ . Also, @isabelcosta, I can't see any where the `share` button, so I upload the file onto BridgeInTech Google folder instead.

While waiting I'm going to open an issue at backend repo and start working on the API endpoints and CRUD operations for this page.

**Comment by foongminwong** [comment]
Like your design! When a user checks 'Yes' for 'Do you represent an organization?', will an extra space pop up so that the user can enter his/her/their organization?

**Comment by isabelcosta** [comment]
@mtreacy002 about the share button, we can troubleshoot this in our 1:1 this Saturday ;)
Excited to see this mockup 🤗 

Questions that came up:
- Is the "Available to be a mentor or mentee", relevant to an organization profile?
- if you are just registering (you are not a logged user), are you supposed to be able to see Programs, Organizations, mentors and mentees etc?

**Comment by mtreacy002** [comment]
Thanks, @isabelcosta.
On your questions:
> Is the "Available to be a mentor or mentee", relevant to an organization profile?

Yes, because:
* only a user can create an organization. When they register, they register as a user, not as organization. But the answer to `Do you represent to an organization` will initiate the `User_Extension` with the new registered user Id so when they login at a later session, they are allowed to create an Organization profile then create a program/s.
* a user doesn't have to be available as mentor or mentee but this (having checkbox `available to be a: ...` will give them possibility to volunteer as a mentor to any program (perhaps the organization might even requires its representative to be available to mentor at least to one of the programs it's offering). 
Also this will make it possible for the rep who is interested to apply to a program offered by other organization as a mentee (depends on the organization they representing, which might allow this to happen).
> if you are just registering (you are not a logged user), are you supposed to be able to see Programs, Organizations, mentors and mentees etc?

I would love to think so, this is so:
* the general public becomes aware of the potential of joining as mentor/mentee/organizations
* to meet BridgeInTech aimed as a pool talent where organizations who are looking for a potential employee can browse mentor/mentee profile/mentorship program history within BridgeInTech and see what skills they (mentor/mentee) have accumulated from the BIT programs. As for mentor/mentee, this gives them opportunities to promote themselves as skilled worker. 

If the general public wants to be involved in BIT, they then need to be registered.
What's your thoughts on this, @isabelcosta?

**Comment by mtreacy002** [comment]
Update:
I've made adjustment to the Register page. I've added `Both` as the 3rd options for `Available to be a:....` (as per the recent change made on Mentorship Android UI).
 
<img width="1027" alt="Screen Shot 2020-05-15 at 10 19 15 am" src="https://user-images.githubusercontent.com/29667122/81999599-ee929280-9698-11ea-8158-7268167345f2.png">

**Comment by mtreacy002** [comment]
> Like your design! When a user checks 'Yes' for 'Do you represent an organization?', will an extra space pop up so that the user can enter his/her/their organization?

@foongminwong, atm, I''m thinking that with this checkbox, if it's `ticked` (==true) once the user data related to `User` table is recorded in MS schema, the new user id will be used to create an instance of `User_extention` in BIT schema. When the user login for the first time, they'll be taken to the [`Create Profile - fig.4.6` then `Create Company Profile - fig.3.3`](https://github.com/anitab-org/bridge-in-tech-backend/issues/6) pages.  The user can also be given a chance to then take their time to when they want to create an organization profile (but this can only be done after this user fill in their user profile). Maybe we can put a `Skip for now` button for this. 
Also, they can only create a program when they've completed the minimum information required from the `User Profile` and  `Organization Profile` that will be needed for creating a Program.

**Comment by mtreacy002** [comment]
Hi @anitab-org/bridgeintech-maintainers, I have something I'd like your vote/opinion on.
Atm, I have separate tabs for Mentors and Mentees (lists) because originally on Mentorship System we're not allowing a mentor to also be a mentee. With the recent change (`Both` as 3rd option on `Available to be a:...` question). Now I'm thinking of just putting the Mentors and Mentees together in one tab. I'm wondering what's the best name for this tab. Options I could think of:
🐯 Participants
🐼 Professionals
🦊 Collaborators
🐨Members

Or maybe you have another option?

**Comment by mtreacy002** [comment]
Note to self:

* Need to add `Login` button to alternate between SignUp and Login pages.
* Need to add `Timezone` field to register page (to initiate the users_extension table, we need: user_id, is_organization_rep, timezone)).

**Comment by isabelcosta** [comment]
@mtreacy002 I like :koala: Members :) but I'm biased since I am using that on mentorship system. I feel it's less specific about the roles of the users. Then you can specify in the item in the list thst represents a user. This is my opinion :)

**Comment by foongminwong** [comment]
Some comments: 
* To follow the current UI design on mentorship-android, change the check buttons of "Mentor, Mentee, Both" to radio buttons 
* I would prefer `Members`  (`Participants` is a little too common,  `Professionals` sounds a little related to organizations, `Collaborators` might confuse users who join BIT that they might be working on projects)

**Comment by foongminwong** [comment]
Remember to let users enter `email address` for registration

**Comment by mtreacy002** [comment]
Update:
Register page (now using Figma)

<img width="928" alt="Screen Shot 2020-05-26 at 5 47 25 pm" src="https://user-images.githubusercontent.com/29667122/82874592-86d22680-9f79-11ea-9ed9-b43bcb3c2022.png">




[link to file](https://www.figma.com/file/jxCqu1lq55H7jC4FDY119a/BridgeInTech?node-id=10%3A1)

**Comment by mtreacy002** [comment]
Update:
Hi @anitab-org/bridgeintech-maintainers. I've made tiny (but important change) to the Register page. Now it has the `Timezone` field so user can tell us their timezone at the time of registration. this will be a selector from list of Timezone enum.

<img width="473" alt="Screen Shot 2020-05-28 at 12 34 00 pm" src="https://user-images.githubusercontent.com/29667122/83092130-0da11380-a0e0-11ea-810b-60de5036d1c2.png">


The list of timezone as overlay

<img width="1080" alt="Screen Shot 2020-05-28 at 2 24 21 pm" src="https://user-images.githubusercontent.com/29667122/83098846-0df4db00-a0ef-11ea-8302-64192c30a94b.png">

**Comment by mtreacy002** [comment]
Note for potential reusable components:

* Text input field
<img width="403" alt="Screen Shot 2020-05-31 at 9 17 00 pm" src="https://user-images.githubusercontent.com/29667122/83351074-54af3300-a384-11ea-8ba3-c06bab4b8aca.png">

* Password input field
<img width="405" alt="Screen Shot 2020-05-31 at 9 17 17 pm" src="https://user-images.githubusercontent.com/29667122/83351085-655fa900-a384-11ea-9e4c-a573d491769c.png">

* Selector input field
<img width="405" alt="Screen Shot 2020-05-31 at 9 17 26 pm" src="https://user-images.githubusercontent.com/29667122/83351091-73adc500-a384-11ea-8463-4f2b7f116872.png">

* Availability type radio buttons
<img width="222" alt="Screen Shot 2020-05-31 at 9 17 43 pm" src="https://user-images.githubusercontent.com/29667122/83351098-83c5a480-a384-11ea-97ee-024ffdf37d31.png">

* Is organization representative radio buttons
<img width="221" alt="Screen Shot 2020-05-31 at 9 17 50 pm" src="https://user-images.githubusercontent.com/29667122/83351116-9fc94600-a384-11ea-93d4-bee7407aa743.png">

* button 
<img width="80" alt="Screen Shot 2020-05-31 at 9 17 58 pm" src="https://user-images.githubusercontent.com/29667122/83351136-ba032400-a384-11ea-9e49-3c5c00d8436d.png">

* form container
<img width="486" alt="Screen Shot 2020-05-31 at 9 22 34 pm" src="https://user-images.githubusercontent.com/29667122/83351176-077f9100-a385-11ea-94f6-8a4781aceea4.png">

* check box and text 
<img width="497" alt="Screen Shot 2020-05-31 at 9 39 08 pm" src="https://user-images.githubusercontent.com/29667122/83351446-59291b00-a387-11ea-9ffd-b7c0c9bc3600.png">

**Comment by meenakshi-dhanani** [comment]
Hey @mtreacy002 looks good, I however have an alternate approach. We can think of the RegistrationForm/Register as a component, when you see a repetition/duplication while creating other components, you can then extract it out to a reusable/common one. If you pre-plan this, I'm afraid we may cause a certain amount of over-engineering. So start off with one component, and wait till you see duplication to extract.

**Comment by mtreacy002** [comment]
> Hey @mtreacy002 looks good, I however have an alternate approach. We can think of the RegistrationForm/Register as a component, when you see a repetition/duplication while creating other components, you can then extract it out to a reusable/common one. If you pre-plan this, I'm afraid we may cause a certain amount of over-engineering. So start off with one component, and wait till you see duplication to extract.

Agree. I was actually thinking about that too... Making it as Form level (Register Form) as component will probably help make it faster to be reused rather than adding field one at a time... 😂. Thanks for the tips, @meenakshi-dhanani

**Comment by mtreacy002** [comment]
Update:

To overcome the [issue](https://github.com/anitab-org/bridge-in-tech-backend/issues/24#issuecomment-636914484) blocking [issue#26 backend](https://github.com/anitab-org/bridge-in-tech-backend/pull/26), the Register form needs to be modified as below:

<img width="530" alt="Screen Shot 2020-06-02 at 2 03 05 pm" src="https://user-images.githubusercontent.com/29667122/83478845-42dfa400-a4da-11ea-9b56-5f4d52fff1cf.png">

Can @anitab-org/bridgeintech-maintainers mentors please approve this change so I can apply the backend change accordingly.
Thanks beforehand
