### ISSUE TITLE
Bug: validation alert not shown when user enters spaces as input in name and password fields

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-web#202]
### Describe the bug

Input validation alert not shown when user enters space as input in name and password fields

### To Reproduce
1. Go to http://localhost:3000/register
2. Enter a number of spaces in name and password fields
3. See error

### Expected behavior

Validation alerts should be shown in case user enters spaces as input in name and password fields.

### Screenshots

![bit-name](https://user-images.githubusercontent.com/54268438/112365622-e023f700-8cfd-11eb-88ed-ef566c297bbe.gif)
![bit-password](https://user-images.githubusercontent.com/54268438/112369353-1a8f9300-8d02-11eb-810f-38e98d4f355f.gif)

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

**Comment by Rahulm2310** [comment]
@mtreacy002 Can you please confirm this issue? Thanks 🙂

**Comment by mtreacy002** [comment]
This seems like a valid issue, @Rahulm2310. Thanks for bringing this up and sorry for the late response. Will label it OSH too 😉.

**Comment by sachinsom93** [comment]
@mtreacy002 can I work on this issue ?

**Comment by Rahulm2310** [comment]
Sure @sachinsom93. Go ahead with the fix ☺️

**Comment by mtreacy002** [comment]
Making this available again for others to work on.

**Comment by naveen8801** [comment]
Hi @mtreacy002, I'd like to work on it, please assign :)

**Comment by mtreacy002** [comment]
Sure, @naveen8801. Will assign you to this now. Thanks for picking this up 😉.
