### ISSUE TITLE
Add project description in description meta tag in index.html

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-web#203]
### Is your feature request related to a problem? Please describe.

Currently we have a description meta tag but the content doesn't contains the project description.
![image](https://user-images.githubusercontent.com/54268438/112371511-b02c2200-8d04-11eb-9df5-527af607ed01.png)

### Describe the solution you'd like

Adding content to description meta tag in index.html.

### Describe alternatives you've considered

NA

### Additional context

Project description can be found on project's readme or wiki.

**Comment by prykdev** [comment]
I'd like to work on this

**Comment by shades-7** [comment]
i would like to work on this.

**Comment by devkapilbansal** [comment]
@shades-7 please make changes to this [pull request](https://github.com/anitab-org/anitab-org.github.io/pull/247) first

**Comment by devkapilbansal** [comment]
@P-riyanka-prasad you are already assigned an issue

**Comment by shades-7** [comment]
> @shades-7 please make changes to this [pull request](https://github.com/anitab-org/anitab-org.github.io/pull/247) first

done

**Comment by devkapilbansal** [comment]
@shades-7 assigning you.

P.S. :- Ensure you complete the necessary set up task first
