### ISSUE TITLE
Docs: Add link to zulip stream in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-web#204]
### Describe the bug

The link to project's zulip stream is missing in CONTRIBUTING.md. 

### To Reproduce
1. Go to [contributing.md](https://github.com/anitab-org/bridge-in-tech-web/blob/develop/.github/CONTRIBUTING.md)
2. See error

### Expected behavior

Add link to zulip stream in CONTRIBUTING.md

### Screenshots

![bit-cont](https://user-images.githubusercontent.com/54268438/112668901-088a2d80-8e85-11eb-9f5a-d248f945b617.JPG)

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

**Comment by naveen8801** [comment]
Hi , @Rahulm2310  , i am very excited for upcoming event 'open source hack' and have a query ,  assignment for the issue having tag ' Open Source Hack ' will begin from 1st April or we can ask for assigns at any time , even now ?

**Comment by Amulya-coder** [comment]
@naveen8801 anyone who claims the issue first on 1st April can get assigned to `Open Source Hack` issues, you have to make the first comment on April for assigning to this issue.  All the best 😉.

**Comment by prykdev** [comment]
I would like to work on this :)

**Comment by decon-harsh** [comment]
> I would like to work on this :)

You have been assigned #199. Please re-claim this issue after you send a successful PR to the previous assigned issue.

**Comment by battuAshita** [comment]
Hi @Rahulm2310, Can this issue be assigned to me:)

**Comment by devkapilbansal** [comment]
@battuAshita happy documenting :smile:

**Comment by Rahulm2310** [comment]
@battuAshita have you completed the compulsary task #218 ? If not please complete it first then work on this. 🙂

**Comment by devkapilbansal** [comment]
@Rahulm2310 this issue doesn't require the contributor to set up the environment

**Comment by Amulya-coder** [comment]
Agree with @devkapilbansal for the documentation-related issues it's not needed to set up the environment as these issues does not related to the main codebase.

**Comment by prykdev** [comment]
Yes

**Comment by decon-harsh** [comment]
Exactly @devkapilbansal Docs doesn't require coding skill and the need to setup , the task should be mandatory for coding/testing/outreach issues but should be optional for docs/ui issues.

**Comment by battuAshita** [comment]
I have raised a PR #219. Kindly review it :)
