### ISSUE TITLE
UI: Develop Top Navigation

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#208]
## Description
As a maintainer,
I need to see BIT pages redesigned,
so that they meet the AnitaB Org guidelines.

## Mocks
Approved design idea for Top Navigation section (Designer Nilesh)
<img width="741" alt="Screen Shot 2021-03-28 at 3 40 19 pm" src="https://user-images.githubusercontent.com/29667122/112743764-dfcd7980-8fe5-11eb-9cec-50ae56dad5a1.png">

### Update [Required]
- [ ] Implement the design above in the section it is intended (Top Navigation section of the homepage).

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

## Additional Information

Link to [Figma file](https://www.figma.com/file/V22SXBLzMd9bqnita6hfMp/Bridge_in_tech?node-id=113%3A20)

**Comment by mtreacy002** [comment]
@VectoTec , the same applies here. Let me know if you'd like to work on this as you have the 1st right to claim being the designer of the section. If you are happy to let others work on this, I'll relabel as `Available`

**Comment by naveen8801** [comment]
Hi @mtreacy002  , i have successfully completed #218  , can i work on this on now ?

**Comment by 0xNilesh** [comment]
@mtreacy002 Thanks for giving me the chance to work on it, but actually I am busy in something else 😅. Please label it as Available for others to try it on.

**Comment by mtreacy002** [comment]
Thanks for letting us know, @VectoTec . I've made this issue available now 😉

**Comment by stableapple** [comment]
Can I work on this issue?

**Comment by decon-harsh** [comment]
> Can I work on this issue?

You have one PR which is still not approved and is in discussion phase however it doesn't have `Changes Requested` Tag. So, I have asked about this issue on Zulip. I ll get back to this when someone answers it.

**Comment by decon-harsh** [comment]
@epicadk please assign @stableapple
