### ISSUE TITLE
UI: Develop Homepage - Video section

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#210]
## Description
As a maintainer,
I need to see BIT pages redesigned,
so that they meet the AnitaB Org guidelines.

## Mocks
Approved design idea for Video section (Designer Gloria Osoro)
<img width="736" alt="Screen Shot 2021-03-28 at 5 04 14 pm" src="https://user-images.githubusercontent.com/29667122/112743975-c3cad780-8fe7-11eb-83c1-c3d1ce0705dc.png">

### Update [Required]
- [ ] Implement the design above in the section it is intended (Video section of the homepage).

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

## Additional Information

Link to [Figma file](https://www.figma.com/file/V22SXBLzMd9bqnita6hfMp/Bridge_in_tech?node-id=113%3A20)

**Comment by mtreacy002** [comment]
@anitab-org/osh , the same applies here. Will check with Gloria Osoro first on zulip to see if she'd like to work on the issue.

**Comment by GloriaOsoro** [comment]
> @anitab-org/osh , the same applies here. Will check with Gloria Osoro first on zulip to see if she'd like to work on the issue.
I would love to work on this too

**Comment by mtreacy002** [comment]
Ok, @GloriaOsoro will assign you on the 1st April for OSH. Thank you 🥰

**Comment by mtreacy002** [comment]
@GloriaOsoro , do you want to work on this issue? If not I'll make it available for other contributors.

**Comment by GloriaOsoro** [comment]
@mtreacy002 Hi, I am so engaged right now, I wish I could. Please make it available for other contributors.

**Comment by mtreacy002** [comment]
No worries, @GloriaOsoro . Thanks for letting us know. Will make it available for others now 😉.

**Comment by battuAshita** [comment]
Hi @mtreacy002. May I work on this issue?

**Comment by naveen8801** [comment]
Hi @mtreacy002, can i work on this one :)

**Comment by mtreacy002** [comment]
Sorry for the delay in response. @naveen8801 , perhaps we should check if @battuAshita is still interested on this? If not, I'll assign this to you 😉. @battuAshita , do you still want to work on this?

**Comment by battuAshita** [comment]
> Sorry for the delay in response. @naveen8801 , perhaps we should check if @battuAshita is still interested on this? If not, I'll assign this to you . @battuAshita , do you still want to work on this?

Hi. I am presently caught up in some other work. You can assign it to others :)

**Comment by mtreacy002** [comment]
Thank you, @battuAshita for letting us know. @naveen8801 , I'll assign this to you now 😉. Thank you for picking this up ❤️

**Comment by naveen8801** [comment]
@mtreacy002, can you please provide the information about the video which should be present in this section, also am confused about complete design of Video section, it involves only  part shown in issue description or complete section like this one below

![Screenshot (95)](https://user-images.githubusercontent.com/54985099/123451738-67358380-d5fb-11eb-93c5-f4eb33517b2d.png)

**Comment by mtreacy002** [comment]
Hi @naveen8801 , since atm we don't have a professional video made from AnitaB.Org, we can temporarily use my [final demo video of GSOC20](https://youtu.be/7J6PPxX4sCI) for now. @isabelcosta, perhaps the @anitab-org/advocates can help with the video creation later down the track 😉? cc @Vuyanzi

**Comment by naveen8801** [comment]
> Hi @naveen8801 , since atm we don't have a professional video made from AnitaB.Org, we can temporarily use my [final demo video of GSOC20](https://youtu.be/7J6PPxX4sCI) for now. @isabelcosta, perhaps the @anitab-org/advocates can help with the video creation later down the track 😉? cc @Vuyanzi

Ok @mtreacy002, for now, I'll start with your video 👍

**Comment by naveen8801** [comment]
@mtreacy002, I have made a PR please review :)
