### ISSUE TITLE
UI: Develop Homepage - Read about us section

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#212]
## Description
As a maintainer,
I need to see BIT pages redesigned,
so that they meet the AnitaB Org guidelines.

## Mocks
Approved design idea for `Read about us` section (Designer Vuyanzi Glorious)
<img width="630" alt="Screen Shot 2021-03-28 at 5 17 51 pm" src="https://user-images.githubusercontent.com/29667122/112744199-a0089100-8fe9-11eb-8520-d4632dc4e6e5.png">

### Update [Required]
- [ ] Implement the design above in the section it is intended (`Read about us` section of the homepage).

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

## Additional Information

Link to [Figma file](https://www.figma.com/file/V22SXBLzMd9bqnita6hfMp/Bridge_in_tech?node-id=113%3A20)

**Comment by mtreacy002** [comment]
@anitab-org/osh , same applies here. Will ping Vuyanzi Glorious first on zulip to see if she'd like to work on this or happy for others to work on it.

**Comment by sidrakshe28** [comment]
hey,can you assign me this rask?

**Comment by shruti1421** [comment]
I would also like to work on this issue.

**Comment by aditisingh2412** [comment]
Hey! Can I work on this issue?

**Comment by mtreacy002** [comment]
@sidrakshe28 and anyone else interested on this issue, you must complete and submit a pr for issue #218 first for picking up any OSH issues. Once you've done that you can comeback here and request to be assigned to this issue 😉

**Comment by naveen8801** [comment]
Hi @mtreacy002  , can i work on this issue ?   :))

**Comment by mtreacy002** [comment]
Sure, @naveen8801 . Assigning you now. Thank you for picking up this issue 😉

**Comment by naveen8801** [comment]
Hi @mtreacy002  , what should be the positioning of ' Read About Us '  section ? :))

**Comment by mtreacy002** [comment]
Can you help me understand what you mean by 'positioning', @naveen8801?

**Comment by naveen8801** [comment]
> Can you help me understand what you mean by 'positioning', @naveen8801?

@mtreacy002  i mean , where it should be placed on home page , currently its above footer component :))

**Comment by mtreacy002** [comment]
HI @naveen8801. I think you need to update your fork by pulling the latest commits from upstream. We already have the `Get  In Touch` section on top of the footer in the develop branch. You can put the `Read about us` section on top of that `Get In Touch` section 😉 .
