### ISSUE TITLE
UI: Develop Homepage - FAQ section

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#213]
## Description
As a maintainer,
I need to see BIT pages redesigned,
so that they meet the AnitaB Org guidelines.

## Mocks
Approved design idea for `FAQ` section (Designer Vuyanzi Glorious)
<img width="630" alt="Screen Shot 2021-03-28 at 5 21 16 pm" src="https://user-images.githubusercontent.com/29667122/112744260-20c78d00-8fea-11eb-88ae-316dff4468d5.png">

### Update [Required]
- [ ] Implement the design above in the section it is intended (FAQ section of the homepage).

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

## Additional Information

Link to [Figma file](https://www.figma.com/file/V22SXBLzMd9bqnita6hfMp/Bridge_in_tech?node-id=113%3A20)

**Comment by mtreacy002** [comment]
@anitab-org/osh , same applies here. Will check Vuyanzi Glorious first on zulip to check if she'd like to work on this issue or happy if others pick up the issue.

**Comment by shades-7** [comment]
@mtreacy002 hey can I work on this?

**Comment by devkapilbansal** [comment]
@shades-7 you have a PR open that needs changes. Would be great if you make necessary changes there

**Comment by shades-7** [comment]
> @shades-7 you have a PR open that needs changes. Would be great if you make necessary changes there

i have made the changes please review
and it would be great if you review it and assign me this.

**Comment by Vuyanzi** [comment]
@shades-7 are you done with the PR you were working on?

**Comment by shades-7** [comment]
> @shades-7 are you done with the PR you were working on?

No, sorry for not being active for 3 days I was unwell. I am fine today will resume the work soon.

**Comment by shruti1421** [comment]
Can I work on this issue?

**Comment by mtreacy002** [comment]
@shruti1421 , have you completed the compulsory setup task for OSH (issue #218)? If not, please complete that one first 😉

**Comment by aditisingh2412** [comment]
Hey! Can I work on this issue?

**Comment by mtreacy002** [comment]
@aditisingh2412 , have you completed the #218 and submitted a pr for that? If not, please do that first 😉

**Comment by naveen8801** [comment]
Hi @mtreacy002 , i'd like to work on this , can you please assign it to me :)

**Comment by devkapilbansal** [comment]
Sure @naveen8801 you can work on this issue. Happy Coding
