### ISSUE TITLE
UI: Develop Homepage - Footer section

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#215]
## Description
As a maintainer,
I need to see BIT pages redesigned,
so that they meet the AnitaB Org guidelines.

## Mocks
Approved design idea for `Footer` section (Designer Vuyanzi Glorious)
<img width="632" alt="Screen Shot 2021-03-28 at 5 34 29 pm" src="https://user-images.githubusercontent.com/29667122/112744454-ebbc3a00-8feb-11eb-9867-aa8d406e5234.png">

### Update [Required]
- [ ] Implement the design above in the section it is intended (Footer section of the homepage).

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

## Additional Information

Link to [Figma file](https://www.figma.com/file/V22SXBLzMd9bqnita6hfMp/Bridge_in_tech?node-id=113%3A20)

**Comment by mtreacy002** [comment]
@anitab-org/osh , same applies here. Will check with Vuyanzi Glorious first on zulip if she'd like to work on this or if she's happy for other contributor to claim this.

**Comment by naveen8801** [comment]
Hi @mtreacy002  , i wanna work on this issue , can you assign it to me :-)

**Comment by Rahulm2310** [comment]
@naveen8801 Thanks for showing interest. As this issue is labelled `Open-Source-Hack` (our month long open source event), this issue will be available on/after 1st April when the event commences. Good Luck 😊

**Comment by naveen8801** [comment]
Thanks @Rahulm2310  for informing :-)

**Comment by naveen8801** [comment]
hi @mtreacy002  , i wanna work on it , can  you assign it to me :-)

**Comment by decon-harsh** [comment]
@epicadk Please assign him

**Comment by epicadk** [comment]
> @epicadk Please assign him


Did Vuyanzi say that she didn't want to work on this?

**Comment by decon-harsh** [comment]
You are right these issues are to be claimed by respective designer first @epicadk .Thank you , i almost forgot

**Comment by Vuyanzi** [comment]
> > @epicadk Please assign him
> 
> Did Vuyanzi say that she didn't want to work on this?

@epicadk There's still a lot of design issues so if someone wants to work on the code I have no problem if they get assigned the sections I designed :)

**Comment by Vuyanzi** [comment]
> Hi @mtreacy002 , i wanna work on this issue , can you assign it to me :-)

Hello @naveen8801 I have assigned the issue to you and I'd be more than happy to jump on a call with you if you need any clarification on whats required :)

**Comment by Vuyanzi** [comment]
> @anitab-org/osh , same applies here. Will check with Vuyanzi Glorious first on zulip if she'd like to work on this or if she's happy for other contributor to claim this.

@mtreacy002 feel free to assign the sections I designed to other members, there're definitely other design tasks I could pick up.

**Comment by naveen8801** [comment]
> > Hi @mtreacy002 , i wanna work on this issue , can you assign it to me :-)
> 
> Hello @naveen8801 I have assigned the issue to you and I'd be more than happy to jump on a call with you if you need any clarification on whats required :)

Thanks @Vuyanzi 👍

**Comment by Rahulm2310** [comment]
@naveen8801 Please do the changes requested on [#254](https://github.com/anitab-org/bridge-in-tech-backend/pull/254) before working on this.

**Comment by naveen8801** [comment]
> @naveen8801 Please do the changes requested on [#254](https://github.com/anitab-org/bridge-in-tech-backend/pull/254) before working on this.

sure @Rahulm2310  , 👍

**Comment by naveen8801** [comment]
> @naveen8801 Please do the changes requested on [#254](https://github.com/anitab-org/bridge-in-tech-backend/pull/254) before working on this.

Hi @Rahulm2310  , I have made changes to [#254](https://github.com/anitab-org/bridge-in-tech-backend/pull/254) , please review :-)

**Comment by naveen8801** [comment]
Hi @mtreacy002  @Vuyanzi , how to get icons similar to those used in figma designs and also how to import font family ' Meta Pro'
? :)

**Comment by mtreacy002** [comment]
@naveen8801 , you can export the icon on Figma as .svg to be used in your code. [Here](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech/topic/BridgeInTech.20Redesign/near/230133523) is my zulip post explaining how this can be done. Let me know if you have any further question 😉

**Comment by naveen8801** [comment]
> @naveen8801 , you can export the icon on Figma as .svg to be used in your code. [Here](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech/topic/BridgeInTech.20Redesign/near/230133026) is my zulip post explaining how this can be done. Let me know if you have any further question 😉

Thanks @mtreacy002 👍

**Comment by mtreacy002** [comment]
In regard to `Meta Pro` font, I think you can find it on the doc pointed out by @annabauza on her zulip post [here](https://anitab-org.zulipchat.com/#narrow/stream/225705-STEM-diverse-tv/topic/design/near/212972418)

**Comment by naveen8801** [comment]
> In regard to `Meta Pro` font, I think you can find it on the doc pointed out by @annabauza on her zulip post [here](https://anitab-org.zulipchat.com/#narrow/stream/225705-STEM-diverse-tv/topic/design/near/212972418)

@mtreacy002 , ok 👍

**Comment by naveen8801** [comment]
Hi @mtreacy002   , i have completed designing of footer component in desktop view as shown below , can you please tell me , what should be the behavior when screen size decreases (on mobile view or tablet view ) , should i use custom media queries for it ?


![Screenshot (53)](https://user-images.githubusercontent.com/54985099/114273366-61d28f00-9a37-11eb-93fe-9177b9402e22.png)

**Comment by decon-harsh** [comment]
> Hi @mtreacy002   , i have completed designing of footer component in desktop view as shown below , can you please tell me , what should be the behavior when screen size decreases (on mobile view or tablet view ) , should i use custom media queries for it ?
> 
> 
> ![Screenshot (53)](https://user-images.githubusercontent.com/54985099/114273366-61d28f00-9a37-11eb-93fe-9177b9402e22.png)
> 

@Rahulm2310 I guess you can help him with this.

**Comment by Rahulm2310** [comment]
@naveen8801 for mobile/tablet view, you can try stacking the sections one over the other using media queries.

**Comment by naveen8801** [comment]
> @naveen8801 for mobile/tablet view, you can try stacking the sections one over the other using media queries.

ok @Rahulm2310

**Comment by naveen8801** [comment]
Hii @Rahulm2310  , @mtreacy002  , I have made a PR , please have a look , and provide some suggestions for more attractive UI :)
