### ISSUE TITLE
Research: Using gh-pages as remote frontend

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-web#216]
### Is your feature request related to a problem? Please describe.

We need to deploy our frontend to a hosting service (ideally free)

### Describe the solution you'd like

Research about hosting the project (frontend) on `gh-pages` (discuss possibility, benefits/disadvantages, and potential issues).

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by shades-7** [comment]
May I work on this?

**Comment by Rahulm2310** [comment]
@shades-7 Please complete the compulsary task  #218 before claiming any other issue. 🙂

**Comment by shades-7** [comment]
@Rahulm2310 ok

**Comment by shades-7** [comment]
> @shades-7 Please complete the compulsary task #218 before claiming any other issue.

Hey, can i work on this now since I have completed the setup task and previously assigned tasks?

**Comment by Rahulm2310** [comment]
@shades-7 Assigned you #214

**Comment by shades-7** [comment]
Hey, i would like to work on this.

**Comment by shades-7** [comment]
@isabelcosta may I work on this?

**Comment by jalajcodes** [comment]
> @isabelcosta may I work on this?

Assigned you. Good luck!

**Comment by shades-7** [comment]
here it's written about hosting on gh-pages, but I have an idea about hosting on other platform, i.e netlify can I add this too in the research or I have to stick strictly to gh-pages only?

**Comment by Rahulm2310** [comment]
@shades-7 You can include points about how `netlify` would be a better option than `github-pages`. This is the reason we want to research on it to find the best possible solution.🙂

**Comment by shades-7** [comment]
how to submit PR for this?

**Comment by Rahulm2310** [comment]
@shades-7 you can create a google doc explaining all your findings, create a pull request and add the link to the doc in the PR description. Also,  please update the link with `Edit` access for everyone, so that anyone can add comment and continue with the discussions on the document you've shared. 🙂 
For more, refer [here](https://github.com/anitab-org/bridge-in-tech-web/pull/225).

**Comment by mtreacy002** [comment]
Closing this issue now since the suggested solution by @shades-7  (with issue #240) had already been accepted and added to BIT web wiki sidebar.

<img width="284" alt="Screen Shot 2021-04-30 at 7 06 31 am" src="https://user-images.githubusercontent.com/29667122/116618595-9aa0bc80-a982-11eb-9852-d109a3667b53.png">
