### ISSUE TITLE
Research: Refactor useState() hooks to useReducer()

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-web#217]
### Is your feature request related to a problem? Please describe.

Currently we have a lot of separate useState() hooks in each component which makes them less maintainable. The idea is to refactor all the useState() hooks to a useReducer() hook.

### Describe the solution you'd like

Research about it. Discuss benefits/disadvantages, and if to be implemented, when is the best timing for refactoring to happen.

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by sdew021** [comment]
Can I take up this issue?

**Comment by jalajcodes** [comment]
@sdew021 Hi there, you need to complete the compulsory task [#218](https://github.com/anitab-org/bridge-in-tech-web/issues/218) before claiming other issues.

**Comment by HarshKumarChoudary** [comment]
Can I help to solve this issue?

**Comment by Aaishpra** [comment]
@HarshKumarChoudary Are you assigned to any other issue currently. If not then I can assign you here.

**Comment by HarshKumarChoudary** [comment]
I had been assigned one task for which I had made a PR which is Ready to merge.

**Comment by Aaishpra** [comment]
Great assigned you here then

**Comment by HarshKumarChoudary** [comment]
I want to know where we have to describe the solution, in code area or make a new file for it

**Comment by Aaishpra** [comment]
I guess this is a research-based issue you just have to suggest benefits/disadvantages here in the comments maybe.
Tagging @Rahulm2310 for your help.

**Comment by jalajcodes** [comment]
> I want to know where we have to describe the solution, in code area or make a new file for it

You dint have to code it right away, this is more of a research type issue. See if you can answer these questions.
- why should we migrate to useReducer?
- what are its benifits? 
- what would be the best way to implement it? (You can convert a simple component from the codebase and share with us here or create a [gist](https://gist.github.com))

**Comment by Rahulm2310** [comment]
@HarshKumarChoudary You can also create a doc file describing the solution. You can answer the questions by @jalajcodes in the doc as well.

**Comment by mtreacy002** [comment]
I agree with @Rahulm2310, creating it on a doc file will means more than one contributors can propose a suggestion and the PR which solution is approved can be merged and later located easily in the repo when we're ready to implement it.

**Comment by HarshKumarChoudary** [comment]
ok

**Comment by HarshKumarChoudary** [comment]
I am ready with the doc. I have to attach that file here in comment or should  merge in forked branch and create a PR?

**Comment by Rahulm2310** [comment]
@HarshKumarChoudary I think you can create a PR with branch called `research` and post the link to the doc in PR description. This way your PR will be counted towards the `Outreach/Research` category which is one out of 4 categories you must complete for OSH. 
cc: @mtreacy002

**Comment by mtreacy002** [comment]
> @HarshKumarChoudary I think you can create a PR with branch called `research` and post the link to the doc in PR description. This way your PR will be counted towards the `Outreach/Research` category which is one out of 4 categories you must complete for OSH.
> cc: @mtreacy002

I agree with what @Rahulm2310 has suggested.

**Comment by naveen8801** [comment]
Hi @mtreacy002  @Rahulm2310  , can you assign this issue to me also ? :-)

**Comment by Rahulm2310** [comment]
Hello @naveen8801, thanks for showing interest. Actually, @HarshKumarChoudary has researched on this and submitted a google doc with his findings which you can find in our github wiki [here](https://docs.google.com/document/d/1rQIwS6z5xqiRy-il5rkJeghvvIDpA1MYSAcEkihaVOc/edit?usp=sharing). This doc is open for all so feel free to add your findings to this doc so that everything related to this remains at one place. 🙂 
cc: @mtreacy002

**Comment by mtreacy002** [comment]
Closing this issue as @HarshKumarChoudary had proposed the suggested solution [here]https://github.com/anitab-org/bridge-in-tech-web/pull/225)
