### ISSUE TITLE
Dev: Add alternative homepage for remote deployment | URGENT

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#237]
## Description
As a contributor,
I need to add BIT web remote gh pages url `https://anitab-org.github.io/bridge-in-tech-web/` as alternative to `homepage` in package.json
so that contributors can chose to use either local or remote server as BIT frontend

### Update [Required]
- [ ] add the remote gh url above as alternative to `homepage` and comment out option for `localhost:3000`
- [ ] add prefix `/bridge-in-tech-web` to the `<Router>` tag in Routes.js for the remote server (see example used [here](https://github.com/anitab-org/stem-diverse-tv-cms/pull/41/files))

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hr

**Comment by shades-7** [comment]
can i work on this?

**Comment by CIPHERTron** [comment]
Heyy @mtreacy002 , just saw the text in Zulip. I would like to take up this issue. Is it cool?

**Comment by CIPHERTron** [comment]
Heyy @mtreacy002 , just saw the text in Zulip. I would like to take up this issue. Is it cool?

**Comment by jalajcodes** [comment]
@shades-7 This is a first timers issue and as you have contributed to the repo before, I'll assign this to @CIPHERTron .

**Comment by mtreacy002** [comment]
@CIPHERTron , I really appreciate your swift response for this urgent issue. Just a reminder, if you also want to claim this as your Open Source Hack contribution, please don't forget to complete the compulsory task #218 beforehand 😉 . cc @jalajcodes

**Comment by CIPHERTron** [comment]
> @CIPHERTron , I really appreciate your swift response for this urgent issue. Just a reminder, if you also want to claim this as your Open Source Hack contribution, please don't forget to complete the compulsory task #218 beforehand 😉 . cc @jalajcodes

Damn! Do we really need to set up the environment? 
I just changed the two lines that's mentioned in the issue.
Setting up the environment would take up much time though ;)

**Comment by CIPHERTron** [comment]
I thought it was a small issue. NVM
Heyy @shades-7 if you're up, you can take up the issue since you already have the environment already set up.

**Comment by shades-7** [comment]
> I thought it was a small issue. NVM
> Heyy @shades-7 if you're up, you can take up the issue since you already have the environment already set up.

Yes will send the PR soon

**Comment by CIPHERTron** [comment]
Thanks @shades-7 
Also, apologies for the inconvenience ;(

**Comment by shades-7** [comment]
Hey @CIPHERTron you don't have to apologies for anything and you can submit your PR without setting up the environment. It will just not be included in OSH but your PR will get merged if it will fulfill the task.

**Comment by shades-7** [comment]
@CIPHERTron since you have made the changes I will insist you to send PR.

**Comment by CIPHERTron** [comment]
Thanks but I'm cool. Go on, send a PR @shades-7 
I'm kinda running on a deadline too. If time wouldn't have been an issue, I would've set up the environment.
Also, it's against the ethics of open-source. As you know, a small change might also introduce various bugs. haha

**Comment by mtreacy002** [comment]
Sorry for the inconvenience, @CIPHERTron . I do understand setting up can take up sometimes for new contributors. Unfortunately, it is part of the Open Source Hack requirements. Thank you for your honesty. Hopefully once the remote deployment is sorted, it'll help cut down some portion of the lengthy process of local setup. 
@jalajcodes , I'll remove `First-timers only` issue for this issue as this is a pretty urgent issue. @shades-7 , I can assign you to this since you've done the setup and not currently working on an issue, right? you're just waiting for the review on #229, so that's ok. Any other issue you're currently working on?

**Comment by shades-7** [comment]
Yes I have PRs they are under review and I can take this task

**Comment by jalajcodes** [comment]
Its nice to see people aware of Open Source ethics and giving each other chances. Kudos to both of you @shades-7 and @CIPHERTron  👏👏
