### ISSUE TITLE
Bug: Test failed after Link tag is used to replace anchor tag in Register.jsx and Login.jsx

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#239]
### Describe the bug
Recent commit #231 which refactored `anchor <a> tag` to `<Link>` causes tests to fail for Login.test.jsx and Register.test.jsx. 

### To Reproduce
1. Run test
2. See errors

### Screenshots
<img width="565" alt="Screen Shot 2021-04-24 at 9 58 22 am" src="https://user-images.githubusercontent.com/29667122/115940072-9d636380-a4e3-11eb-9b3b-a3c52e8bd1fa.png">
 
### Desktop (please complete the following information):
 - OS: MacOS Catalina 10.15.7
 - Browser: Safari

### Additional context
Other errors also exist. If possible address the issue at the same time.

**Comment by mtreacy002** [comment]
@Rahulm2310 , the errors indicates that `<Link> tag` which replaced `<a>  tag` [here](https://github.com/anitab-org/bridge-in-tech-web/pull/190#discussion_r589071561) was causing the error. Any suggestion on how we can fix this?

**Comment by Rahulm2310** [comment]
@mtreacy002 Found the fix. This is happening because when we render our react component (`<Register/>` or `<Login/>`) in the test cases, they are not wrapped with `<Router/>` due to which this `Error: Uncaught [Error: Invariant failed: You should not use <Link> outside a <Router>]` is shown. I tried wrapping the components `<Router><Register/></Router>` and all test cases passed. 
![image](https://user-images.githubusercontent.com/54268438/115952068-b549e000-a501-11eb-824a-88c848cbc37a.png)

**Comment by mtreacy002** [comment]
That makes sense to me. Thank you @Rahulm2310 for the solution. Would you be able to submit a pr for this? Or should I open it for Open Source Hack?

**Comment by Rahulm2310** [comment]
@mtreacy002 If someone is interested in submitting a PR as a contribution for Open Source Hack, they can surely claim it. 5 more days to go for the wrap up of OSH. If it remains unassigned, I will submit a PR for the fix.

**Comment by shades-7** [comment]
hey i would like to work on this, since all my PR are under review, I am free

**Comment by mtreacy002** [comment]
Sure, @shades-7 will assign you to this now 😉. Thank you for picking up the issue.

**Comment by shades-7** [comment]
> @mtreacy002 Found the fix. This is happening because when we render our react component (`<Register/>` or `<Login/>`) in the test cases, they are not wrapped with `<Router/>` due to which this `Error: Uncaught [Error: Invariant failed: You should not use <Link> outside a <Router>]` is shown. I tried wrapping the components `<Router><Register/></Router>` and all test cases passed.
> ![image](https://user-images.githubusercontent.com/54268438/115952068-b549e000-a501-11eb-824a-88c848cbc37a.png)

![Screenshot from 2021-04-26 00-06-47](https://user-images.githubusercontent.com/58786336/116005160-59777800-a623-11eb-92d1-63e2bb2353cf.png)
### Followed you instructions got 2 test case pass but Getting an error
node_modules/react-dom/cjs/react-dom.development.js:88
      ### Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
          in Register (at Register.test.js:128)
          in Router (created by BrowserRouter)
          in BrowserRouter (at Register.test.js:128)

**Comment by mtreacy002** [comment]
@shades-7 , I wonder why it shows only 2 tests since we have 3 tests altogether 🤔

**Comment by mtreacy002** [comment]
@jalajcodes and @Rahulm2310., can you please give some suggestions to why [this](https://github.com/anitab-org/bridge-in-tech-web/issues/239#issuecomment-826370296) happens?
