### ISSUE TITLE
UI: Temporary side navigation for protected pages

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#250]
### Is your feature request related to a problem? Please describe.
Currently we have PR #230 for Main Navigation that address new design of top navigation as part of BIT redesign project. However, merging the pr will break existing features like viewing members and organizations list, creating/updating organization and program as well as creating/updating users info (all comes under protected pages as per the existing main nav shown in the screenshot below) because the new design for Side Navbar for the Members Area (shown only to the login user) is still in progress by @Vuyanzi .

Existing Main navigation:
![Screen Shot 2021-05-23 at 10 15 19 pm](https://user-images.githubusercontent.com/29667122/119260059-65e7f400-bc14-11eb-99f2-1f74d5f263d2.png)

New Main navigation
![Screen Shot 2021-05-23 at 10 17 08 pm](https://user-images.githubusercontent.com/29667122/119260112-a3e51800-bc14-11eb-9778-ee67f220ff10.png)

### Describe the solution you'd like
To prevent blocking the existing features, we need to implement a temporary Side Navigation that would allow contributors to continue using the existing features that comes under the protected pages. Below is what the temp design look like:

On Open Sidebar:
![Screen Shot 2021-05-23 at 10 08 50 pm](https://user-images.githubusercontent.com/29667122/119260222-2f5ea900-bc15-11eb-92f1-2fa4d9fd888a.png)

On Closed Sidebar:
![Screen Shot 2021-05-23 at 10 22 32 pm](https://user-images.githubusercontent.com/29667122/119260253-646afb80-bc15-11eb-8257-395d931c5454.png)

Position: on the left side of the screen.
Design idea is taken from the [Figma Design ideas](https://www.figma.com/file/gNUHi7wnBYNKKdt0Sl2uvm/BIT-Ayush-Nilesh?node-id=0%3A1) by @VectoTec 

### Describe alternatives you've considered
Once @Vuyanzi completed the new design of Side Navbar, this temp design can be updated with @Vuyanzi 's design.

### Additional context
NA

**Comment by naveen8801** [comment]
hi @mtreacy002 , can i work on this :)

**Comment by mtreacy002** [comment]
Sure, @naveen8801 . But can you please first pull the latest update I just requested on #246 before working on this issue? Thanks 😉

**Comment by arkumari2000** [comment]
If this issue is not taken, can I work on this issue? (Also is the project uses material-ui?)

**Comment by mtreacy002** [comment]
@naveen8801 , since you're still fixing PR #246, I'll assign this to @arkumari2000 . Thanks for your understanding 😉

**Comment by naveen8801** [comment]
No problem @mtreacy002, go ahead @arkumari2000, Happy coding 👍

**Comment by arkumari2000** [comment]
@mtreacy002 can I use styled-components or material-ui?

**Comment by mtreacy002** [comment]
@arkumari2000 , I'm pretty sure you can use either of those two here, but perhaps we can confirm with @Rahulm2310 since he's more experience in this 😉

**Comment by Rahulm2310** [comment]
@mtreacy002  @arkumari2000 I don't think we need any of those libraries to achieve this. This component should be implemented similar to how other designs have been implemented so far.

**Comment by arkumari2000** [comment]
> @mtreacy002 @arkumari2000 I don't think we need any of those libraries to achieve this. This component should be implemented similar to how other designs have been implemented so far.

Can you please help me with some tutorial or content suggestion for this design implementation without styled component or material ui component? As I can see in this project only bootstrap is used and I am unable to find such a design implementation in react-bootstrap. And I think this design is quite complex to implement with pure css.

**Comment by arkumari2000** [comment]
Either if the mentor agrees we can have a fixed non-collapsible navbar on the computer screen or a fully collapsible navbar on both the screen. 
Please consider my suggestion @mtreacy002

**Comment by arkumari2000** [comment]
> @mtreacy002 @arkumari2000 I don't think we need any of those libraries to achieve this. This component should be implemented similar to how other designs have been implemented so far.

okay, It is almost done.
