### ISSUE TITLE
Dev: Move GetInTouch files into home folder

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#253]
### Describe the bug
Currently the `GetInTouch` related files (jsx and css) are placed in the `getInTouch` folder outside `home` folder. 

### To Reproduce
NA

### Expected behavior
To be consistent, all sections on the Homepage need to be placed under the `home` folder.

### Screenshots
<img width="485" alt="Screen Shot 2021-06-10 at 12 34 42 am" src="https://user-images.githubusercontent.com/29667122/121378539-a1a9ea00-c986-11eb-88f9-75e9ade6793c.png">

<img width="494" alt="Screen Shot 2021-06-10 at 12 35 41 am" src="https://user-images.githubusercontent.com/29667122/121378667-bf774f00-c986-11eb-9e22-279f6dd8b95f.png">

**Comment by naveen8801** [comment]
Hi @mtreacy002, I'd like to work on it, please assign :))

**Comment by mtreacy002** [comment]
Sure, @naveen8801 . I'm assigning you to this now. Thanks for picking up the issue 😉.
