### ISSUE TITLE
View User Profile - Personal Details

### ISSUE THREAD

**Issue by foongminwong** [anitab-org/bridge-in-tech-web#27]
## Description
As a user,
I want to view the user profile
so that I can edit my personal user information.

## Out of Scope
 - [ ] Updating profile information
-  [ ] Displaying additional information
-  [ ] Displaying Personal Background

## Mocks
See the latest mock under https://github.com/anitab-org/bridge-in-tech-web/issues/5

## Acceptance Criteria

- [ ] all details present in the mockup must be part of this story. All details should be viewable for this story. Editing the details will be a separate story. 

- [ ] must have section title `Personal Details` with necessary components as per initial mockup or with some modifications approved by mentors
- [ ] must have the following fields:
   - [ ] Username
   - [ ] Email
   - [ ] Name
   - [ ] IRC ID
   - [ ] Option for Available to be a mentor (Mentor, Mentee, Both)
   - [ ] Interest
   - [ ] Bio
   - [ ] Location
   - [ ] Occupation
   - [ ] Organization
   - [ ] Skills

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 - 3 days

**Comment by mtreacy002** [comment]
@meenakshi-dhanani . Can I split this into 3 seeparate sub issues:
* view personal details page
* view additional information page
* view personal background page

Each of this page will come with their own test cases. Combining them into one PR will make the PR too big. What do you think?
