### ISSUE TITLE
SignIn and SignUp page UI inconsistency

### ISSUE THREAD

**Issue by kushal98** [anitab-org/bridge-in-tech-web#271]
### Describe the bug
It is not exactly a bug but some UI inconsistency.

I can see the signin and signup pages having very big checkboxes and that should be aligned and should not be that big.

### To Reproduce
1. Please visit either signin or signup page

### Expected behavior
The expected behaviour is to have that inline with the chechbox text and reduced in size.

### Screenshots
![image](https://user-images.githubusercontent.com/26721689/125425416-9e69795d-a320-43f7-b6e6-0cec30ac98bf.png)
![image](https://user-images.githubusercontent.com/26721689/125425443-fa37772e-2fb6-478d-8af0-f9fbeefaa6df.png)

### Desktop (please complete the following information):
 - OS: macOS
 - Browser: chrome

### Additional context
NA

**Comment by kushal98** [comment]
Please assign this to me.

Thank you

**Comment by stableapple** [comment]
@kushal98 Thanks for bringing this up.  As we are redesigning the website, this issue won't be relevant in the new Sign In(#249) and Sign Up page(#248). I think we can close this issue?

**Comment by mtreacy002** [comment]
I agree with @stableapple , @kushal98 . We just need to make sure the check boxes inconsistency won't happen in the new designs. So, I'm closing this issue now 😉.
