### ISSUE TITLE
UI: High-fidelity Mockup - Login

### ISSUE THREAD

**Issue by foongminwong** [anitab-org/bridge-in-tech-web#3]
## Description
As a student,
I need to create high-fidelity mockup for Login,
so that I can move forward with on the planning stage.

## Mocks
Initial idea (per proposal)
Figure 1.2. Login
<img width="1133" alt="BridgeInTech MockUp - Login" src="https://user-images.githubusercontent.com/29667122/81494743-76217f80-92ee-11ea-9d61-6a4fb4790af2.png">
### Update [Required]
- [x] must have all the fields for BIT system for user login:
       [x] username or email (in case people forget their username)
       [x] password
- [ ] must have `Organization` and `Mentor/Mentee` radio buttons under "Login as"
- [x] must have `Login` (for current users) and `Register` or `Sign Up` (for new users) buttons
- [x] must have `Forgot Password?` hyperlink

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 - 2 days

**Comment by foongminwong** [comment]
@mtreacy002 feel free to edit/insert your proposal `Login` mock on this issue

**Comment by mtreacy002** [comment]
Update:

Login page. 

<img width="931" alt="Screen Shot 2020-05-26 at 9 03 37 am" src="https://user-images.githubusercontent.com/29667122/82847235-603bcd80-9f30-11ea-9fc6-c908e5388072.png">

[link to file](https://www.figma.com/file/jxCqu1lq55H7jC4FDY119a/BridgeInTech?node-id=10%3A1)

**Comment by mtreacy002** [comment]
@anitab-org/bridgeintech-maintainers, I think we don't need the radio button for `Organization` or `Mentor/Mentee` anymore because an organization must be represented by a user who doesn't have to be a mentor or mentee but can be if they want to. Plus, we don't have separate registration form for an organization (its user representative is the one who will create organization profile). So, can we change the `Acceptance Criteria` for this issue to remove this requirement? Thanks

**Comment by mtreacy002** [comment]
Update:

On second thought, I think it's ok to keep the radio button to check if the user is a representative of an organization (so we don't have to query all users data to check if user is rep to get the relevant users_extension table).
So, the latest mockup login I have is as below:

<img width="927" alt="Screen Shot 2020-05-26 at 5 47 54 pm" src="https://user-images.githubusercontent.com/29667122/82874522-6ace8500-9f79-11ea-9e64-d3ed0f8acc18.png">

**Comment by foongminwong** [comment]
> Update:
> 
> On second thought, I think it's ok to keep the radio button to check if the user is a representative of an organization (so we don't have to query all users data to check if user is rep to get the relevant users_extension table).
> So, the latest mockup login I have is as below:
> 
> <img alt="Screen Shot 2020-05-26 at 5 47 54 pm" width="927" src="https://user-images.githubusercontent.com/29667122/82874522-6ace8500-9f79-11ea-9e64-d3ed0f8acc18.png">

Hmm if you are planning to keep the radio buttons on the `Login`, based on your latest mockup, it doesn't have radio buttons. If not, your current mockup looks good

**Comment by mtreacy002** [comment]
Sorry @foongminwong , posted wrong image... 😂 
<img width="868" alt="Screen Shot 2020-05-27 at 9 45 46 am" src="https://user-images.githubusercontent.com/29667122/82960808-e0c8ff80-9ffe-11ea-9ee9-313480536f5c.png">

**Comment by mtreacy002** [comment]
Although, now that I think of it, we can't rely on user on this.Coz, what if the user is `naughty` and say yes, but actually they don't represent an organisation? Or what if the other way around, the user is representing an organisation but they say `no` to the answer (maybe they forgot 😂). If we don't give this option (radio button) then, we just have to look into the user record in the user_extension to see if they are or they are not representing an organisation. This way we have **one source of truth**.. What do you all think, @anitab-org/bridgeintech-maintainers ?

**Comment by mtreacy002** [comment]
Update:
as per discussion on [BIT weekly meeting, Wednesday, May 27th](https://docs.google.com/document/d/1QRHzy0IWgAE5bjkwI_Lp67Dv50aywGuUmzmWewQ1rpY/edit#heading=h.uj7p49x423h) it is decided that we'll go ahead with mockup below

<img width="927" alt="Screen Shot 2020-05-26 at 5 47 54 pm" src="https://user-images.githubusercontent.com/29667122/83209659-2ec73a00-a19c-11ea-9e9e-a037a6e829e2.png">

**Comment by mtreacy002** [comment]
Hi @anitab-org/bridgeintech-maintainers. I prefer if we keep the `forgot password` feature as a `Nice To Have` feature and not `Required` feature. Should I take it out of the Mockup so that it represents what will really work as an MVP?

**Comment by meenakshi-dhanani** [comment]
Yup. I think it makes sense to not include it in the MVP.

**Comment by mtreacy002** [comment]
cool 👍. I'll take it off the mockup then 😉. Thanks for the input, @meenakshi-dhanani

**Comment by mtreacy002** [comment]
Update:
now without `forgot password` link

![Screen Shot 2020-05-30 at 4 53 22 pm](https://user-images.githubusercontent.com/29667122/83321855-3539dc80-a296-11ea-9c89-6dfb574c3978.png)
