### ISSUE TITLE
Autoprefixer 9.8.1 to 9.8.0?

### ISSUE THREAD

**Issue by foongminwong** [anitab-org/bridge-in-tech-web#31]
**Describe the bug**
Tried to reclone `anitab-rg/bridge-in-tech-web` and run BIT web app, and I got this error: 
<code>
./src/register/Register.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./src/register/Register.css)
Error: Package exports for 'C:\Users\foongmin\Desktop\bridge-in-tech-web\node_modules\autoprefixer\node_modules\kleur' do not define a valid './colors' target
</code>

![fail-to-compile-autoprefix](https://user-images.githubusercontent.com/23441795/85651354-61663480-b66d-11ea-96b7-c7205c29310b.png)

**To Reproduce**
1. Clone repo [bridge-in-tech-web](https://github.com/anitab-org/bridge-in-tech-web)
2. Ran `npm install`
3. Ran `npm start`
4. See error: 
    <img width="450" alt="develop-error" src="https://user-images.githubusercontent.com/23441795/85650807-e7817b80-b66b-11ea-8d0f-31688e72a78a.PNG">

**Desktop:**
 - OS: Windows 10

**Additional comments**
- Not sure if any of you  ran into this issue on your local machine
- I downgraded autoprefix to 9.8.0 based on this [post](https://stackoverflow.com/questions/62481678/react-app-failed-to-compile-after-install/62488309?stw=2#62488309), and it works hmm
- If no one encounters this error on their end, feel free to close it

**Comment by mtreacy002** [comment]
@foongminwong  After you clone the repo, did you delete package-lock.json and node_module folder (this folder shouldn't be there, but just in case) before you run npm install?

Please do try this and let me know if this still an issue after that.

**Comment by mtreacy002** [comment]
Also, after the done the above (delete mentioned files and run npm install, try to run `npm run build` first before running nom start. just in case

**Comment by foongminwong** [comment]
Thank you for the help @mtreacy002 ! I reclone the project repo and it worked fine, I'll close it now 👍
