### ISSUE TITLE
Test: write tests for input validations on Login form

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#32]
## Description
As a developer,
I need check if a warning comes up for each of the form fields if input inserted is invalid,
so that I can make sure user insert a valid input.

### Update [Required]
- [ ] Write tests using React Testing Library in the Login.test.js file
- [ ] Test if validation message shows up for username
- [ ] Test if validation message shows up for password

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by khushishikhu** [comment]
can i take this issue?

**Comment by mtreacy002** [comment]
Sure, @khushishikhu , assigning this to you now 😉

**Comment by khushishikhu** [comment]
@mtreacy002  in `Login.jsx` there isn't any validation message code written for Username field. So how we can test this case.

**Comment by mtreacy002** [comment]
@meenakshi-dhanani . Can you please also make it clear on what validation we're actually looking here at frontend? I forgot why we need to do this. 
IMO we don't need to check for input validations on Login form. Because the task to do the validation input on username and password are already handled on the Registration form. In Login form, user simply need to give a valid username and password combination that is checked by the backend against the user credentials. 
Sorry, I know I open the issue, but now that I think of it, it doesn't seems to be a valid issue. Can you please advise?

**Comment by mtreacy002** [comment]
Or, perhaps, we want to test the response message should show `username or password is invalid` in the case of wrong credentials given? And if the input is valid, then the homepage should be rendered as a result with the Navbar showing `Logout` and `Welcome userXXX!` on the top right.?  I think that's more likely the case, @meenakshi-dhanani and @khushishikhu, what do you reckon?

**Comment by khushishikhu** [comment]
@mtreacy002  but the case of wrong credentials is already written. so can you please clarify me what tests i need to do?

**Comment by mtreacy002** [comment]
@khushishikhu . I think you can test if either username or password field is empty, a warning should be shown to user. What do you think? cc @meenakshi-dhanani

**Comment by khushishikhu** [comment]
@mtreacy002  yes it can be done.

**Comment by mtreacy002** [comment]
Thank you @khushishikhu . 
Btw, I've just noticed the culprit on the bug that you raised [here](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech/topic/Questions/near/207783890). It turned out that the `local` option is missing on the `FLASK_ENVIRONMENT_CONFIG`from the template. Thanks for bringing it up to our attention. Have just pushed PR [#123](https://github.com/anitab-org/bridge-in-tech-backend/pull/123) backend to fix this. This really would help the next contributors in setting up their local environment for BIT backend. cc @anitab-org/bridgeintech-maintainers
