### ISSUE TITLE
Test: write test cases for personal details functionality

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#39]
## Description
As a student,
I need write test cases for View user's personal details functionality,
so that I can ensure the View user personal details does what it is supposed to do, allow user to view their personal details.

## Mocks
NA

### Update [Required]
- [ ] write test cases using react-testing-library
- [ ] write test to check if user personal details information are displayed properly from get call
- [ ] write test to check if modified fields are sent in put request for update
 
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

**Comment by meenakshi-dhanani** [comment]
@anitab-org/bridgeintech-maintainers  can you please approve this PR? It's an example for API call unit tests so that @mtreacy002 can do similar tests for other components.
