### ISSUE TITLE
UI: High-fidelity Mockup - Homepage

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#4]
## Description
As a student,
I need to create high-fidelity mockup for Homepage,
so that I can move forward with on the planning stage.

## Mocks 
as per initial proposal:
<img width="855" alt="BridgeInTech MockUp - Homepage" src="https://user-images.githubusercontent.com/29667122/81494778-bda80b80-92ee-11ea-9ba7-482fa7c685e1.png">

### Update [Required]
- [ ] About BridgeInTech section
- [ ] Recent mentoring opportunities section
- [ ] Contact form section
- [ ] Contact details section

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

**Comment by mtreacy002** [comment]
Update:

Here's the Landing (Homepage) Mockup I have in mind. There are 3 internal sections on this Homepage:

1. **About** section
<img width="874" alt="Screen Shot 2020-05-27 at 8 52 08 pm" src="https://user-images.githubusercontent.com/29667122/83010825-341d6b00-a05c-11ea-80ce-c82d137afb5f.png">

2. **Benefit** section
<img width="937" alt="Screen Shot 2020-05-27 at 9 50 23 pm" src="https://user-images.githubusercontent.com/29667122/83015702-2cfa5b00-a064-11ea-95b8-ed9f5bf365c4.png">


3. **Recent Programs** section
<img width="880" alt="Screen Shot 2020-05-27 at 8 55 35 pm" src="https://user-images.githubusercontent.com/29667122/83010949-6f1f9e80-a05c-11ea-901c-c45dda16e452.png">


On `Recent Programs` section, the arrow at the end of each programs when clicked, will open to a `brief program description` as below:
<img width="1444" alt="Screen Shot 2020-05-27 at 8 58 28 pm" src="https://user-images.githubusercontent.com/29667122/83011212-dc333400-a05c-11ea-9632-960684273a45.png">

[link to file](https://www.figma.com/file/jxCqu1lq55H7jC4FDY119a/BridgeInTech?node-id=10%3A1)

**Comment by isabelcosta** [comment]
@mtreacy002 I really love the mockups, it's so much realistic and relatable 🤗

**Comment by mtreacy002** [comment]
Thanks, @isabelcosta. As per your suggestion, I'll keep the Homepage as static page for the MVP. Meaning that the `Recent Programs` section will be for Future Feature 😉

**Comment by mtreacy002** [comment]
Just wanna take notes on possible Reusable components based on the Homepage mockup:

* Public/Non Logged-in users Main-navbar
<img width="706" alt="Screen Shot 2020-05-31 at 9 02 24 pm" src="https://user-images.githubusercontent.com/29667122/83350877-7f988780-a382-11ea-84e5-135886669ff4.png">

* Logged-in users Main-Navbar - Not representative of an organization
<img width="707" alt="Screen Shot 2020-05-31 at 9 02 44 pm" src="https://user-images.githubusercontent.com/29667122/83350892-9a6afc00-a382-11ea-8053-6d65038e1d79.png">

* Logged-in users Main-Navbar - representative of an organization
<img width="707" alt="Screen Shot 2020-05-31 at 9 03 23 pm" src="https://user-images.githubusercontent.com/29667122/83350923-e158f180-a382-11ea-9330-dde26d0aca35.png">

* down/up arrows at the bottom of the Homepage
<img width="62" alt="Screen Shot 2020-05-31 at 9 09 48 pm" src="https://user-images.githubusercontent.com/29667122/83350941-19603480-a383-11ea-8a72-15da141e6ba5.png">

* Sub-Navbar for Homepage
<img width="157" alt="Screen Shot 2020-05-31 at 9 10 59 pm" src="https://user-images.githubusercontent.com/29667122/83350965-4f9db400-a383-11ea-9725-2f7817b2ce5d.png">

**Comment by mtreacy002** [comment]
Also, I've updated the Homepage to the followings:

* About page
<img width="722" alt="Screen Shot 2020-05-31 at 9 14 02 pm" src="https://user-images.githubusercontent.com/29667122/83350997-bae78600-a383-11ea-9898-b7de1599a5f1.png">

* Benefit page
<img width="719" alt="Screen Shot 2020-05-31 at 9 14 09 pm" src="https://user-images.githubusercontent.com/29667122/83351002-c2a72a80-a383-11ea-9f67-652987e0fe54.png">

Note that the tabs inside Main-Navbar will depend on whether user is logged-in or not.
