### ISSUE TITLE
UI: High-fidelity Mockup - Create User Profile

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#5]
## Description
As a student,
I need create a high-fidelity Mockup on Create User Profile,
so that I can move forward with my planning stage.

## Mocks
as per initial proposal
**Figure 4.6. Create Profile**
<img width="501" alt="BridgeInTech MockUp - Create_Profile" src="https://user-images.githubusercontent.com/29667122/81495112-3d36da00-92f1-11ea-8aed-9935103e6a03.png">

### Update [Required]
- [ ] must have section title `Update Profile - Personal Details` with necessary components as per initial mockup or with some modifications approved by mentors
- [ ] must have section title `Update Profile - Additional Information` with necessary components as per initial mockup or with some modifications approved by mentors
- [ ] must have section title `Update Profile - Personal Background` with necessary components as per initial mockup or with some modifications approved by mentors

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

**Comment by mtreacy002** [comment]
Update:
User Profile - Additional Information section

<img width="876" alt="Screen Shot 2020-05-28 at 10 44 23 pm" src="https://user-images.githubusercontent.com/29667122/83143134-d3159600-a134-11ea-96d7-248ffc7a0d87.png">

**Comment by mtreacy002** [comment]
Update: Change the buttons at the bottom

1. User Profile - Personal details

<img width="922" alt="Screen Shot 2020-05-28 at 11 53 12 pm" src="https://user-images.githubusercontent.com/29667122/83150309-79b26480-a13e-11ea-97b4-4c8402de52a6.png">

**Comment by mtreacy002** [comment]
Update: 
2. User Profile - Additional Information

<img width="931" alt="Screen Shot 2020-05-28 at 11 54 40 pm" src="https://user-images.githubusercontent.com/29667122/83150466-a49cb880-a13e-11ea-81da-d60ef7545f96.png">

**Comment by mtreacy002** [comment]
Update:
3. User Profile - Personal Background

<img width="792" alt="Screen Shot 2020-05-29 at 12 12 20 am" src="https://user-images.githubusercontent.com/29667122/83152406-1e35a600-a141-11ea-8525-5b5ec2bc0b4b.png">

**Comment by mtreacy002** [comment]
[Link to file](https://www.figma.com/file/jxCqu1lq55H7jC4FDY119a/BridgeInTech?node-id=10%3A1)

**Comment by mtreacy002** [comment]
Update:
Modified User Profile - Create/Update pages with `My Space` for Main navbar and added sub navbar under this tab

so, when user logged in, they can select the `My Space` tab on main navbar to get to their own `My Portfolio`, `MyProfile` and `My Contact` pages. Under Members tab we'll have the same sections but without `'My...' on the sub nav titles.

Here're the mockups
1. User Profile - Update Personal Details
<img width="822" alt="Screen Shot 2020-05-29 at 3 23 23 pm" src="https://user-images.githubusercontent.com/29667122/83224646-4533bc80-a1c1-11ea-9f31-9cd389cb53f6.png">

2. User - Profile - Update Additional Information
<img width="826" alt="Screen Shot 2020-05-29 at 3 23 30 pm" src="https://user-images.githubusercontent.com/29667122/83224669-52e94200-a1c1-11ea-893b-4b3a1943b156.png">

3. User Profile - Update Personal Background
<img width="832" alt="Screen Shot 2020-05-29 at 3 23 44 pm" src="https://user-images.githubusercontent.com/29667122/83224686-609ec780-a1c1-11ea-8029-99beb0f8d693.png">


Here're what user can see when they click on the `My Profile` tab (to view their profile)
4. User Profile - Personal Details
<img width="910" alt="Screen Shot 2020-05-29 at 3 20 56 pm" src="https://user-images.githubusercontent.com/29667122/83224777-92b02980-a1c1-11ea-95a4-2043da4438f8.png">

5. User Profile - Additional Information
<img width="815" alt="Screen Shot 2020-05-29 at 3 23 12 pm" src="https://user-images.githubusercontent.com/29667122/83224810-a491cc80-a1c1-11ea-90f0-286026a45eae.png">

6. User Profile - Personal Background
<img width="830" alt="Screen Shot 2020-05-29 at 3 23 00 pm" src="https://user-images.githubusercontent.com/29667122/83224796-9f348200-a1c1-11ea-8529-4391a18e00d5.png">

**Comment by mtreacy002** [comment]
Update:
Hi @anitab-org/bridgeintech-maintainers. Changed my mind on the sub nav under My Space section. Now it has `Request History` instead of `My Contact`

(will only put one image here to show the change. But have changed the relevant tabs in the [Figma file](https://www.figma.com/file/jxCqu1lq55H7jC4FDY119a/BridgeInTech?node-id=10%3A1))

<img width="862" alt="Screen Shot 2020-05-29 at 4 35 41 pm" src="https://user-images.githubusercontent.com/29667122/83229179-d9565180-a1ca-11ea-844c-5a208602b03f.png">

**Comment by mtreacy002** [comment]
Note for Reusable components:

* Sub-Navbar for Member users (under `My Space` main-navbar tab)
<img width="360" alt="Screen Shot 2020-05-31 at 9 34 45 pm" src="https://user-images.githubusercontent.com/29667122/83351416-018aaf80-a387-11ea-909f-560f36a627c2.png">

**Comment by foongminwong** [comment]
Suggestions:
* Change `IRC ID` to `Zulip username` or explaining what IRC ID is
* Remove `Exit` button

Note: 3 pages for one user profile

**Comment by foongminwong** [comment]
Self-note: 3 pages for one user profile

**Comment by mtreacy002** [comment]
> Suggestions:
> 
> * Change `IRC ID` to `Zulip username` or explaining what IRC ID is

mmm... the issue is not all organization are the same, some might use Zulip, some might use Slack or other rIRC tools. Can I just add a `?` icon so when user wants further information, they can hover or click and we give them extra information saying "IRC is an Interactive Relay Channel. e.g, Zulip, Slack, Skype, etc"

> * Remove `Exit` button

Yup 👍, will do that.

 
> Note: 3 pages for one user profile

Yup 😊
