### ISSUE TITLE
Create or Update Organization Profile

### ISSUE THREAD

**Issue by foongminwong** [anitab-org/bridge-in-tech-web#51]
## Description
As an organization,
I need to create or update the organization profile BridgeInTech, 
so that I can create or modify the information inside my organization profile.

## Mocks
See mockup under https://github.com/anitab-org/bridge-in-tech-web/issues/6

### Update [Required]
- [ ] must have a button to Save Organization Profile with necessary components as per initial mockup or with some modifications approved by mentors

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors

## Estimation
2 - 3 days

**Comment by 19-pragya** [comment]
can i work on this??

**Comment by mtreacy002** [comment]
I'm closing this issue since this was fixed by PR #69.
