### ISSUE TITLE
UI: High-fidelity Mockup - Create Organization Profile

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#6]
## Description
As a student],
I need create a high-fidelity mockup for Create/Update Organization Profile,
so that I can move ahead with my planning stage.

## Mocks
as per initial proposal:

**Figure 3.3. Create Company Profile**
<img width="851" alt="BridgeInTech MockUp - Create_Company" src="https://user-images.githubusercontent.com/29667122/81495050-aec25880-92f0-11ea-8774-3c949eaac30a.png">

### Update [Required]
- [ ] must have section title Create/Update Organization Profile with necessary components as per initial mockup or with some modifications approved by mentors

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

**Comment by mtreacy002** [comment]
Update:
Hi @anitab-org/bridgeintech-maintainers. Here's the mockup for Organization Profile - Create/Update form. Let me know what you think 😉 

<img width="813" alt="Screen Shot 2020-05-29 at 9 19 22 pm" src="https://user-images.githubusercontent.com/29667122/83254450-1c77eb00-a1f2-11ea-9da0-addf2678340f.png">

**Comment by mtreacy002** [comment]
Update:
And here's the Organization Profile - View Details

![Screen Shot 2020-05-30 at 4 58 47 pm](https://user-images.githubusercontent.com/29667122/83321929-e476b380-a296-11ea-86e8-8a26a4338f38.png)

**Comment by mtreacy002** [comment]
Note: this is only MVP. In the future (Future Feature), we can add a function where the current representative can remove themselves so they are no longer representing the organization by selecting another user on the update form. After the update is successful, the current user will automatically be removed and won't see `My Organization` tab again from their Main Navbar.
It's similar to how `Admin` functionality of MS works I guess, where the current admin can chose another user to be admin which will remove themselves from the position.

**Comment by foongminwong** [comment]
I saw the difference between `Update Organization Profile` and `Organization profile`. When a user clicks `Organization Profile`, it will show the purple one and then after the user clicks `Update`, it will show the orange one. What if the user wants to update again, which button should he/she clicks to update on the orange one? (Just discussed with you, you can put an `Edit` button on the oragne one)

One suggestion: You can put * on `Organization Name`

Dicussion: We just discussed that we can make `Address` not mandatory  (probably in the schema, remove the NOT NULL CONSTRAINT)

**Comment by foongminwong** [comment]
Swap `Exit` button to `Edit` button
