### ISSUE TITLE
Test: Add tests for validations on personal detail fields

### ISSUE THREAD

**Issue by meenakshi-dhanani** [anitab-org/bridge-in-tech-web#64]
## Acceptance Criteria
- [ ] Assert if validation check pops up for username - "Must be between 5-25 characters long. Can only contain alphabets, numbers and underscore _"
- [ ] Asset if validation check pops up for name field - "Must be between 2-30 characters long. Can only contain alphabets, whitespace and dash -"
- [ ] Use the react testing library for writing tests

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
2 hours

**Comment by Shashwati-tidke** [comment]
@meenakshi-dhanani  I would like to work on this issue, Can I?

**Comment by meenakshi-dhanani** [comment]
@Shashwati-tidke sure, assigning this to you. Please read the contribution guidelines before you start. Also, I can assign you to only one issue at a time. When this gets done, I can assign you to another :)

**Comment by Shashwati-tidke** [comment]
Thanks !I  will start working on it

**Comment by mtreacy002** [comment]
@Shashwati-tidke . Can you give us an update on where you upto on this issue? Do you need more time?

**Comment by Aaishpra** [comment]
@mtreacy002 if @Shashwati-tidke is not working on this can i work on this?

**Comment by mtreacy002** [comment]
Sure, @Aaishpra . I'll assign this to you since we didn't get any update from @Shashwati-tidke .
