### ISSUE TITLE
Test: Add tests for validating error message displays when API calls fail

### ISSUE THREAD

**Issue by meenakshi-dhanani** [anitab-org/bridge-in-tech-web#65]
## Acceptance Criteria
- [ ] Test if GET call returns 500, SERVICE_UNAVAILABLE_ERROR message is shown
- [ ] Test if PUT call fails, (status: 500) SERVICE_UNAVAILABLE_ERROR message is displayed on the form
- [ ] Test if GET call returns other status code eg. 403, then server defined message is displayed on screen
- [ ] Test if PUT call returns other status code eg. 400, then server defined message is displayed on screen
- [ ] use msw like existing tests, and react testing library

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
2 hours

**Comment by Shashwati-tidke** [comment]
@meenakshi-dhanani  can i work on this issue?

**Comment by meenakshi-dhanani** [comment]
> @meenakshi-dhanani can i work on this issue?

Hey @Shashwati-tidke , I have already assigned you to one issue.

**Comment by Shashwati-tidke** [comment]
OK,thanks ! :)

**Comment by mtreacy002** [comment]
@Shashwati-tidke . Are you still working on this issue? I've noticed that the status is still stated as available. If you need more time to work on this I can remove the `Status: Available`.

**Comment by mtreacy002** [comment]
@meenakshi-dhanani, can you please remind me again on which page this tests  for validation error messagees need to be done? Can you please add that information on the issue description? Thanks

**Comment by mtreacy002** [comment]
@meenakshi-dhanani , I'll close this issue since the task on this issue is to broad and there were smaller issues have been created to test validation error messages specific to a particular View page.
