### ISSUE TITLE
Create the config.yml file for the Welcome Bot

### ISSUE THREAD

**Issue by Frenzyritz13** [anitab-org/bridge-in-tech-web#66]
## Description
 As a first time contributor,
 I need a bot to help guide my first contribution,
 so that I can follow this org's contribution guidelines.
 
 ## Mocks
 ![Screen Shot 2020-08-06 at 10 26 14 AM](https://user-images.githubusercontent.com/2440938/89543720-44299780-d7cf-11ea-82a0-bd81664f0d8e.png)
 
 ## Acceptance Criteria
 ### Update [Required]
 * [ ]  newIssueWelcomeComment is complete with the correct links to this repo.
 * [ ]  newPRWelcomeComment is complete with the links to the project's stream or topic and the repo's Code of Conduct.
 * [ ]  firstPRMergeComment is complete.
 
 ## Definition of Done
 * [ ]  All of the required items are completed.
 * [ ]  Approval by 1 mentor.
 
 ## Estimation
 0.5 hours

**Comment by Aaishpra** [comment]
@Frenzyritz13 can i work on this

**Comment by Aaishpra** [comment]
can anyone please assign this to me

**Comment by mtreacy002** [comment]
@Aaishpra , I'm assigning this to you, since @Frenzyritz13 didn't seem to currently working on it. cc @anitab-org/bridgeintech-maintainers

**Comment by Aaishpra** [comment]
Sure ! Thanks

> @Aaishpra , I'm assigning this to you, since @Frenzyritz13 didn't seem to currently working on it. cc @anitab-org/bridgeintech-maintainers

Sure

**Comment by aastha985** [comment]
Hi! Can I work on this issue? @mtreacy002

**Comment by mtreacy002** [comment]
Definitely. I'll assign this to you, @aastha985
