### ISSUE TITLE
Fix: typos on Register Form

### ISSUE THREAD

**Issue by meenakshi-dhanani** [anitab-org/bridge-in-tech-web#67]
You will find the typos in the `Register.jsx` file
## Acceptance Criteria
- [x] Rename the text on the form from "Register Form" -> "Register"
- [x] "Already register?" to "Already registered?"
- [x] "Login here" -> "Click on Login"

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

**Comment by Manav-03** [comment]
Please review my PR.

**Comment by isabelcosta** [comment]
@Manav-03 before creating a PR you have to be assigned. So the usual procedure is to ask to work on it or be assigned, then managers and maintainers can assign this to you and then you can submit a PR. Can you please do that the next time? :)

**Comment by 19-pragya** [comment]
can i work on this

**Comment by meenakshi-dhanani** [comment]
@19-pragya Apologies, the issue is already assigned. Maybe you can work on another one :)

**Comment by 19-pragya** [comment]
@meenakshi-dhanani  can you please suggest me some other issues??

**Comment by Manav-03** [comment]
@isabelcosta Just getting familiar with how it works. I'll make sure I
follow that procedure next time. Thank you. :)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_1767839287791138943_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
