### ISSUE TITLE
Fix: typo on Login form

### ISSUE THREAD

**Issue by meenakshi-dhanani** [anitab-org/bridge-in-tech-web#68]
You will find typos in the `Login.jsx` file.

## Acceptance Criteria
- [x] Change from  "Not yet register?" -> "Not yet registered?"
- [x] Instead of "Sign up here" -> "Click on Sign Up"

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

**Comment by Manav-03** [comment]
Please check my PR.

**Comment by 19-pragya** [comment]
can i work on this issue??

**Comment by isabelcosta** [comment]
@19-pragya I will assign this to you, since @Manav-03 already sent a PR to another first timer issue.

**Comment by 19-pragya** [comment]
@isabelcosta  thankyou mam!! please have a look, here i have made changes
https://github.com/anitab-org/bridge-in-tech-web/pull/73
