### ISSUE TITLE
UI: High-fidelity Mockup - Create Program

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#7]
## Description
As a student,
I need to create a high-fidelity mockup on Create Program,
so that I can move forward with the planning stage.

## Mocks
**Figure 4.1. Create Program 1/3**
<img width="848" alt="BridgeInTech MockUp - Create_Program1of3" src="https://user-images.githubusercontent.com/29667122/81495056-c568af80-92f0-11ea-870c-4ee9bf9c63f9.png">

**Figure 4.2. Create Program 2/3**
<img width="853" alt="BridgeInTech MockUp - Create_Program2of3" src="https://user-images.githubusercontent.com/29667122/81495064-db767000-92f0-11ea-996e-e038210ad6bd.png">

**Figure 4.3. Create Program 3/3**
<img width="1133" alt="BridgeInTech MockUp - Create_Program3of3" src="https://user-images.githubusercontent.com/29667122/81495071-e5986e80-92f0-11ea-8d4a-0e2659274fd2.png">

### Update [Required]
- [ ] Must have the Create Program components as per initial mockup or with some adjustments that are approved by the mentors

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

**Comment by 19-pragya** [comment]
can i work on this

**Comment by meenakshi-dhanani** [comment]
@19-pragya you might want to filter issues on the repository that have a label as Status:Available
