### ISSUE TITLE
Register a user

### ISSUE THREAD

**Issue by foongminwong** [anitab-org/bridge-in-tech-web#8]
## Description
As a user,
I want to register on BIT,
So that I can sign up as mentor/mentee for programs I like

## Mocks
See the latest mock under https://github.com/anitab-org/bridge-in-tech-web/issues/2

## Linked Issue
[Create Registration API](https://github.com/anitab-org/bridge-in-tech-backend/issues/24
)
## Out of Scope
Handling duplicate registrations

### Update [Required]

- [ ] **Given** I am on registration page, 
       **When** I submit all details successfully,
       **Then** I see a message saying registration was successful. 

- [ ] **Given** I submit the registration form,
       **When** I receive an error from the backend service,
       **Then** I see a message saying there was an error 

- [ ] must have all the fields for Mentorship System user registration:
       [ ] name
       [ ] username
       [ ] email
       [ ] password(should be masked)
       [ ] terms and conditions
- [ ] must have available to be a `Mentor`, `Mentee` radio buttons
- [ ] must have `Signup` and `Login` buttons

- [ ] **Given** I am on the registration page,
        **When** I click on submit after filling the form,
        **Then** I see validation errors on the UI if any one of the following are an issue
        Email does not match xxx@xxx.com, password does not follow a combination of at least 1 
        digit, at least special character, at least uppercase letter, and length as 12 characters, confirm 
        password does not match password, any of the mandatory fields are missing, terms and 
        conditions is not checked. 
        
        Name: Min length = 2 , max length = 30
        Username: min = 5 max = 25
        Password: min = 8 max = 64
        Email: please match the pattern

For the "name" field to be valid, it may contain one or more character from:
- letter "a" to "z" and/or "A" to "Z", 
- any of the whitespace characters, and/or
- special character "-".

For the "email" field to be valid, it must have the following structure:
> the first section, which may contain one or more character from:
    - letter "a" to "z" and/or "A" to "Z",
    - number "0" to "9",
    - special character "_", ".", "+", and/or "-".
> followed by the "@" character,
> followed by the second section, which may contain one or more character from:
    - letter "a" to "z" and/or "A" to "Z",
    - number "0" to "9", and/or
    - special character "-".
> followed by the escaped character ".",
> followed by the third section, which may contain one or more character from:
    - letter "a" to "z" and/or "A" to "Z",
    - number "0" to "9",
    - special character "-" and/or ".".

For the "username" field to be valid, it may contain one or more character from:
    - letter "a" to "z" and/or "A" to "Z",
    - number "0" to "9", and/or
    - special character "-".

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
2-3 days

**Comment by meenakshi-dhanani** [comment]
Hey @foongminwong, since a user story is supposed to be of value to the customer, I'm going to modify the acceptance criteria to include the backend as well. It needs to be a complete slice (frontend + backend) to have a working story. Hope that's okay

**Comment by foongminwong** [comment]
> Hey @foongminwong, since a user story is supposed to be of value to the customer, I'm going to modify the acceptance criteria to include the backend as well. It needs to be a complete slice (frontend + backend) to have a working story. Hope that's okay

Yes! Feel free to make changes on the issue :)

**Comment by mtreacy002** [comment]
Thanks, @meenakshi-dhanani and @foongminwong for preparing this issue. I'll touch on it as soon as I'm done with backend [issue#24](https://github.com/anitab-org/bridge-in-tech-backend/issues/24) 😉 
Just a note for password validation, @anitab-org/bridgeintech-maintainers, the rules we'll apply here must be used across all mentorship system backend and frontend (android) as well. We cannot have different rules for these 4 (MS+BIT front+back) because we only have one source of truth, MS backend. Can you please open a discussion stream on zulip and get to an agreement what rules we should apply on this, just so we won't have issues in the future. Thanks for your understanding.

**Comment by mtreacy002** [comment]
Actually, please don't open a new issue or channel on Zulip. I have started a discussion on this in [issue#710](https://github.com/anitab-org/mentorship-android/issues/710) mentorship android) and Zulip topic [#Common input validations](https://anitab-org.zulipchat.com/#narrow/stream/222534-mentorship-system/topic/Common.20Input.20validations) under mentorship-system channel. So, please use these existing ones instead. Thanks

**Comment by meenakshi-dhanani** [comment]
@mtreacy002 I have updated the validation details on this. Validation needs to be a check on the front end, as well on the backend API. I'll add it to that issue as well. In case someone bypasses the front end and hits the API, the backend needs to be protected too.
