### ISSUE TITLE
Feat: Add show/hide password toggle functionality on password fields

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#84]
**Is your feature request related to a problem? Please describe.**
At the moment password field has no show/hide visibility option on the login and register form.

**Describe the solution you'd like**
Password fields need to have a show/hide visibility option so they can check their input on the field.

**Describe alternatives you've considered**
Open to contributor's idea as long as it fits the application well.

**Additional context**
NA

**Comment by heyanurag** [comment]
Can I try solving this issue? I am a first time contributor participating in Open Source Hack

**Comment by mtreacy002** [comment]
HI @singhanurag05 . Thank you for showing an interest on contributing to BridgeInTech project. You are most welcome to work on the issue. Although, I have to make it clear that as far as I'm aware, this project is not one of the projects listed on the Open Source Hack (in fact only 3 projects are selected for the Open Source Hack). If I'm not mistaken, the 3 selected projects are [vms](https://github.com/anitab-org/vms), [mentorship-backend](https://github.com/anitab-org/mentorship-backend) and [mentorship-android](https://github.com/anitab-org/mentorship-android/). You can find the [issues that counted towards the event](https://github.com/search?l=&q=org%3Aanitab-org+label%3A%22Open+Source+Hack%22&type=Issues) (Open Source Hack) have been labelled with `Open Source Hack` on them. 
Regardless, you're more than welcomed to work on this issue. Let mee know if you're still interested, I'll then assign you to this issue 😉. cc @anitab-org/coding-team, can you please confirm that this is the case?

**Comment by anna4j** [comment]
Yes that is correct @mtreacy002

**Comment by heyanurag** [comment]
I would like to try this. How much time will I get to complete the task?

**Comment by mtreacy002** [comment]
That's good. Take how ever long you need, @singhanurag05, but please make sure you give us update on your progress. We normally ask you for an update if after 3 days you don't show activity on the PR, just to see if you need more time to work on it or if you are facing some blockers that we could help you with. But you will still be able to continue to work on it till it's completed. Again, thank you for your interest to this project. I'll assign this issue to you now. 😉

**Comment by heyanurag** [comment]
Thank you! On  it.

**Comment by heyanurag** [comment]
Hi @mtreacy002, I had some doubts regarding setting up the environment. Do I ask them right here or do we have a slack channel or something?

**Comment by mtreacy002** [comment]
@singhanurag05 , can you please ask on the Zulip channel under #bridge-in-tech > Dev env setup. It would help others who might come across the same issue.

**Comment by ruppysuppy** [comment]
I would like to work on this issue. Would a checkbox below (saying "show password" do)? And where do I have to add them (login and register)?

**Comment by mtreacy002** [comment]
@ruppysuppy . sure, you can work on this. Yup, a checkbox will do. This feature need to be applied on both Login and Register form. Although, I suggest you start with Login form first. I'd prefer if PR #89 (confirm password field) is approved first so wheen you work on it on Register form, the checkbox will work on both `password` and `confirm password` fields. @anitab-org/bridgeintech-maintainers or @anitab-org/coding-team , can someone please review PR #89. It only needs one more review as I've already approved it.
