### ISSUE TITLE
Feat: Add confirrm password field and validation to Register form

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#85]
**Is your feature request related to a problem? Please describe.**
At the moment there is no confirm password field on the Register form.

**Describe the solution you'd like**
Confirm password field and its validation (checking that the password and confirm password fields match) is useful to help user confirm the password they have given on the password field. 

**Describe alternatives you've considered**
Open to contributor's idea as long as it fits the application well.

**Additional context**
NA

**Comment by ruppysuppy** [comment]
I would like to work on this issue

**Comment by mtreacy002** [comment]
Yup, @ruppysuppy , you can work on this issue now 👍
