### ISSUE TITLE
Feat: Disable `Go to Programs` and `Save` buttons on Organization Profile page if user is not an organization representative.

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#86]
**Is your feature request related to a problem? Please describe.**
At the moment for login user who is not an organization representative (has not declared that they are), when they go to `My Organization`, on the Organization Profile page they can try to click on the `Go to Programs` or `Save` buttons which should've been prevented.

**Describe the solution you'd like**
Disable the `Go to Prrograms` and `Save` buttons on Organization Profile page if login user is not (has not declared) an organization representative.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ruppysuppy** [comment]
> At the moment for login user who is not an organization representative (has not declared that they are), when they go to `My Organization`, on the Organization Profile page they can try to click on the `Go to Programs` or `Save` buttons which should've been prevented.

I would like to work on this issue. Could you tell me how to check if the logged in user is an organization representative?

**Comment by mtreacy002** [comment]
@ruppysuppy , when you run the app, you'll notice that if the user has not declared that they represent an organization, when they try to open the organization page under `My Space`, this error message will be returned.
<img width="1054" alt="Screen Shot 2020-10-07 at 5 21 42 pm" src="https://user-images.githubusercontent.com/29667122/95309206-9160dd00-08d6-11eb-9ef3-97f0eaa4f958.png">

This error is there since when the user open the page, the GET /organization request is made to backend

<img width="481" alt="Screen Shot 2020-10-07 at 7 45 08 pm" src="https://user-images.githubusercontent.com/29667122/95309670-3085d480-08d7-11eb-8cf7-60a6e34e5edd.png">

You can use this as the the deciding factor. Meaning, if this particular response is shown, then the `Go to programs` should be disabled. Does this make sense?

**Comment by ruppysuppy** [comment]
Ok, I'll start working on it tomorrow

> <img alt="Screen Shot 2020-10-07 at 7 45 08 pm" width="481" src="https://user-images.githubusercontent.com/29667122/95309670-3085d480-08d7-11eb-8cf7-60a6e34e5edd.png">
> 
> You can use this as the the deciding factor. Meaning, if this particular response is shown, then the Go to programs should be disabled. Does this make sense?

@mtreacy002 please clarify one thing for me, only in case of `!responseMessage`, I should display `Go to Programs` and `Save` buttons?

**Comment by mtreacy002** [comment]
@ruppysuppy . Sorry for the late reply. To be precise, if the response is not HTTPStatus.OK (200) then the `Go to programs` button should be disable. Only when the response message is 200 then the button should be enable. Does this make sense?

**Comment by ruppysuppy** [comment]
Its ok. I am currently a bit caught up in various tasks, I won't have time to work on this issue. Sorry @mtreacy002

**Comment by mtreacy002** [comment]
That's alright, @ruppysuppy . Thanks for letting me know. 😉

**Comment by ankitpal1029** [comment]
can i work on this? i am new to open source and have some experience with react apps

**Comment by mtreacy002** [comment]
Suree, @ankitpal1029 . I'll assign you to this. Thanks for picking up the issue.

**Comment by ankitpal1029** [comment]
Thanks , I'll set up the backend and frontend  client locally and let you know if I have any difficulties

**Comment by ankitpal1029** [comment]
![Screenshot from 2020-10-13 17-29-46](https://user-images.githubusercontent.com/49815751/95857792-c313f100-0d79-11eb-8581-0ebd1faf21c5.png)
i was following this step of setting up the backend

when i ran run.py i get this error 
![Screenshot from 2020-10-13 17-29-13](https://user-images.githubusercontent.com/49815751/95857890-e50d7380-0d79-11eb-9dae-7978f6d5b1b3.png)
i installed all the requirement packages in the venv as mentioned in the setup guide
can you help me out

**Comment by ankitpal1029** [comment]
![Screenshot from 2020-10-13 18-01-44](https://user-images.githubusercontent.com/49815751/95860813-31f34900-0d7e-11eb-97e8-3e04c92e2ac7.png)
can you guide me as to what some of these environment variables are

**Comment by saideepesh000** [comment]
> ![Screenshot from 2020-10-13 18-01-44](https://user-images.githubusercontent.com/49815751/95860813-31f34900-0d7e-11eb-97e8-3e04c92e2ac7.png)
> can you guide me as to what some of these environment variables are 

If you followed the database setup from the Wiki correctly, you can put these values, except for 'DB_PASSWORD', it needs to be your postgre password which you did setup during the postgre installation.

![IMG20201013223733.jpg](https://user-images.githubusercontent.com/43727167/95892836-beb0fd80-0da4-11eb-937d-a065cad3de33.jpg)

**Comment by ankitpal1029** [comment]
thanks i did that and run.py ran without any errors

**Comment by ankitpal1029** [comment]
this is the mentorship-backend run.py
![image](https://user-images.githubusercontent.com/49815751/96004376-f2e5f600-0e58-11eb-82a2-ca8f881591ef.png)


this is the bridge-in-tech-backend
![image](https://user-images.githubusercontent.com/49815751/96004357-eb265180-0e58-11eb-9491-27324dbd7b11.png)



the client says the server is unavailable despite both the servers being run,what am i doing wrong?

**Comment by ankitpal1029** [comment]
this is the mentorship-backend run.py
![image](https://user-images.githubusercontent.com/49815751/96004533-26288500-0e59-11eb-9e74-1a9b44216b8c.png)

this is the bridge-in-tech-backendt
![Uploading image.png…]()

he client says the server is unavailable despite both the servers being run,what am i doing wrong?
![Uploading image.png…]()

**Comment by ankitpal1029** [comment]
this is the mentorship backend:
![image](https://user-images.githubusercontent.com/49815751/96004777-6ab42080-0e59-11eb-871b-da6adddab13f.png)

this is the bridge-in-tech-backend:
![image](https://user-images.githubusercontent.com/49815751/96004802-71db2e80-0e59-11eb-9798-374914eacb33.png)

he client says the server is unavailable despite both the servers being run,what am i doing wrong?
![image](https://user-images.githubusercontent.com/49815751/96004826-7869a600-0e59-11eb-8d49-b4fcf7da924e.png)

**Comment by mtreacy002** [comment]
@ankitpal1029 . Did you run MS backend from my fork repo ms-backend-server branch as mentioned in the setup instruction? If you try to run from the develop branch it will not work.

Also, perhaps not related to the issue, but VERY IMPORTANT STEP. If this is your first time running them, you must click the link given to open the swagger UI and create the database tables (IMPORTANT: click on the BridgeInTech backend link first instead of Mentorship Sytem backend link. Otherwise you'll get the wrong tables).

**Comment by mtreacy002** [comment]
Also, try and confirm that BIT backend can talk to MS backend by registering a new user using the swagger UI of BIT backend. Once these backends connection is established (through a successful registration), you can try again running the frontend and see if it works.

**Comment by mtreacy002** [comment]
PS: can you please show me screenshots of your .env for both BIT and MS backends (please remove/hide any personal credentials like email address and password)

**Comment by ankitpal1029** [comment]
![Screenshot from 2020-10-15 21-37-27](https://user-images.githubusercontent.com/49815751/96156434-aff65200-0f2e-11eb-9620-20cad8019630.png)
these are the .env variables for both the backends
![Screenshot from 2020-10-15 21-37-39](https://user-images.githubusercontent.com/49815751/96156506-c69ca900-0f2e-11eb-8517-5da23e715dc0.png)
this probably means that the backends aren't communicating with each other not sure what's the reason

i redid the process of setting up the MS backend by forking this repo and following the instructions just to be sure
https://github.com/mtreacy002/mentorship-backend/tree/ms-backend-server
but still wasn't able to register a new user

**Comment by ankitpal1029** [comment]
> Also, perhaps not related to the issue, but VERY IMPORTANT STEP. If this is your first time running them, you must click the link given to open the swagger UI and create the database tables (IMPORTANT: click on the BridgeInTech backend link first instead of Mentorship Sytem backend link. Otherwise you'll get the wrong tables).

i don't understand what you mean by click on BIT backend first

**Comment by ankitpal1029** [comment]
although during setup of both the backends i needed to pip install psycopg seperately as the version mentioned in the requirements.txt was throwing up errors

**Comment by mtreacy002** [comment]
Ok, here are a couple of things you neeed to do:
* you must use the exact same .env variables for both MS and BIT backend. Meaning, the one on the right (14 lines) would be the closes one you need to have (with some modification below)
* Try put actual values instead of empty string '    '  for each of the variables (I never tried using empty string like you or @saideepesh000 so not sure how that works)
* Please use the outgoing server address given by your email provider. For example, I'm using `mail.com` in the .env since they use less security measures compared to Gmail. Their outgoing server is `smtp.mail.com`. So, that is the value I use for the `MAIL_SERVER` variable (so don't use localhost). 
* Once you are using real email account, don't forget to add real values for `APP_MAIL_USERNAME` and `APP_MAIL_PASSWORD` which is your email account credentials (that's why using `mail.com` account only for development purpose is useful since you don't have to worry about the seccurity of your email account).
* Please set the `FLASK_ENVIRONMENT_CONFIG` as `local` and since you are using Windows, make sure you follow the extra steps mentioned on [section 7th of the BIT backend setup](https://github.com/anitab-org/bridge-in-tech-backend/wiki/BIT-development-environment-setup#7th-create-the-env-file-using-envtemplate)
<img width="692" alt="Screen Shot 2020-10-16 at 3 25 55 pm" src="https://user-images.githubusercontent.com/29667122/96214312-dbc51680-0fc6-11eb-82eb-c820503f8d77.png">


* Even though I use an actual email service, I prefer to use MOCK_EMAIL feature in our app (so I set `MOCK_EMAIL` as True). This way the email would be printed to the terrminal (so there is no need to open the inbox of my email account on the browser).
* Make sure there is no space in between the `=` sign for each of the variables.

**Comment by mtreacy002** [comment]
Here's a screenshot of my .env for both BIT and MS backend on Windows laptop (CMD terminal)
<img width="261" alt="env" src="https://user-images.githubusercontent.com/29667122/96214707-cb616b80-0fc7-11eb-82df-1617a4aa560a.PNG">

**Comment by ankitpal1029** [comment]
i did the .env changes and also realised there was a path error since i compiled postgres during setup rather than just sudo apt get it , 
upon reinstalling postgresql i was able to create a user finally

![image](https://user-images.githubusercontent.com/49815751/96290283-f7024700-1003-11eb-92db-579b86cbe92c.png)

although when i try running the front end i'm still not able to make a new organisation 
![image](https://user-images.githubusercontent.com/49815751/96290389-1ef1aa80-1004-11eb-940e-0c8ac999edb8.png)

tables were generated upon first running run.py of BIT as shown below
![image](https://user-images.githubusercontent.com/49815751/96290675-a0493d00-1004-11eb-91e1-394c834c1337.png)

**Comment by ankitpal1029** [comment]
i am not able to understand why the front end still shows server unavailable

**Comment by mtreacy002** [comment]
@ankitpal1029 . I'm glad to see that you are now able to link BIT and MS backend. Just curious, can you send me the screenshot of your user table to see the newly registered user record?

On the frontend not able to connect to backend, can you please send me the screenshots of what's been printed on both MS and BIT backend terminal when the frontend send the register request? You did have them (BIT and MS backend servers) running at the same time with frontend, right?

**Comment by ankitpal1029** [comment]
sorry for the late reply ,

below are the tables in bitschema and public respectively
![Screenshot from 2020-10-18 00-39-00](https://user-images.githubusercontent.com/49815751/96351625-57fc4e80-10da-11eb-92e9-ac19f73122fd.png)
![Screenshot from 2020-10-18 00-36-20](https://user-images.githubusercontent.com/49815751/96351629-5fbbf300-10da-11eb-976e-759ca89d2436.png)
these are the terminal outputs for both the servers upon tryiing to login followed by an attempt to register ,
![Screenshot from 2020-10-17 23-58-57](https://user-images.githubusercontent.com/49815751/96351656-a27dcb00-10da-11eb-9f4b-b43ed27cf3ab.png)
![Screenshot from 2020-10-17 23-59-10](https://user-images.githubusercontent.com/49815751/96351662-a578bb80-10da-11eb-8cf9-616b8206309d.png)

**Comment by ankitpal1029** [comment]
> @ankitpal1029 . I'm glad to see that you are now able to link BIT and MS backend. Just curious, can you send me the screenshot of your user table to see the newly registered user record?
> 
> On the frontend not able to connect to backend, can you please send me the screenshots of what's been printed on both MS and BIT backend terminal when the frontend send the register request? You did have them (BIT and MS backend servers) running at the same time with frontend, right?

@mtreacy002  both the servers are running when i launch the client

**Comment by mtreacy002** [comment]
@ankitpal1029 , let's try to troubleshoot this one step at a time. Now I can see that you haven't confirmed the email verification on register (from the users table record). With this, when you try to log in on swagger UI BIT backend it should come with an error message "Please verify your email before login.". Can you please confirm that this is the case? Can you tell me what the response is after you confirm the email and try to login again (using Swagger UI)? I just want to make sure that all features at the backend work as expected before we go troubleshoot frontend.

**Comment by saideepesh000** [comment]
@ankitpal1029 , @mtreacy002, I actually did this in windows, I've got to run the servers in the first go, I'm not sure why is this happening, actually for user email verification, I did directly in postgre database, I changed it to true(is_email_verified: true), and then I tried to login in. After that everything went as expected.

**Comment by mtreacy002** [comment]
> @ankitpal1029 , @mtreacy002, I actually did this in windows, I've got to run the servers in the first go, I'm not sure why is this happening, actually for user email verification, I did directly in postgre database, I changed it to true(is_email_verified: true), and then I tried to login in. After that everything went as expected.

That (verifying email directly on postgresql database) is also a good alternative to mock email, @saideepesh000. Thank you for sharing 👍

**Comment by ankitpal1029** [comment]
@saideepesh000 editing the db from pgadmin made it a lot easier to login thanks for that,
@mtreacy002 i was indeed able to login from BIT swagger ui ,
although i did find this in the dev tools 
![image](https://user-images.githubusercontent.com/49815751/96372791-41abcc80-1186-11eb-9478-d1366b1901dd.png)
i also found this SO query in a simailar situation 
https://stackoverflow.com/questions/54371815/cors-issue-with-django-and-react-hosted-on-same-server
i tried looking through  the backend code but couldn't find any CORS configuration

**Comment by ankitpal1029** [comment]
upon digging a little more turns out by changing it from 5000 to 3000 works since the app was allowing requests only from  localhost 5000 previously , 
also i'm not sure about this but why is the BIT backend allowing it's own local host i.e 5000
![image](https://user-images.githubusercontent.com/49815751/96373883-eaf5c100-118c-11eb-9079-89abe7a71959.png)
i was able to finally login 
![Screenshot from 2020-10-18 21-58-08](https://user-images.githubusercontent.com/49815751/96373929-2db79900-118d-11eb-8152-f9171cd93ea3.png)

**Comment by mtreacy002** [comment]
Hi @ankitpal1029 . that is strange. I don't know how your local develop branch of BIT backend can get localhost:5000  as the allowed origin, bcoz on both Anitab (upstream) and your own fork repo develop branch, I could see the port being what it is supposed to be (localhost:3000). 
* anitab upstream develop branch
<img width="927" alt="Screen Shot 2020-10-19 at 9 54 35 am" src="https://user-images.githubusercontent.com/29667122/96388022-e57e9200-11f1-11eb-9fab-a2a469f4f37f.png">

* your fork repo develop branch
<img width="937" alt="Screen Shot 2020-10-19 at 9 55 26 am" src="https://user-images.githubusercontent.com/29667122/96388037-047d2400-11f2-11eb-8a34-8d02f240aa46.png">

Perhaps there's an accidental change made somehow in the process of troubleshooting? But anyway, I'm glad that the issue is now solved. Look forward to the PR 😉

**Comment by ankitpal1029** [comment]
Probably the case although I'm not sure how I managed to change that ,@mtreacy002 thanks a lot for helping me through the setup process despite multiple issues (some self created 😅). I'll look into to the issue and send a PR asap.

**Comment by ankitpal1029** [comment]
@mtreacy002 i have made the PR , kindly take a look at it

**Comment by Amulya-coder** [comment]
This issue is available for the Open Source hack whoever claims this issue `first` on 1st April get assigned to it be ready for the hack :)

**Comment by mtreacy002** [comment]
Closing this issue since it appears to no longer be an issue (possibly had been fixed through #118 as well)
