### ISSUE TITLE
UI Repository base setup 

### ISSUE THREAD

**Issue by meenakshi-dhanani** [anitab-org/bridge-in-tech-web#9]
## Description
Have a setup working with all dependencies and required directory structure. 

## Acceptance Criteria
- [x] create a base setup for a react app
- [ ] add dependencies for testing
- [x] you should be able to build and run your app

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 2 mentor.

## Estimation
1 day

**Comment by mtreacy002** [comment]
@meenakshi-dhanani. Just wanna check.
So, I've created the basic setup for react using create-react-app boilerplate and merge it with the existing files/folder from the bridge-in-tech-web. The react app run successfully. Would this suffice for this issue? If so, I'll open the PR and push the code changes.

<img width="1680" alt="Screen Shot 2020-06-02 at 7 31 10 pm" src="https://user-images.githubusercontent.com/29667122/83504393-cc599b00-a507-11ea-94c3-f1e81603a2b2.png">

**Comment by meenakshi-dhanani** [comment]
Replace the default page with a default page for your app. Maybe have Bridge-in-tech and some 1-2 line description and that should be enough :)

**Comment by mtreacy002** [comment]
Ok 👍 will work on it..

**Comment by meenakshi-dhanani** [comment]
All looks good. Except this directory called js(Not a really meaningful name) and it has just one file so again it doesn't need to be extracted into a directory. In future when you have multiple related files, choose to move them to related directories. 

My suggestion: Put Home.jsx back to the src directory. Remove js directory
