### ISSUE TITLE
Doc : Some Grammatical Error in Readme and Setup guide.

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/bridge-in-tech-web#90]
**Describe the bug**
Some Grammatical Errors in Readme and Setup guide.

**Screenshots for what changes should be added**
![image](https://user-images.githubusercontent.com/66299533/92225873-79560200-eec1-11ea-9d75-792266e37eae.png)
![image](https://user-images.githubusercontent.com/66299533/92225930-8b37a500-eec1-11ea-9d8d-b323ba5b9bbd.png)
![image](https://user-images.githubusercontent.com/66299533/92225963-97bbfd80-eec1-11ea-8d97-9ce8b8868f89.png)

**Additional context**
Fixed them and linking a PR.

**Comment by Aaishpra** [comment]
@mtreacy002 please take a look at the issue and tell me if I can link a PR with this. If yes I am done with the changes and would submit a PR if you assign this to me

**Comment by mtreacy002** [comment]
It's ok with me. cc @anitab-org/bridgeintech-maintainers. I can assign you on this.

**Comment by mtreacy002** [comment]
@Aaishpra . I changed my mind. can you please finish PR #88 that you've been working on? It's not far to go.

**Comment by Aaishpra** [comment]
No Problem @mtreacy002 but i have linked a PR
