### ISSUE TITLE
Feat: View About page

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#96]
## Description
As a public user,
I need see `About` page,
so that I can see infomation about the BridgeInTech Application.

## Mocks
Based on [Target MVP](https://www.figma.com/file/jxCqu1lq55H7jC4FDY119a/BridgeInTech?node-id=10%3A1), add a content describing what BridgeInTech application is about: 
<img width="1098" alt="Screen Shot 2020-09-16 at 4 35 57 pm" src="https://user-images.githubusercontent.com/29667122/93300761-bf548380-f83a-11ea-99a3-7629a0ce7231.png">

### Update [Required]
- [ ] Add content to the `About` page (sub menu under Home).
- [ ] Although the design is not the main focus, a reasonable layout is expected. 
- [ ] Avoid changing the Navbar layout in this PR as it is not required
- [ ] Link to `Read more about the project here...` with the [BridgeInTech Frontend Wiki repository](https://github.com/anitab-org/bridge-in-tech-web/wiki).

### Enhancement to Update [Optional]
- [ ] Image can be taken from the source refered on the Figma MVP above or can be replaced with other imagee (IMPORTANT: Please be careful with copyright issue. Make sure you give a visual refence to the source of image).

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

**Additional Information**
To do this task, you do not need to setup BridgeInTech Backend environment (if you haven't already done so), since there is no login required.

**Comment by mtreacy002** [comment]
@anitab-org/bridgeintech-maintainers , will this issue suitable for a first-timers-only issue? The task is to add static content and image. Feel free to remove the `First Timer Only` label if you think the difficulty level doesn't match.

**Comment by HeroicHitesh** [comment]
@mtreacy002 I am interested to contribute for this issue. Can I work on it?

**Comment by mtreacy002** [comment]
Sure,  @HeroicHitesh. I'll assign you now 😉.

**Comment by HeroicHitesh** [comment]
@mtreacy002 I am a bit confused here, the thing is I am unable to find the About component in the repo. Is it already there with some other name and we need to add static content which is shown in the image? or do we need to create the component and then add the text?
I am ok with doing any of them, but just for clarification, I am asking.

**Comment by mtreacy002** [comment]
@HeroicHitesh , when you run the app, you could see that the content in the `/about` page is blank (even though the route and Navbar menu has that as an option). You just need to add content as per shown on the image above. Does this answer your question?

<img width="1680" alt="Screen Shot 2020-09-17 at 2 31 42 pm" src="https://user-images.githubusercontent.com/29667122/93420640-b8894780-f8f2-11ea-9926-06a8629b588c.png">

**Comment by HeroicHitesh** [comment]
@mtreacy002 Not really, actually I found the `About` section in UI, but can't find a .js file for it

>  You just need to add content as per shown on the image above.

By this do you mean we need to add text(content) to a particular file which is already there, or do we need to create `About.js` and then add content in that, this is my main doubt.

**Comment by mtreacy002** [comment]
Can you tell me which file (that is already there) that you're talking about, @HeroicHitesh ?

**Comment by mtreacy002** [comment]
Sorry, correction, @HeroicHitesh. yes, you need to create `About.jsx` ad add content to it. Don't add it to any existing file as It needs to be kept separate per page.

**Comment by HeroicHitesh** [comment]
Thanks @mtreacy002, now my doubt's cleared, also do we need to keep these `.jsx` file in some folder say `Navigation` or for now, we are putting them in `src` only?

**Comment by mtreacy002** [comment]
Yes, please. Now that we have more then just Home under Home Navtab, you can put all pages .jsx files that comes under Home (including Home.jsx itself) to a new folder under `src` to keep it consistent with the rest of the code. 
So, that folder will have `Home.jsx`, `About.jsx` and later `Benefit.jsx`.

**Comment by HeroicHitesh** [comment]
Also, @mtreacy002 do we need this `Photo by fauxels from Pexerillie` to be added in the `About` page or do we have some other photo that needs to be added?

**Comment by HeroicHitesh** [comment]
And @mtreacy002  for AnitaB.org Mentorship System, where should I hyperlink it to? Is [this](https://anitab.org/resources/mentorship/) ok?
Also, how are the hyperlinks required to open, in a new tab or the same tab?

**Comment by mtreacy002** [comment]
@HeroicHitesh, you can use this figma photo by fauxels. If you have any other picture in mind, feel free to use it. Just make sure there is no copyright issue that will come from using that image. Make sure you give appropriate credit to the image source. 

Hyperlink should be directed to the [Mentorship System Backend project repository](https://github.com/anitab-org/mentorship-backend/wiki). The link above is to Mentoring programs held by AnitaB but not necessarily will be using the Mentorship System (as it is still in production).

**Comment by HeroicHitesh** [comment]
<img width="1440" alt="Screenshot 2020-09-17 at 12 50 38 PM" src="https://user-images.githubusercontent.com/37622734/93433495-7bb65400-f8e4-11ea-9eb6-47e1412a3ba0.png">

@mtreacy002 Does this look good? I am creating an MR for this, if changes are needed let me know.

**Comment by mtreacy002** [comment]
Yep, that looks good, @HeroicHitesh 👍. Ou, I forgot to answer your question. can you please make the link open in a new tab when user click on it? Coz we want to make user stay longer in our site to keep their curiosity undistracted, if you know what I mean 😁

**Comment by HeroicHitesh** [comment]
> Yep, that looks good, @HeroicHitesh 👍. Ou, I forgot to answer your question. can you please make the link open in a new tab when user click on it? Coz we want to make user stay longer in our site to keep their curiosity undistracted, if you know what I mean 😁

Thanks. Yeah I did that only, I thought of the same thing. Just sending a PR in about 15mins
