### ISSUE TITLE
Feat: View Benefit page

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#97]
## Description
As a public user,
I need see `Benefit` page,
so that I can read about the benefit becoming a member of BridgeInTech.

## Mocks
Based on the [target MVP](https://www.figma.com/file/jxCqu1lq55H7jC4FDY119a/BridgeInTech?node-id=10%3A1), add a content describing what the benefits are for becoming a member of BridgeInTech:
<img width="1092" alt="Screen Shot 2020-09-16 at 4 50 47 pm" src="https://user-images.githubusercontent.com/29667122/93302278-0e9bb380-f83d-11ea-89e9-e69c1b086641.png">

### Update [Required]
- [ ] Add content to the `Benefit` page (sub menu under Home).
- [ ] Although the design is not the main focus, a reasonable layout is expected. 
- [ ] Avoid changing the Navbar layout in this PR as it is not required
### Enhancement to Update [Optional]
- [ ] Image can be taken from the source refered on the Figma MVP above or can be replaced with other imagee (IMPORTANT: Please be careful with copyright issue. Make sure you give a visual refence to the source of image).

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

**Additional Information**
To do this task, you do not need to setup BridgeInTech Backend environment (if you haven't already done so), since there is no login required.

**Comment by mtreacy002** [comment]
@anitab-org/bridgeintech-maintainers , will this issue suitable for a first-timers-only issue? The task is to add static content and image. Feel free to remove the `First Timer Only` label if you think the difficulty level doesn't match.

**Comment by prathmeshkhandelwal1** [comment]
I would like to work on this issue can you assign this to me??
@mtreacy002

**Comment by mtreacy002** [comment]
> I would like to work on this issue can you assign this to me??
> @mtreacy002

Sure, @prathmeshkhandelwal1 , I’ll assign you to work on this 👍

**Comment by prathmeshkhandelwal1** [comment]
@mtreacy002 Can you plz tell me where to get help if i stuck somewhere :(

**Comment by mtreacy002** [comment]
@prathmeshkhandelwal1 , the Heroku backend at the moment is not working because of the scaling issue, which is out of our control (since we can only using the free service that has limited capability and not able to take up BridgeInTech architecture). I wrote a blog explaining about it [here](https://medium.com/anitab-org-open-source/why-you-cant-use-heroku-free-dynos-in-multiple-servers-dependent-application-fa1cdd9e9e07?source=friends_link&sk=281bb76050f052c03c6772e9be275f67). I’m still looking for alternative solution (perhaps using AnitaB.Org Open Source AWS account). So, the only available option for now is setting up using the local servers. But for PR [97](https://github.com/anitab-org/bridge-in-tech-web/issues/97) that you are working on now, you won’t need to have the backend servers running as no login is required when viewing the page. 
Although, you can still choose to set up the local backend servers to have them ready for the next issue you are interested on. Let me know if you have trouble setting up the local servers 😉

**Comment by mtreacy002** [comment]
@prathmeshkhandelwal1 , you can always ping me or @anitab-org/coding-team or @anitab-org/bridgeintech-maintainers on the pr or issue itself and/or Zulip #bridge-in-tech stream. This way, If I am not available, someone in the community will get  back to you.

**Comment by prathmeshkhandelwal1** [comment]
@mtreacy002 thanku for this info. I will submit a PR by tommorow.

**Comment by prathmeshkhandelwal1** [comment]
@mtreacy002 Can you pllzz help me in finding the list bullet style? or i can use simple disc as a list style?

**Comment by prathmeshkhandelwal1** [comment]
![Screenshot (109)](https://user-images.githubusercontent.com/56167998/93566632-f9dd2e00-f9aa-11ea-95bb-9aff695e1c32.png)
As for now i used square type of list style.

**Comment by prathmeshkhandelwal1** [comment]
@mtreacy002  and also where to link that anchor tag which is on second point in Our Goals section.

**Comment by mtreacy002** [comment]
> As for now i used square type of list style.

Square ones looks good too, @prathmeshkhandelwal1 . 👍

The page looks awesome @prathmeshkhandelwal1 ✨✨👍

**Comment by mtreacy002** [comment]
> @mtreacy002 and also where to link that anchor tag which is on second point in Our Goals section.

The link on the Figma file should be clickable. But in case you can't access it, it's this link: https://www.techrepublic.com/article/how-to-close-the-tech-skills-gap/

**Comment by mtreacy002** [comment]
@prathmeshkhandelwal1 , don't forget to place source image info on the images. 😉

**Comment by prathmeshkhandelwal1** [comment]
> > As for now i used square type of list style.
> 
> Square ones looks good too, @prathmeshkhandelwal1 . 👍
> 
> The page looks awesome @prathmeshkhandelwal1 ✨✨👍

@mtreacy002 Thankyou so much, Submitting a PR in 30 mins with some final changes.

**Comment by prathmeshkhandelwal1** [comment]
> @prathmeshkhandelwal1 , don't forget to place source image info on the images. 😉

I did'nt get this, can you explain it in little bit more detail?

**Comment by mtreacy002** [comment]
Sorry, I must've forgotten to add the text on Figma file for the image on the top let like I had done in About page image to state the source of image. I tried to look on Pexel website since that's where I got it from, but couldn't find the same one again. But I'm sure it will be ok (no copyright infringement) since I'm using the free stuff from that website anyway.

**Comment by prathmeshkhandelwal1** [comment]
> Sorry, I must've forgotten to add the text on Figma file for the image on the top let like I had done in About page image to state the source of image. I tried to look on Pexel website since that's where I got it from, but couldn't find the same one again. But I'm sure it will be ok (no copyright infringement) since I'm using the free stuff from that website anyway.

@mtreacy002 Ohk, then it's super fine as there is no issue with images. 
Also i have done the PR :)

**Comment by mtreacy002** [comment]
Great, I'll go and check it out now 😉
