### ISSUE TITLE
Feat: Add link to AnitaB.Org Open Source contact page on sub menu `Contact` under `Home`

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-web#98]
## Description
As a public user,
I need see a contact page for AnitaB.Org Open Source,
so that I know who to contact if I want to ask something in regard to BridgeInTech.

## Mocks
NA

### Update [Required]
- [ ] The `Contact` sub menu under `Home` Navbar must redirect user to [AnitaB.Org Contact Page](https://anitab.org/contact/)

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Additional Information**
To do this task, you do not need to setup BridgeInTech Backend environment (if you haven't already done so), since there is no login required.

**Comment by Harshita-Kanal** [comment]
Can I take this up ?

**Comment by mtreacy002** [comment]
Definitely, @Harshita-Kanal. I'll assign you now. Thanks for picking up the issue 😉
